Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    BramFactor: 1000000000
    IOType: io_stream
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 4
KerasModel: !keras_model 'projeto_iris_hls_ip_axi/keras_model.keras'
OutputDir: projeto_iris_hls_ip_axi
OutputPredictions: null
OutputShapes:
  layer7_out:
  - 3
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: d7d9f3eb
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
