// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_val1,
        data_1_val2,
        data_2_val3,
        data_3_val4,
        data_4_val5,
        data_5_val6,
        data_6_val7,
        data_7_val8,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] data_0_val1;
input  [15:0] data_1_val2;
input  [15:0] data_2_val3;
input  [15:0] data_3_val4;
input  [15:0] data_4_val5;
input  [15:0] data_5_val6;
input  [15:0] data_6_val7;
input  [15:0] data_7_val8;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [14:0] trunc_ln_reg_1522;
wire    ap_block_pp0_stage0_11001;
reg   [13:0] trunc_ln42_2_reg_1527;
reg   [14:0] trunc_ln42_10_reg_1532;
reg   [12:0] trunc_ln42_11_reg_1537;
reg   [15:0] trunc_ln42_13_reg_1542;
reg   [15:0] trunc_ln42_14_reg_1547;
wire   [15:0] add_ln58_fu_1393_p2;
reg   [15:0] add_ln58_reg_1552;
wire   [15:0] add_ln58_1_fu_1399_p2;
reg   [15:0] add_ln58_1_reg_1557;
wire   [15:0] add_ln58_8_fu_1405_p2;
reg   [15:0] add_ln58_8_reg_1562;
wire   [15:0] add_ln58_9_fu_1411_p2;
reg   [15:0] add_ln58_9_reg_1567;
wire   [14:0] add_ln58_13_fu_1427_p2;
reg   [14:0] add_ln58_13_reg_1572;
wire   [9:0] mul_ln73_2_fu_154_p1;
wire    ap_block_pp0_stage0;
wire   [8:0] mul_ln73_fu_155_p1;
wire  signed [15:0] mul_ln42_2_fu_156_p0;
wire  signed [25:0] sext_ln73_fu_1226_p1;
wire  signed [10:0] mul_ln42_2_fu_156_p1;
wire   [6:0] mul_ln73_5_fu_157_p1;
wire  signed [15:0] mul_ln73_7_fu_158_p0;
wire  signed [25:0] sext_ln42_7_fu_1367_p1;
wire  signed [9:0] mul_ln73_7_fu_158_p1;
wire   [9:0] mul_ln73_3_fu_160_p1;
wire  signed [15:0] mul_ln42_4_fu_161_p0;
wire  signed [10:0] mul_ln42_4_fu_161_p1;
wire  signed [10:0] mul_ln42_fu_162_p1;
wire   [8:0] mul_ln73_4_fu_163_p1;
wire  signed [15:0] mul_ln42_1_fu_166_p0;
wire  signed [25:0] sext_ln70_2_fu_1200_p1;
wire   [10:0] mul_ln42_1_fu_166_p1;
wire  signed [15:0] mul_ln73_1_fu_167_p0;
wire   [9:0] mul_ln73_1_fu_167_p1;
wire  signed [15:0] mul_ln42_3_fu_168_p0;
wire   [10:0] mul_ln42_3_fu_168_p1;
wire   [7:0] mul_ln73_6_fu_169_p1;
wire  signed [15:0] sext_ln70_fu_1094_p0;
wire  signed [15:0] sext_ln70_1_fu_1098_p0;
wire   [24:0] mul_ln73_fu_155_p2;
wire  signed [15:0] tmp_fu_1113_p1;
wire   [18:0] tmp_fu_1113_p3;
wire  signed [20:0] sext_ln73_2_fu_1121_p1;
wire  signed [20:0] sext_ln70_fu_1094_p1;
wire   [20:0] add_ln73_fu_1125_p2;
wire   [10:0] trunc_ln42_1_fu_1131_p4;
wire  signed [15:0] sext_ln42_2_fu_1145_p0;
wire  signed [15:0] tmp_1_fu_1150_p1;
wire   [22:0] tmp_1_fu_1150_p3;
wire  signed [15:0] tmp_2_fu_1162_p1;
wire   [16:0] tmp_2_fu_1162_p3;
wire  signed [23:0] sext_ln73_4_fu_1170_p1;
wire  signed [23:0] sext_ln73_3_fu_1158_p1;
wire   [23:0] sub_ln73_fu_1174_p2;
wire   [25:0] mul_ln42_fu_162_p2;
wire   [25:0] mul_ln42_1_fu_166_p2;
wire   [25:0] mul_ln73_1_fu_167_p2;
wire   [25:0] mul_ln42_2_fu_156_p2;
wire   [25:0] mul_ln42_3_fu_168_p2;
wire  signed [15:0] sext_ln42_4_fu_1252_p0;
wire   [25:0] mul_ln73_2_fu_154_p2;
wire  signed [15:0] p_shl_fu_1267_p1;
wire  signed [15:0] tmp_3_fu_1275_p1;
wire   [23:0] tmp_3_fu_1275_p3;
wire  signed [25:0] sext_ln42_8_fu_1283_p1;
wire   [25:0] p_shl_fu_1267_p3;
wire   [25:0] sub_ln42_fu_1287_p2;
wire  signed [15:0] sext_ln70_3_fu_1303_p0;
wire  signed [15:0] sext_ln70_4_fu_1308_p0;
wire   [25:0] mul_ln73_3_fu_160_p2;
wire   [24:0] mul_ln73_4_fu_163_p2;
wire  signed [15:0] sext_ln70_5_fu_1333_p0;
wire  signed [15:0] sext_ln70_6_fu_1338_p0;
wire   [22:0] mul_ln73_5_fu_157_p2;
wire   [23:0] mul_ln73_6_fu_169_p2;
wire   [13:0] trunc_ln42_12_fu_1353_p4;
wire   [25:0] mul_ln73_7_fu_158_p2;
wire   [25:0] mul_ln42_4_fu_161_p2;
wire   [15:0] trunc_ln42_4_fu_1206_p4;
wire   [15:0] trunc_ln42_6_fu_1232_p4;
wire   [15:0] trunc_ln42_8_fu_1257_p4;
wire   [15:0] trunc_ln42_s_fu_1313_p4;
wire   [15:0] trunc_ln42_3_fu_1190_p4;
wire   [15:0] trunc_ln42_5_fu_1216_p4;
wire   [15:0] trunc_ln42_7_fu_1242_p4;
wire   [15:0] trunc_ln42_9_fu_1293_p4;
wire  signed [11:0] sext_ln42_1_fu_1141_p1;
wire   [11:0] add_ln58_12_fu_1417_p2;
wire  signed [14:0] sext_ln58_2_fu_1423_p1;
wire  signed [14:0] sext_ln42_6_fu_1363_p1;
wire  signed [15:0] sext_ln42_fu_1433_p1;
wire  signed [13:0] sext_ln73_1_fu_1442_p1;
wire   [13:0] add_ln58_4_fu_1454_p2;
wire  signed [14:0] sext_ln58_fu_1460_p1;
wire  signed [14:0] sext_ln42_3_fu_1436_p1;
wire   [14:0] add_ln58_5_fu_1464_p2;
wire  signed [15:0] sext_ln58_1_fu_1470_p1;
wire   [15:0] add_ln58_3_fu_1449_p2;
wire   [15:0] add_ln58_6_fu_1474_p2;
wire   [15:0] add_ln58_2_fu_1445_p2;
wire  signed [15:0] sext_ln42_5_fu_1439_p1;
wire  signed [15:0] sext_ln58_3_fu_1495_p1;
wire   [15:0] add_ln58_11_fu_1490_p2;
wire   [15:0] add_ln58_14_fu_1498_p2;
wire   [15:0] add_ln58_10_fu_1486_p2;
wire   [15:0] add_ln58_7_fu_1480_p2;
wire   [15:0] add_ln58_15_fu_1504_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U441(
    .din0(sext_ln42_4_fu_1252_p0),
    .din1(mul_ln73_2_fu_154_p1),
    .dout(mul_ln73_2_fu_154_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U442(
    .din0(sext_ln70_1_fu_1098_p0),
    .din1(mul_ln73_fu_155_p1),
    .dout(mul_ln73_fu_155_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U443(
    .din0(mul_ln42_2_fu_156_p0),
    .din1(mul_ln42_2_fu_156_p1),
    .dout(mul_ln42_2_fu_156_p2)
);

myproject_mul_16s_7ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_1_1_U444(
    .din0(sext_ln70_6_fu_1338_p0),
    .din1(mul_ln73_5_fu_157_p1),
    .dout(mul_ln73_5_fu_157_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U445(
    .din0(mul_ln73_7_fu_158_p0),
    .din1(mul_ln73_7_fu_158_p1),
    .dout(mul_ln73_7_fu_158_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U446(
    .din0(sext_ln70_4_fu_1308_p0),
    .din1(mul_ln73_3_fu_160_p1),
    .dout(mul_ln73_3_fu_160_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U447(
    .din0(mul_ln42_4_fu_161_p0),
    .din1(mul_ln42_4_fu_161_p1),
    .dout(mul_ln42_4_fu_161_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U448(
    .din0(sext_ln42_2_fu_1145_p0),
    .din1(mul_ln42_fu_162_p1),
    .dout(mul_ln42_fu_162_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U449(
    .din0(sext_ln70_3_fu_1303_p0),
    .din1(mul_ln73_4_fu_163_p1),
    .dout(mul_ln73_4_fu_163_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U450(
    .din0(mul_ln42_1_fu_166_p0),
    .din1(mul_ln42_1_fu_166_p1),
    .dout(mul_ln42_1_fu_166_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U451(
    .din0(mul_ln73_1_fu_167_p0),
    .din1(mul_ln73_1_fu_167_p1),
    .dout(mul_ln73_1_fu_167_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U452(
    .din0(mul_ln42_3_fu_168_p0),
    .din1(mul_ln42_3_fu_168_p1),
    .dout(mul_ln42_3_fu_168_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U453(
    .din0(sext_ln70_5_fu_1333_p0),
    .din1(mul_ln73_6_fu_169_p1),
    .dout(mul_ln73_6_fu_169_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_13_reg_1572 <= add_ln58_13_fu_1427_p2;
        add_ln58_1_reg_1557 <= add_ln58_1_fu_1399_p2;
        add_ln58_8_reg_1562 <= add_ln58_8_fu_1405_p2;
        add_ln58_9_reg_1567 <= add_ln58_9_fu_1411_p2;
        add_ln58_reg_1552 <= add_ln58_fu_1393_p2;
        trunc_ln42_10_reg_1532 <= {{mul_ln73_4_fu_163_p2[24:10]}};
        trunc_ln42_11_reg_1537 <= {{mul_ln73_5_fu_157_p2[22:10]}};
        trunc_ln42_13_reg_1542 <= {{mul_ln73_7_fu_158_p2[25:10]}};
        trunc_ln42_14_reg_1547 <= {{mul_ln42_4_fu_161_p2[25:10]}};
        trunc_ln42_2_reg_1527 <= {{sub_ln73_fu_1174_p2[23:10]}};
        trunc_ln_reg_1522 <= {{mul_ln73_fu_155_p2[24:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_10_fu_1486_p2 = (add_ln58_9_reg_1567 + add_ln58_8_reg_1562);

assign add_ln58_11_fu_1490_p2 = ($signed(trunc_ln42_14_reg_1547) + $signed(sext_ln42_5_fu_1439_p1));

assign add_ln58_12_fu_1417_p2 = ($signed(sext_ln42_1_fu_1141_p1) + $signed(12'd4049));

assign add_ln58_13_fu_1427_p2 = ($signed(sext_ln58_2_fu_1423_p1) + $signed(sext_ln42_6_fu_1363_p1));

assign add_ln58_14_fu_1498_p2 = ($signed(sext_ln58_3_fu_1495_p1) + $signed(add_ln58_11_fu_1490_p2));

assign add_ln58_15_fu_1504_p2 = (add_ln58_14_fu_1498_p2 + add_ln58_10_fu_1486_p2);

assign add_ln58_1_fu_1399_p2 = (trunc_ln42_8_fu_1257_p4 + trunc_ln42_s_fu_1313_p4);

assign add_ln58_2_fu_1445_p2 = (add_ln58_1_reg_1557 + add_ln58_reg_1552);

assign add_ln58_3_fu_1449_p2 = ($signed(trunc_ln42_13_reg_1542) + $signed(sext_ln42_fu_1433_p1));

assign add_ln58_4_fu_1454_p2 = ($signed(sext_ln73_1_fu_1442_p1) + $signed(14'd46));

assign add_ln58_5_fu_1464_p2 = ($signed(sext_ln58_fu_1460_p1) + $signed(sext_ln42_3_fu_1436_p1));

assign add_ln58_6_fu_1474_p2 = ($signed(sext_ln58_1_fu_1470_p1) + $signed(add_ln58_3_fu_1449_p2));

assign add_ln58_7_fu_1480_p2 = (add_ln58_6_fu_1474_p2 + add_ln58_2_fu_1445_p2);

assign add_ln58_8_fu_1405_p2 = (trunc_ln42_3_fu_1190_p4 + trunc_ln42_5_fu_1216_p4);

assign add_ln58_9_fu_1411_p2 = (trunc_ln42_7_fu_1242_p4 + trunc_ln42_9_fu_1293_p4);

assign add_ln58_fu_1393_p2 = (trunc_ln42_4_fu_1206_p4 + trunc_ln42_6_fu_1232_p4);

assign add_ln73_fu_1125_p2 = ($signed(sext_ln73_2_fu_1121_p1) + $signed(sext_ln70_fu_1094_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = add_ln58_7_fu_1480_p2;

assign ap_return_1 = add_ln58_15_fu_1504_p2;

assign mul_ln42_1_fu_166_p0 = sext_ln70_2_fu_1200_p1;

assign mul_ln42_1_fu_166_p1 = 26'd646;

assign mul_ln42_2_fu_156_p0 = sext_ln73_fu_1226_p1;

assign mul_ln42_2_fu_156_p1 = 26'd67108044;

assign mul_ln42_3_fu_168_p0 = sext_ln73_fu_1226_p1;

assign mul_ln42_3_fu_168_p1 = 26'd582;

assign mul_ln42_4_fu_161_p0 = sext_ln42_7_fu_1367_p1;

assign mul_ln42_4_fu_161_p1 = 26'd67108147;

assign mul_ln42_fu_162_p1 = 26'd67108162;

assign mul_ln73_1_fu_167_p0 = sext_ln70_2_fu_1200_p1;

assign mul_ln73_1_fu_167_p1 = 26'd291;

assign mul_ln73_2_fu_154_p1 = 26'd393;

assign mul_ln73_3_fu_160_p1 = 26'd494;

assign mul_ln73_4_fu_163_p1 = 25'd200;

assign mul_ln73_5_fu_157_p1 = 23'd43;

assign mul_ln73_6_fu_169_p1 = 24'd125;

assign mul_ln73_7_fu_158_p0 = sext_ln42_7_fu_1367_p1;

assign mul_ln73_7_fu_158_p1 = 26'd67108370;

assign mul_ln73_fu_155_p1 = 25'd236;

assign p_shl_fu_1267_p1 = data_4_val5;

assign p_shl_fu_1267_p3 = {{p_shl_fu_1267_p1}, {10'd0}};

assign sext_ln42_1_fu_1141_p1 = $signed(trunc_ln42_1_fu_1131_p4);

assign sext_ln42_2_fu_1145_p0 = data_1_val2;

assign sext_ln42_3_fu_1436_p1 = $signed(trunc_ln42_2_reg_1527);

assign sext_ln42_4_fu_1252_p0 = data_4_val5;

assign sext_ln42_5_fu_1439_p1 = $signed(trunc_ln42_10_reg_1532);

assign sext_ln42_6_fu_1363_p1 = $signed(trunc_ln42_12_fu_1353_p4);

assign sext_ln42_7_fu_1367_p1 = $signed(data_7_val8);

assign sext_ln42_8_fu_1283_p1 = $signed(tmp_3_fu_1275_p3);

assign sext_ln42_fu_1433_p1 = $signed(trunc_ln_reg_1522);

assign sext_ln58_1_fu_1470_p1 = $signed(add_ln58_5_fu_1464_p2);

assign sext_ln58_2_fu_1423_p1 = $signed(add_ln58_12_fu_1417_p2);

assign sext_ln58_3_fu_1495_p1 = $signed(add_ln58_13_reg_1572);

assign sext_ln58_fu_1460_p1 = $signed(add_ln58_4_fu_1454_p2);

assign sext_ln70_1_fu_1098_p0 = data_0_val1;

assign sext_ln70_2_fu_1200_p1 = $signed(data_2_val3);

assign sext_ln70_3_fu_1303_p0 = data_5_val6;

assign sext_ln70_4_fu_1308_p0 = data_5_val6;

assign sext_ln70_5_fu_1333_p0 = data_6_val7;

assign sext_ln70_6_fu_1338_p0 = data_6_val7;

assign sext_ln70_fu_1094_p0 = data_0_val1;

assign sext_ln70_fu_1094_p1 = sext_ln70_fu_1094_p0;

assign sext_ln73_1_fu_1442_p1 = $signed(trunc_ln42_11_reg_1537);

assign sext_ln73_2_fu_1121_p1 = $signed(tmp_fu_1113_p3);

assign sext_ln73_3_fu_1158_p1 = $signed(tmp_1_fu_1150_p3);

assign sext_ln73_4_fu_1170_p1 = $signed(tmp_2_fu_1162_p3);

assign sext_ln73_fu_1226_p1 = $signed(data_3_val4);

assign sub_ln42_fu_1287_p2 = ($signed(sext_ln42_8_fu_1283_p1) - $signed(p_shl_fu_1267_p3));

assign sub_ln73_fu_1174_p2 = ($signed(sext_ln73_4_fu_1170_p1) - $signed(sext_ln73_3_fu_1158_p1));

assign tmp_1_fu_1150_p1 = data_1_val2;

assign tmp_1_fu_1150_p3 = {{tmp_1_fu_1150_p1}, {7'd0}};

assign tmp_2_fu_1162_p1 = data_1_val2;

assign tmp_2_fu_1162_p3 = {{tmp_2_fu_1162_p1}, {1'd0}};

assign tmp_3_fu_1275_p1 = data_4_val5;

assign tmp_3_fu_1275_p3 = {{tmp_3_fu_1275_p1}, {8'd0}};

assign tmp_fu_1113_p1 = data_0_val1;

assign tmp_fu_1113_p3 = {{tmp_fu_1113_p1}, {3'd0}};

assign trunc_ln42_12_fu_1353_p4 = {{mul_ln73_6_fu_169_p2[23:10]}};

assign trunc_ln42_1_fu_1131_p4 = {{add_ln73_fu_1125_p2[20:10]}};

assign trunc_ln42_3_fu_1190_p4 = {{mul_ln42_fu_162_p2[25:10]}};

assign trunc_ln42_4_fu_1206_p4 = {{mul_ln42_1_fu_166_p2[25:10]}};

assign trunc_ln42_5_fu_1216_p4 = {{mul_ln73_1_fu_167_p2[25:10]}};

assign trunc_ln42_6_fu_1232_p4 = {{mul_ln42_2_fu_156_p2[25:10]}};

assign trunc_ln42_7_fu_1242_p4 = {{mul_ln42_3_fu_168_p2[25:10]}};

assign trunc_ln42_8_fu_1257_p4 = {{mul_ln73_2_fu_154_p2[25:10]}};

assign trunc_ln42_9_fu_1293_p4 = {{sub_ln42_fu_1287_p2[25:10]}};

assign trunc_ln42_s_fu_1313_p4 = {{mul_ln73_3_fu_160_p2[25:10]}};

endmodule //myproject_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s
