// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_8u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [255:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;
output  [127:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer3_out_read;
reg layer4_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer3_out_blk_n;
reg    layer4_out_blk_n;
wire    ap_CS_fsm_state4;
wire   [15:0] data_fu_117_p1;
reg   [15:0] data_reg_316;
reg    ap_block_state1;
reg   [15:0] data_33_reg_321;
reg   [15:0] data_19_reg_326;
reg   [15:0] data_20_reg_331;
reg   [15:0] data_21_reg_336;
reg   [15:0] data_22_reg_341;
reg   [15:0] data_23_reg_346;
reg   [15:0] data_24_reg_351;
reg   [15:0] data_25_reg_356;
reg   [15:0] data_26_reg_361;
reg   [15:0] data_27_reg_366;
reg   [15:0] data_28_reg_371;
reg   [15:0] data_29_reg_376;
reg   [15:0] data_30_reg_381;
reg   [15:0] data_31_reg_386;
reg   [15:0] data_32_reg_391;
reg   [15:0] res_reg_396;
wire    ap_CS_fsm_state3;
reg   [15:0] res_1_reg_401;
reg   [15:0] res_2_reg_406;
reg   [15:0] res_3_reg_411;
reg   [15:0] res_4_reg_416;
reg   [15:0] res_5_reg_421;
reg   [15:0] res_6_reg_426;
reg   [15:0] res_7_reg_431;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_done;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_idle;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_ready;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_0;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_1;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_2;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_3;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_4;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_5;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_6;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_7;
reg    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start_reg = 1'b0;
end

myproject_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start),
    .ap_done(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_done),
    .ap_idle(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_idle),
    .ap_ready(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_ready),
    .data_0_val1(data_reg_316),
    .data_1_val2(data_33_reg_321),
    .data_2_val3(data_19_reg_326),
    .data_3_val4(data_20_reg_331),
    .data_4_val5(data_21_reg_336),
    .data_5_val6(data_22_reg_341),
    .data_6_val7(data_23_reg_346),
    .data_7_val8(data_24_reg_351),
    .data_8_val9(data_25_reg_356),
    .data_9_val10(data_26_reg_361),
    .data_10_val11(data_27_reg_366),
    .data_11_val12(data_28_reg_371),
    .data_12_val13(data_29_reg_376),
    .data_13_val14(data_30_reg_381),
    .data_14_val15(data_31_reg_386),
    .data_15_val16(data_32_reg_391),
    .ap_return_0(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_0),
    .ap_return_1(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_1),
    .ap_return_2(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_2),
    .ap_return_3(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_3),
    .ap_return_4(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_4),
    .ap_return_5(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_5),
    .ap_return_6(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_6),
    .ap_return_7(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_7)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_ready == 1'b1)) begin
            grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_19_reg_326 <= {{layer3_out_dout[47:32]}};
        data_20_reg_331 <= {{layer3_out_dout[63:48]}};
        data_21_reg_336 <= {{layer3_out_dout[79:64]}};
        data_22_reg_341 <= {{layer3_out_dout[95:80]}};
        data_23_reg_346 <= {{layer3_out_dout[111:96]}};
        data_24_reg_351 <= {{layer3_out_dout[127:112]}};
        data_25_reg_356 <= {{layer3_out_dout[143:128]}};
        data_26_reg_361 <= {{layer3_out_dout[159:144]}};
        data_27_reg_366 <= {{layer3_out_dout[175:160]}};
        data_28_reg_371 <= {{layer3_out_dout[191:176]}};
        data_29_reg_376 <= {{layer3_out_dout[207:192]}};
        data_30_reg_381 <= {{layer3_out_dout[223:208]}};
        data_31_reg_386 <= {{layer3_out_dout[239:224]}};
        data_32_reg_391 <= {{layer3_out_dout[255:240]}};
        data_33_reg_321 <= {{layer3_out_dout[31:16]}};
        data_reg_316 <= data_fu_117_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        res_1_reg_401 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_1;
        res_2_reg_406 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_2;
        res_3_reg_411 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_3;
        res_4_reg_416 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_4;
        res_5_reg_421 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_5;
        res_6_reg_426 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_6;
        res_7_reg_431 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_7;
        res_reg_396 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((layer4_out_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((layer3_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign data_fu_117_p1 = layer3_out_dout[15:0];

assign grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start = grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config4_s_fu_97_ap_start_reg;

assign layer4_out_din = {{{{{{{{res_7_reg_431}, {res_6_reg_426}}, {res_5_reg_421}}, {res_4_reg_416}}, {res_3_reg_411}}, {res_2_reg_406}}, {res_1_reg_401}}, {res_reg_396}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_8u_config4_s
