// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_empty_n,
        layer4_out_read,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer5_out_din,
        layer5_out_full_n,
        layer5_out_write,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer4_out_dout;
input   layer4_out_empty_n;
output   layer4_out_read;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;
output  [127:0] layer5_out_din;
input   layer5_out_full_n;
output   layer5_out_write;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;
reg layer5_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer4_out_blk_n;
reg    layer5_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [14:0] select_ln51_fu_237_p3;
reg   [14:0] select_ln51_reg_388;
reg    ap_block_state1;
wire   [14:0] select_ln51_1_fu_251_p3;
reg   [14:0] select_ln51_1_reg_393;
wire   [14:0] select_ln51_2_fu_265_p3;
reg   [14:0] select_ln51_2_reg_398;
wire   [14:0] select_ln51_3_fu_279_p3;
reg   [14:0] select_ln51_3_reg_403;
wire   [14:0] select_ln51_4_fu_293_p3;
reg   [14:0] select_ln51_4_reg_408;
wire   [14:0] select_ln51_5_fu_307_p3;
reg   [14:0] select_ln51_5_reg_413;
wire   [14:0] select_ln51_6_fu_321_p3;
reg   [14:0] select_ln51_6_reg_418;
wire   [14:0] select_ln51_7_fu_335_p3;
reg   [14:0] select_ln51_7_reg_423;
wire   [15:0] trunc_ln44_fu_83_p1;
wire   [0:0] icmp_ln51_fu_231_p2;
wire   [14:0] trunc_ln44_14_fu_87_p1;
wire   [15:0] trunc_ln44_1_fu_91_p4;
wire   [0:0] icmp_ln51_1_fu_245_p2;
wire   [14:0] trunc_ln44_8_fu_101_p4;
wire   [15:0] trunc_ln44_2_fu_111_p4;
wire   [0:0] icmp_ln51_2_fu_259_p2;
wire   [14:0] trunc_ln44_9_fu_121_p4;
wire   [15:0] trunc_ln44_3_fu_131_p4;
wire   [0:0] icmp_ln51_3_fu_273_p2;
wire   [14:0] trunc_ln44_s_fu_141_p4;
wire   [15:0] trunc_ln44_4_fu_151_p4;
wire   [0:0] icmp_ln51_4_fu_287_p2;
wire   [14:0] trunc_ln44_10_fu_161_p4;
wire   [15:0] trunc_ln44_5_fu_171_p4;
wire   [0:0] icmp_ln51_5_fu_301_p2;
wire   [14:0] trunc_ln44_11_fu_181_p4;
wire   [15:0] trunc_ln44_6_fu_191_p4;
wire   [0:0] icmp_ln51_6_fu_315_p2;
wire   [14:0] trunc_ln44_12_fu_201_p4;
wire   [15:0] trunc_ln44_7_fu_211_p4;
wire   [0:0] icmp_ln51_7_fu_329_p2;
wire   [14:0] trunc_ln3_fu_221_p4;
wire   [15:0] zext_ln51_6_fu_361_p1;
wire   [15:0] zext_ln51_5_fu_358_p1;
wire   [15:0] zext_ln51_4_fu_355_p1;
wire   [15:0] zext_ln51_3_fu_352_p1;
wire   [15:0] zext_ln51_2_fu_349_p1;
wire   [15:0] zext_ln51_1_fu_346_p1;
wire   [15:0] zext_ln51_fu_343_p1;
wire   [126:0] or_ln57_s_fu_364_p9;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln51_1_reg_393 <= select_ln51_1_fu_251_p3;
        select_ln51_2_reg_398 <= select_ln51_2_fu_265_p3;
        select_ln51_3_reg_403 <= select_ln51_3_fu_279_p3;
        select_ln51_4_reg_408 <= select_ln51_4_fu_293_p3;
        select_ln51_5_reg_413 <= select_ln51_5_fu_307_p3;
        select_ln51_6_reg_418 <= select_ln51_6_fu_321_p3;
        select_ln51_7_reg_423 <= select_ln51_7_fu_335_p3;
        select_ln51_reg_388 <= select_ln51_fu_237_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer5_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer4_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_1_fu_245_p2 = (($signed(trunc_ln44_1_fu_91_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_259_p2 = (($signed(trunc_ln44_2_fu_111_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_273_p2 = (($signed(trunc_ln44_3_fu_131_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_287_p2 = (($signed(trunc_ln44_4_fu_151_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_301_p2 = (($signed(trunc_ln44_5_fu_171_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_315_p2 = (($signed(trunc_ln44_6_fu_191_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_329_p2 = (($signed(trunc_ln44_7_fu_211_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_231_p2 = (($signed(trunc_ln44_fu_83_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign layer5_out_din = or_ln57_s_fu_364_p9;

assign or_ln57_s_fu_364_p9 = {{{{{{{{select_ln51_7_reg_423}, {zext_ln51_6_fu_361_p1}}, {zext_ln51_5_fu_358_p1}}, {zext_ln51_4_fu_355_p1}}, {zext_ln51_3_fu_352_p1}}, {zext_ln51_2_fu_349_p1}}, {zext_ln51_1_fu_346_p1}}, {zext_ln51_fu_343_p1}};

assign select_ln51_1_fu_251_p3 = ((icmp_ln51_1_fu_245_p2[0:0] == 1'b1) ? trunc_ln44_8_fu_101_p4 : 15'd0);

assign select_ln51_2_fu_265_p3 = ((icmp_ln51_2_fu_259_p2[0:0] == 1'b1) ? trunc_ln44_9_fu_121_p4 : 15'd0);

assign select_ln51_3_fu_279_p3 = ((icmp_ln51_3_fu_273_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_141_p4 : 15'd0);

assign select_ln51_4_fu_293_p3 = ((icmp_ln51_4_fu_287_p2[0:0] == 1'b1) ? trunc_ln44_10_fu_161_p4 : 15'd0);

assign select_ln51_5_fu_307_p3 = ((icmp_ln51_5_fu_301_p2[0:0] == 1'b1) ? trunc_ln44_11_fu_181_p4 : 15'd0);

assign select_ln51_6_fu_321_p3 = ((icmp_ln51_6_fu_315_p2[0:0] == 1'b1) ? trunc_ln44_12_fu_201_p4 : 15'd0);

assign select_ln51_7_fu_335_p3 = ((icmp_ln51_7_fu_329_p2[0:0] == 1'b1) ? trunc_ln3_fu_221_p4 : 15'd0);

assign select_ln51_fu_237_p3 = ((icmp_ln51_fu_231_p2[0:0] == 1'b1) ? trunc_ln44_14_fu_87_p1 : 15'd0);

assign start_out = real_start;

assign trunc_ln3_fu_221_p4 = {{layer4_out_dout[126:112]}};

assign trunc_ln44_10_fu_161_p4 = {{layer4_out_dout[78:64]}};

assign trunc_ln44_11_fu_181_p4 = {{layer4_out_dout[94:80]}};

assign trunc_ln44_12_fu_201_p4 = {{layer4_out_dout[110:96]}};

assign trunc_ln44_14_fu_87_p1 = layer4_out_dout[14:0];

assign trunc_ln44_1_fu_91_p4 = {{layer4_out_dout[31:16]}};

assign trunc_ln44_2_fu_111_p4 = {{layer4_out_dout[47:32]}};

assign trunc_ln44_3_fu_131_p4 = {{layer4_out_dout[63:48]}};

assign trunc_ln44_4_fu_151_p4 = {{layer4_out_dout[79:64]}};

assign trunc_ln44_5_fu_171_p4 = {{layer4_out_dout[95:80]}};

assign trunc_ln44_6_fu_191_p4 = {{layer4_out_dout[111:96]}};

assign trunc_ln44_7_fu_211_p4 = {{layer4_out_dout[127:112]}};

assign trunc_ln44_8_fu_101_p4 = {{layer4_out_dout[30:16]}};

assign trunc_ln44_9_fu_121_p4 = {{layer4_out_dout[46:32]}};

assign trunc_ln44_fu_83_p1 = layer4_out_dout[15:0];

assign trunc_ln44_s_fu_141_p4 = {{layer4_out_dout[62:48]}};

assign zext_ln51_1_fu_346_p1 = select_ln51_1_reg_393;

assign zext_ln51_2_fu_349_p1 = select_ln51_2_reg_398;

assign zext_ln51_3_fu_352_p1 = select_ln51_3_reg_403;

assign zext_ln51_4_fu_355_p1 = select_ln51_4_reg_408;

assign zext_ln51_5_fu_358_p1 = select_ln51_5_reg_413;

assign zext_ln51_6_fu_361_p1 = select_ln51_6_reg_418;

assign zext_ln51_fu_343_p1 = select_ln51_reg_388;

endmodule //myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config5_s
