-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_14_fu_108_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_fu_118_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_8_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_13_fu_104_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_8_fu_136_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_9_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_12_fu_100_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_9_fu_154_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_10_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_11_fu_96_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_10_fu_172_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_11_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_10_fu_92_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_11_fu_190_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_12_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_9_fu_88_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_12_fu_208_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_13_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_8_fu_84_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_13_fu_226_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_14_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln39_fu_80_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln45_14_fu_244_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln42_fu_126_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_fu_144_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_5_fu_162_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_7_fu_198_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_8_fu_216_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln42_2_fu_234_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln50_fu_252_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln42_fu_126_p1;
    ap_return_1 <= zext_ln45_fu_144_p1;
    ap_return_2 <= zext_ln45_5_fu_162_p1;
    ap_return_3 <= zext_ln45_6_fu_180_p1;
    ap_return_4 <= zext_ln45_7_fu_198_p1;
    ap_return_5 <= zext_ln45_8_fu_216_p1;
    ap_return_6 <= zext_ln42_2_fu_234_p1;
    ap_return_7 <= zext_ln50_fu_252_p1;
    icmp_ln45_10_fu_166_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_11_fu_184_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_12_fu_202_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_13_fu_220_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_14_fu_238_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_8_fu_130_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_9_fu_148_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_112_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    select_ln45_10_fu_172_p3 <= 
        trunc_ln39_11_fu_96_p1 when (icmp_ln45_10_fu_166_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_11_fu_190_p3 <= 
        trunc_ln39_10_fu_92_p1 when (icmp_ln45_11_fu_184_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_12_fu_208_p3 <= 
        trunc_ln39_9_fu_88_p1 when (icmp_ln45_12_fu_202_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_13_fu_226_p3 <= 
        trunc_ln39_8_fu_84_p1 when (icmp_ln45_13_fu_220_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_14_fu_244_p3 <= 
        trunc_ln39_fu_80_p1 when (icmp_ln45_14_fu_238_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_8_fu_136_p3 <= 
        trunc_ln39_13_fu_104_p1 when (icmp_ln45_8_fu_130_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_9_fu_154_p3 <= 
        trunc_ln39_12_fu_100_p1 when (icmp_ln45_9_fu_148_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln45_fu_118_p3 <= 
        trunc_ln39_14_fu_108_p1 when (icmp_ln45_fu_112_p2(0) = '1') else 
        ap_const_lv15_0;
    trunc_ln39_10_fu_92_p1 <= data_4_val(15 - 1 downto 0);
    trunc_ln39_11_fu_96_p1 <= data_3_val(15 - 1 downto 0);
    trunc_ln39_12_fu_100_p1 <= data_2_val(15 - 1 downto 0);
    trunc_ln39_13_fu_104_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln39_14_fu_108_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln39_8_fu_84_p1 <= data_6_val(15 - 1 downto 0);
    trunc_ln39_9_fu_88_p1 <= data_5_val(15 - 1 downto 0);
    trunc_ln39_fu_80_p1 <= data_7_val(15 - 1 downto 0);
    zext_ln42_2_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_13_fu_226_p3),16));
    zext_ln42_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_fu_118_p3),16));
    zext_ln45_5_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_9_fu_154_p3),16));
    zext_ln45_6_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_10_fu_172_p3),16));
    zext_ln45_7_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_11_fu_190_p3),16));
    zext_ln45_8_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_12_fu_208_p3),16));
    zext_ln45_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_8_fu_136_p3),16));
    zext_ln50_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_14_fu_244_p3),16));
end behav;
