// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;

wire   [9:0] exp_table_address0;
wire   [10:0] exp_table_q0;
wire   [9:0] exp_table_address1;
wire   [10:0] exp_table_q1;
wire   [9:0] exp_table_address2;
wire   [10:0] exp_table_q2;
wire   [9:0] invert_table_address0;
wire   [17:0] invert_table_q0;
reg   [15:0] data_2_val_read_reg_331;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] a_fu_124_p3;
reg   [15:0] a_reg_336;
wire   [14:0] trunc_ln66_1_fu_132_p1;
reg   [14:0] trunc_ln66_1_reg_342;
reg   [14:0] trunc_ln66_1_reg_342_pp0_iter1_reg;
wire   [14:0] trunc_ln248_fu_136_p1;
reg   [14:0] trunc_ln248_reg_348;
reg   [14:0] trunc_ln248_reg_348_pp0_iter1_reg;
wire   [14:0] trunc_ln248_1_fu_140_p1;
reg   [14:0] trunc_ln248_1_reg_353;
reg   [14:0] trunc_ln248_1_reg_353_pp0_iter1_reg;
wire   [14:0] select_ln66_fu_157_p3;
reg   [14:0] select_ln66_reg_358;
reg   [9:0] tmp_reg_365;
reg   [9:0] tmp_2_reg_370;
reg   [9:0] tmp_4_reg_375;
reg   [10:0] a_1_reg_395;
reg   [10:0] a_1_reg_395_pp0_iter5_reg;
reg   [10:0] a_1_reg_395_pp0_iter6_reg;
reg   [10:0] a_1_reg_395_pp0_iter7_reg;
reg   [10:0] b_reg_401;
reg   [10:0] b_reg_401_pp0_iter5_reg;
reg   [10:0] b_reg_401_pp0_iter6_reg;
reg   [10:0] b_reg_401_pp0_iter7_reg;
reg   [10:0] b_1_reg_407;
reg   [10:0] b_1_reg_407_pp0_iter5_reg;
reg   [10:0] b_1_reg_407_pp0_iter6_reg;
reg   [10:0] b_1_reg_407_pp0_iter7_reg;
reg   [3:0] tmp_1_reg_413;
reg   [17:0] inv_exp_sum_reg_423;
wire  signed [25:0] sext_ln270_fu_253_p1;
wire   [63:0] zext_ln258_fu_206_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln258_1_fu_210_p1;
wire   [63:0] zext_ln258_2_fu_214_p1;
wire   [63:0] zext_ln267_fu_249_p1;
reg    exp_table_ce2_local;
reg    exp_table_ce1_local;
reg    exp_table_ce0_local;
reg    invert_table_ce0_local;
wire   [0:0] icmp_ln66_fu_112_p2;
wire   [0:0] xor_ln66_fu_118_p2;
wire   [0:0] icmp_ln66_1_fu_144_p2;
wire   [0:0] xor_ln66_1_fu_148_p2;
wire   [14:0] trunc_ln66_fu_154_p1;
wire   [14:0] x_fu_164_p2;
wire   [14:0] x_1_fu_168_p2;
wire   [14:0] x_2_fu_172_p2;
wire   [11:0] zext_ln141_fu_218_p1;
wire   [11:0] zext_ln51_fu_224_p1;
wire   [11:0] add_ln51_1_fu_227_p2;
wire   [11:0] zext_ln141_1_fu_221_p1;
wire   [11:0] add_ln51_fu_233_p2;
wire  signed [17:0] grp_fu_259_p0;
wire   [10:0] grp_fu_259_p1;
wire  signed [17:0] grp_fu_268_p0;
wire   [10:0] grp_fu_268_p1;
wire  signed [17:0] grp_fu_277_p0;
wire   [10:0] grp_fu_277_p1;
wire   [25:0] grp_fu_259_p2;
wire   [25:0] grp_fu_268_p2;
wire   [25:0] grp_fu_277_p2;
reg    grp_fu_259_ce;
reg    grp_fu_268_ce;
reg    grp_fu_277_ce;
reg    ap_ce_reg;
reg   [15:0] data_0_val_int_reg;
reg   [15:0] data_1_val_int_reg;
reg   [15:0] data_2_val_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
wire   [25:0] grp_fu_259_p10;
wire   [25:0] grp_fu_268_p10;
wire   [25:0] grp_fu_277_p10;

myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0_local),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1_local),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2_local),
    .q2(exp_table_q2)
);

myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0_local),
    .q0(invert_table_q0)
);

myproject_mul_18s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_2_0_U153(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_259_p0),
    .din1(grp_fu_259_p1),
    .ce(grp_fu_259_ce),
    .dout(grp_fu_259_p2)
);

myproject_mul_18s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_2_0_U154(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_268_p0),
    .din1(grp_fu_268_p1),
    .ce(grp_fu_268_ce),
    .dout(grp_fu_268_p2)
);

myproject_mul_18s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_2_0_U155(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_277_p0),
    .din1(grp_fu_277_p1),
    .ce(grp_fu_277_ce),
    .dout(grp_fu_277_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        a_1_reg_395 <= exp_table_q2;
        a_1_reg_395_pp0_iter5_reg <= a_1_reg_395;
        a_1_reg_395_pp0_iter6_reg <= a_1_reg_395_pp0_iter5_reg;
        a_1_reg_395_pp0_iter7_reg <= a_1_reg_395_pp0_iter6_reg;
        a_reg_336 <= a_fu_124_p3;
        b_1_reg_407 <= exp_table_q0;
        b_1_reg_407_pp0_iter5_reg <= b_1_reg_407;
        b_1_reg_407_pp0_iter6_reg <= b_1_reg_407_pp0_iter5_reg;
        b_1_reg_407_pp0_iter7_reg <= b_1_reg_407_pp0_iter6_reg;
        b_reg_401 <= exp_table_q1;
        b_reg_401_pp0_iter5_reg <= b_reg_401;
        b_reg_401_pp0_iter6_reg <= b_reg_401_pp0_iter5_reg;
        b_reg_401_pp0_iter7_reg <= b_reg_401_pp0_iter6_reg;
        data_2_val_read_reg_331 <= data_2_val_int_reg;
        inv_exp_sum_reg_423 <= invert_table_q0;
        select_ln66_reg_358 <= select_ln66_fu_157_p3;
        tmp_1_reg_413 <= {{add_ln51_fu_233_p2[11:8]}};
        tmp_2_reg_370 <= {{x_1_fu_168_p2[14:5]}};
        tmp_4_reg_375 <= {{x_2_fu_172_p2[14:5]}};
        tmp_reg_365 <= {{x_fu_164_p2[14:5]}};
        trunc_ln248_1_reg_353 <= trunc_ln248_1_fu_140_p1;
        trunc_ln248_1_reg_353_pp0_iter1_reg <= trunc_ln248_1_reg_353;
        trunc_ln248_reg_348 <= trunc_ln248_fu_136_p1;
        trunc_ln248_reg_348_pp0_iter1_reg <= trunc_ln248_reg_348;
        trunc_ln66_1_reg_342 <= trunc_ln66_1_fu_132_p1;
        trunc_ln66_1_reg_342_pp0_iter1_reg <= trunc_ln66_1_reg_342;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= {{grp_fu_259_p2[25:10]}};
        ap_return_1_int_reg <= {{grp_fu_268_p2[25:10]}};
        ap_return_2_int_reg <= {{grp_fu_277_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_val_int_reg <= data_0_val;
        data_1_val_int_reg <= data_1_val;
        data_2_val_int_reg <= data_2_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = {{grp_fu_259_p2[25:10]}};
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = {{grp_fu_268_p2[25:10]}};
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = {{grp_fu_277_p2[25:10]}};
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_table_ce0_local = 1'b1;
    end else begin
        exp_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_table_ce1_local = 1'b1;
    end else begin
        exp_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_table_ce2_local = 1'b1;
    end else begin
        exp_table_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_259_ce = 1'b1;
    end else begin
        grp_fu_259_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_268_ce = 1'b1;
    end else begin
        grp_fu_268_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_277_ce = 1'b1;
    end else begin
        grp_fu_277_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        invert_table_ce0_local = 1'b1;
    end else begin
        invert_table_ce0_local = 1'b0;
    end
end

assign a_fu_124_p3 = ((xor_ln66_fu_118_p2[0:0] == 1'b1) ? data_0_val_int_reg : data_1_val_int_reg);

assign add_ln51_1_fu_227_p2 = (zext_ln141_fu_218_p1 + zext_ln51_fu_224_p1);

assign add_ln51_fu_233_p2 = (add_ln51_1_fu_227_p2 + zext_ln141_1_fu_221_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign exp_table_address0 = zext_ln258_2_fu_214_p1;

assign exp_table_address1 = zext_ln258_1_fu_210_p1;

assign exp_table_address2 = zext_ln258_fu_206_p1;

assign grp_fu_259_p0 = sext_ln270_fu_253_p1;

assign grp_fu_259_p1 = grp_fu_259_p10;

assign grp_fu_259_p10 = a_1_reg_395_pp0_iter7_reg;

assign grp_fu_268_p0 = sext_ln270_fu_253_p1;

assign grp_fu_268_p1 = grp_fu_268_p10;

assign grp_fu_268_p10 = b_reg_401_pp0_iter7_reg;

assign grp_fu_277_p0 = sext_ln270_fu_253_p1;

assign grp_fu_277_p1 = grp_fu_277_p10;

assign grp_fu_277_p10 = b_1_reg_407_pp0_iter7_reg;

assign icmp_ln66_1_fu_144_p2 = (($signed(a_reg_336) < $signed(data_2_val_read_reg_331)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_112_p2 = (($signed(data_0_val_int_reg) < $signed(data_1_val_int_reg)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln267_fu_249_p1;

assign select_ln66_fu_157_p3 = ((xor_ln66_1_fu_148_p2[0:0] == 1'b1) ? trunc_ln66_fu_154_p1 : trunc_ln66_1_reg_342);

assign sext_ln270_fu_253_p1 = $signed(inv_exp_sum_reg_423);

assign trunc_ln248_1_fu_140_p1 = data_1_val_int_reg[14:0];

assign trunc_ln248_fu_136_p1 = data_0_val_int_reg[14:0];

assign trunc_ln66_1_fu_132_p1 = data_2_val_int_reg[14:0];

assign trunc_ln66_fu_154_p1 = a_reg_336[14:0];

assign x_1_fu_168_p2 = (select_ln66_reg_358 - trunc_ln248_1_reg_353_pp0_iter1_reg);

assign x_2_fu_172_p2 = (select_ln66_reg_358 - trunc_ln66_1_reg_342_pp0_iter1_reg);

assign x_fu_164_p2 = (select_ln66_reg_358 - trunc_ln248_reg_348_pp0_iter1_reg);

assign xor_ln66_1_fu_148_p2 = (icmp_ln66_1_fu_144_p2 ^ 1'd1);

assign xor_ln66_fu_118_p2 = (icmp_ln66_fu_112_p2 ^ 1'd1);

assign zext_ln141_1_fu_221_p1 = b_reg_401;

assign zext_ln141_fu_218_p1 = a_1_reg_395;

assign zext_ln258_1_fu_210_p1 = tmp_2_reg_370;

assign zext_ln258_2_fu_214_p1 = tmp_4_reg_375;

assign zext_ln258_fu_206_p1 = tmp_reg_365;

assign zext_ln267_fu_249_p1 = tmp_1_reg_413;

assign zext_ln51_fu_224_p1 = b_1_reg_407;

endmodule //myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s
