// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;

reg  signed [15:0] data_6_val_read_reg_14876;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_5_val_read_reg_14882;
reg  signed [15:0] data_4_val_read_reg_14892;
reg  signed [15:0] data_3_val_read_reg_14900;
reg  signed [15:0] data_2_val_read_reg_14907;
reg  signed [15:0] data_2_val_read_reg_14907_pp0_iter1_reg;
reg  signed [15:0] data_1_val_read_reg_14914;
reg  signed [15:0] data_0_val_read_reg_14922;
reg   [10:0] trunc_ln42_38_reg_14931;
wire   [24:0] sub_ln73_2_fu_13549_p2;
reg   [24:0] sub_ln73_2_reg_14936;
wire  signed [22:0] sext_ln70_20_fu_13560_p1;
wire  signed [25:0] sext_ln70_21_fu_13565_p1;
reg   [12:0] trunc_ln42_81_reg_14961;
reg   [12:0] trunc_ln42_81_reg_14961_pp0_iter1_reg;
reg   [12:0] trunc_ln42_81_reg_14961_pp0_iter2_reg;
wire  signed [25:0] sext_ln70_9_fu_13611_p1;
reg   [13:0] trunc_ln42_25_reg_14985;
reg   [13:0] trunc_ln42_25_reg_14985_pp0_iter2_reg;
wire  signed [25:0] sext_ln70_11_fu_13661_p1;
reg   [14:0] trunc_ln42_31_reg_15005;
reg   [14:0] trunc_ln42_31_reg_15005_pp0_iter2_reg;
wire  signed [25:0] sext_ln42_13_fu_13708_p1;
wire  signed [24:0] sext_ln70_14_fu_13727_p1;
wire  signed [25:0] sext_ln42_15_fu_13732_p1;
wire  signed [24:0] sext_ln70_16_fu_13744_p1;
wire  signed [25:0] sext_ln73_1_fu_13749_p1;
reg   [14:0] trunc_ln42_57_reg_15063;
reg   [14:0] trunc_ln42_57_reg_15063_pp0_iter2_reg;
wire  signed [25:0] sext_ln42_23_fu_13782_p1;
reg   [14:0] trunc_ln42_62_reg_15082;
reg   [12:0] trunc_ln42_64_reg_15087;
reg   [12:0] trunc_ln42_64_reg_15087_pp0_iter2_reg;
wire  signed [25:0] sext_ln42_27_fu_13874_p1;
reg   [12:0] trunc_ln42_70_reg_15107;
reg   [15:0] trunc_ln42_77_reg_15112;
reg   [15:0] trunc_ln42_78_reg_15117;
reg   [15:0] trunc_ln42_79_reg_15122;
reg   [15:0] trunc_ln42_80_reg_15127;
reg   [12:0] trunc_ln42_82_reg_15132;
reg   [15:0] trunc_ln42_83_reg_15137;
reg   [15:0] trunc_ln42_84_reg_15142;
wire   [11:0] add_ln58_35_fu_13963_p2;
reg   [11:0] add_ln58_35_reg_15147;
reg   [15:0] trunc_ln_reg_15152;
reg   [15:0] trunc_ln42_s_reg_15157;
reg   [15:0] trunc_ln42_23_reg_15162;
reg   [15:0] trunc_ln42_24_reg_15167;
reg   [12:0] trunc_ln42_26_reg_15172;
reg   [15:0] trunc_ln42_27_reg_15177;
reg   [14:0] trunc_ln42_28_reg_15182;
reg   [15:0] trunc_ln42_29_reg_15187;
reg   [15:0] trunc_ln42_30_reg_15192;
reg   [15:0] trunc_ln42_32_reg_15197;
reg   [15:0] trunc_ln42_33_reg_15202;
reg   [15:0] trunc_ln42_34_reg_15207;
reg   [12:0] trunc_ln42_35_reg_15212;
reg   [15:0] trunc_ln42_36_reg_15217;
reg   [15:0] trunc_ln42_37_reg_15222;
reg   [15:0] trunc_ln42_39_reg_15227;
reg   [14:0] trunc_ln42_40_reg_15232;
reg   [15:0] trunc_ln42_41_reg_15237;
reg   [15:0] trunc_ln42_42_reg_15242;
reg   [15:0] trunc_ln42_43_reg_15247;
reg   [15:0] trunc_ln42_44_reg_15252;
reg   [15:0] trunc_ln42_45_reg_15257;
reg   [15:0] trunc_ln42_46_reg_15262;
reg   [15:0] trunc_ln42_47_reg_15267;
reg   [14:0] trunc_ln42_48_reg_15272;
reg   [14:0] trunc_ln42_49_reg_15277;
reg   [13:0] trunc_ln42_50_reg_15282;
reg   [15:0] trunc_ln42_51_reg_15287;
reg   [15:0] trunc_ln42_52_reg_15292;
reg   [15:0] trunc_ln42_53_reg_15297;
reg   [14:0] trunc_ln42_54_reg_15302;
reg   [12:0] trunc_ln42_55_reg_15307;
reg   [15:0] trunc_ln42_56_reg_15312;
reg   [14:0] trunc_ln42_58_reg_15317;
reg   [15:0] trunc_ln42_59_reg_15322;
reg   [15:0] trunc_ln42_60_reg_15327;
reg   [14:0] trunc_ln42_61_reg_15332;
reg   [15:0] trunc_ln42_63_reg_15337;
reg   [15:0] trunc_ln42_65_reg_15342;
reg   [15:0] trunc_ln42_66_reg_15347;
reg   [15:0] trunc_ln42_67_reg_15352;
reg   [15:0] trunc_ln42_68_reg_15357;
reg   [15:0] trunc_ln42_69_reg_15362;
reg   [15:0] trunc_ln42_71_reg_15367;
reg   [15:0] trunc_ln42_72_reg_15372;
reg   [14:0] trunc_ln42_73_reg_15377;
reg   [15:0] trunc_ln42_74_reg_15382;
reg   [15:0] trunc_ln42_75_reg_15387;
reg   [15:0] trunc_ln42_76_reg_15392;
wire   [15:0] add_ln58_27_fu_14485_p2;
reg   [15:0] add_ln58_27_reg_15397;
wire   [15:0] add_ln58_34_fu_14490_p2;
reg   [15:0] add_ln58_34_reg_15402;
wire   [15:0] add_ln58_36_fu_14499_p2;
reg   [15:0] add_ln58_36_reg_15407;
wire   [15:0] add_ln58_43_fu_14504_p2;
reg   [15:0] add_ln58_43_reg_15412;
wire   [15:0] add_ln58_51_fu_14509_p2;
reg   [15:0] add_ln58_51_reg_15417;
wire   [13:0] add_ln58_67_fu_14514_p2;
reg   [13:0] add_ln58_67_reg_15422;
wire   [15:0] add_ln58_75_fu_14520_p2;
reg   [15:0] add_ln58_75_reg_15427;
wire   [15:0] add_ln58_83_fu_14525_p2;
reg   [15:0] add_ln58_83_reg_15432;
wire   [15:0] add_ln58_fu_14581_p2;
reg   [15:0] add_ln58_reg_15437;
wire   [15:0] add_ln58_24_fu_14585_p2;
reg   [15:0] add_ln58_24_reg_15442;
wire   [15:0] add_ln58_26_fu_14589_p2;
reg   [15:0] add_ln58_26_reg_15447;
wire   [15:0] add_ln58_28_fu_14594_p2;
reg   [15:0] add_ln58_28_reg_15452;
wire   [15:0] add_ln58_31_fu_14598_p2;
reg   [15:0] add_ln58_31_reg_15457;
wire   [15:0] add_ln58_32_fu_14602_p2;
reg   [15:0] add_ln58_32_reg_15462;
wire   [15:0] add_ln58_37_fu_14607_p2;
reg   [15:0] add_ln58_37_reg_15467;
reg   [15:0] add_ln58_37_reg_15467_pp0_iter4_reg;
wire   [15:0] add_ln58_39_fu_14611_p2;
reg   [15:0] add_ln58_39_reg_15472;
wire   [15:0] add_ln58_40_fu_14616_p2;
reg   [15:0] add_ln58_40_reg_15477;
wire   [15:0] add_ln58_42_fu_14620_p2;
reg   [15:0] add_ln58_42_reg_15482;
wire   [15:0] add_ln58_44_fu_14625_p2;
reg   [15:0] add_ln58_44_reg_15487;
wire   [15:0] add_ln58_47_fu_14629_p2;
reg   [15:0] add_ln58_47_reg_15492;
wire   [15:0] add_ln58_48_fu_14633_p2;
reg   [15:0] add_ln58_48_reg_15497;
wire   [15:0] add_ln58_50_fu_14639_p2;
reg   [15:0] add_ln58_50_reg_15502;
wire   [15:0] add_ln58_52_fu_14644_p2;
reg   [15:0] add_ln58_52_reg_15507;
wire   [15:0] add_ln58_55_fu_14648_p2;
reg   [15:0] add_ln58_55_reg_15512;
wire   [15:0] add_ln58_56_fu_14653_p2;
reg   [15:0] add_ln58_56_reg_15517;
wire   [15:0] add_ln58_58_fu_14658_p2;
reg   [15:0] add_ln58_58_reg_15522;
wire   [15:0] add_ln58_60_fu_14673_p2;
reg   [15:0] add_ln58_60_reg_15527;
wire   [15:0] add_ln58_63_fu_14679_p2;
reg   [15:0] add_ln58_63_reg_15532;
wire   [15:0] add_ln58_64_fu_14684_p2;
reg   [15:0] add_ln58_64_reg_15537;
wire   [15:0] add_ln58_66_fu_14689_p2;
reg   [15:0] add_ln58_66_reg_15542;
wire   [15:0] add_ln58_68_fu_14697_p2;
reg   [15:0] add_ln58_68_reg_15547;
wire   [15:0] add_ln58_71_fu_14702_p2;
reg   [15:0] add_ln58_71_reg_15552;
wire   [15:0] add_ln58_72_fu_14707_p2;
reg   [15:0] add_ln58_72_reg_15557;
wire   [15:0] add_ln58_74_fu_14711_p2;
reg   [15:0] add_ln58_74_reg_15562;
wire   [15:0] add_ln58_76_fu_14715_p2;
reg   [15:0] add_ln58_76_reg_15567;
wire   [15:0] add_ln58_79_fu_14719_p2;
reg   [15:0] add_ln58_79_reg_15572;
wire   [15:0] add_ln58_80_fu_14724_p2;
reg   [15:0] add_ln58_80_reg_15577;
wire   [15:0] add_ln58_82_fu_14728_p2;
reg   [15:0] add_ln58_82_reg_15582;
wire   [15:0] add_ln58_84_fu_14732_p2;
reg   [15:0] add_ln58_84_reg_15587;
wire   [15:0] add_ln58_25_fu_14736_p2;
reg   [15:0] add_ln58_25_reg_15592;
wire   [15:0] add_ln58_29_fu_14740_p2;
reg   [15:0] add_ln58_29_reg_15597;
wire   [15:0] add_ln58_33_fu_14744_p2;
reg   [15:0] add_ln58_33_reg_15602;
wire   [15:0] add_ln58_41_fu_14748_p2;
reg   [15:0] add_ln58_41_reg_15607;
wire   [15:0] add_ln58_45_fu_14752_p2;
reg   [15:0] add_ln58_45_reg_15612;
wire   [15:0] add_ln58_49_fu_14756_p2;
reg   [15:0] add_ln58_49_reg_15617;
wire   [15:0] add_ln58_53_fu_14760_p2;
reg   [15:0] add_ln58_53_reg_15622;
wire   [15:0] add_ln58_57_fu_14764_p2;
reg   [15:0] add_ln58_57_reg_15627;
wire   [15:0] add_ln58_61_fu_14768_p2;
reg   [15:0] add_ln58_61_reg_15632;
wire   [15:0] add_ln58_65_fu_14772_p2;
reg   [15:0] add_ln58_65_reg_15637;
wire   [15:0] add_ln58_69_fu_14776_p2;
reg   [15:0] add_ln58_69_reg_15642;
wire   [15:0] add_ln58_73_fu_14780_p2;
reg   [15:0] add_ln58_73_reg_15647;
wire   [15:0] add_ln58_77_fu_14784_p2;
reg   [15:0] add_ln58_77_reg_15652;
wire   [15:0] add_ln58_81_fu_14788_p2;
reg   [15:0] add_ln58_81_reg_15657;
wire   [15:0] add_ln58_85_fu_14792_p2;
reg   [15:0] add_ln58_85_reg_15662;
wire  signed [15:0] grp_fu_270_p0;
wire  signed [10:0] grp_fu_270_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] grp_fu_271_p0;
wire  signed [10:0] grp_fu_271_p1;
wire  signed [15:0] grp_fu_273_p0;
wire   [9:0] grp_fu_273_p1;
wire  signed [15:0] grp_fu_274_p0;
wire   [10:0] grp_fu_274_p1;
wire  signed [15:0] grp_fu_275_p0;
wire   [9:0] grp_fu_275_p1;
wire  signed [15:0] grp_fu_276_p0;
wire   [6:0] grp_fu_276_p1;
wire  signed [15:0] grp_fu_277_p0;
wire   [10:0] grp_fu_277_p1;
wire  signed [15:0] grp_fu_278_p0;
wire   [9:0] grp_fu_278_p1;
wire  signed [15:0] grp_fu_279_p0;
wire   [8:0] grp_fu_279_p1;
wire  signed [15:0] grp_fu_280_p0;
wire   [11:0] grp_fu_280_p1;
wire  signed [15:0] grp_fu_281_p0;
wire   [9:0] grp_fu_281_p1;
wire  signed [15:0] grp_fu_282_p0;
wire   [8:0] grp_fu_282_p1;
wire  signed [15:0] grp_fu_283_p0;
wire   [10:0] grp_fu_283_p1;
wire  signed [15:0] grp_fu_284_p0;
wire   [11:0] grp_fu_284_p1;
wire  signed [15:0] grp_fu_285_p0;
wire  signed [11:0] grp_fu_285_p1;
wire  signed [8:0] grp_fu_286_p1;
wire  signed [15:0] grp_fu_287_p0;
wire   [11:0] grp_fu_287_p1;
wire  signed [15:0] grp_fu_288_p0;
wire  signed [9:0] grp_fu_288_p1;
wire  signed [8:0] grp_fu_289_p1;
wire  signed [6:0] grp_fu_290_p1;
wire  signed [15:0] grp_fu_291_p0;
wire  signed [9:0] grp_fu_291_p1;
wire  signed [15:0] grp_fu_292_p0;
wire  signed [10:0] grp_fu_292_p1;
wire  signed [8:0] grp_fu_293_p1;
wire  signed [15:0] grp_fu_294_p0;
wire  signed [9:0] grp_fu_294_p1;
wire  signed [15:0] grp_fu_295_p0;
wire  signed [10:0] grp_fu_295_p1;
wire  signed [15:0] grp_fu_296_p0;
wire  signed [11:0] grp_fu_296_p1;
wire  signed [15:0] grp_fu_297_p0;
wire   [10:0] grp_fu_297_p1;
wire  signed [15:0] grp_fu_298_p0;
wire   [11:0] grp_fu_298_p1;
wire  signed [15:0] grp_fu_299_p0;
wire   [10:0] grp_fu_299_p1;
wire  signed [15:0] grp_fu_300_p0;
wire  signed [8:0] grp_fu_300_p1;
wire  signed [15:0] grp_fu_302_p0;
wire  signed [9:0] grp_fu_302_p1;
wire  signed [15:0] grp_fu_303_p0;
wire  signed [9:0] grp_fu_303_p1;
wire  signed [6:0] grp_fu_305_p1;
wire  signed [15:0] grp_fu_306_p0;
wire  signed [10:0] grp_fu_306_p1;
wire  signed [15:0] grp_fu_307_p0;
wire   [10:0] grp_fu_307_p1;
wire  signed [15:0] grp_fu_308_p0;
wire   [10:0] grp_fu_308_p1;
wire   [6:0] grp_fu_309_p1;
wire  signed [15:0] grp_fu_310_p0;
wire   [9:0] grp_fu_310_p1;
wire  signed [8:0] grp_fu_311_p1;
wire  signed [15:0] grp_fu_312_p0;
wire   [11:0] grp_fu_312_p1;
wire  signed [15:0] grp_fu_313_p0;
wire  signed [10:0] grp_fu_313_p1;
wire  signed [15:0] grp_fu_315_p0;
wire   [10:0] grp_fu_315_p1;
wire  signed [15:0] grp_fu_316_p0;
wire  signed [9:0] grp_fu_316_p1;
wire  signed [15:0] grp_fu_317_p0;
wire   [9:0] grp_fu_317_p1;
wire  signed [15:0] grp_fu_318_p0;
wire   [10:0] grp_fu_318_p1;
wire  signed [15:0] grp_fu_319_p0;
wire   [9:0] grp_fu_319_p1;
wire   [7:0] grp_fu_320_p1;
wire  signed [15:0] grp_fu_321_p0;
wire  signed [9:0] grp_fu_321_p1;
wire  signed [15:0] grp_fu_322_p0;
wire  signed [8:0] grp_fu_322_p1;
wire  signed [15:0] grp_fu_323_p0;
wire  signed [9:0] grp_fu_323_p1;
wire   [6:0] grp_fu_324_p1;
wire  signed [15:0] grp_fu_327_p0;
wire   [10:0] grp_fu_327_p1;
wire  signed [15:0] grp_fu_328_p0;
wire  signed [10:0] grp_fu_328_p1;
wire  signed [15:0] grp_fu_329_p0;
wire  signed [9:0] grp_fu_329_p1;
wire  signed [15:0] grp_fu_330_p0;
wire  signed [11:0] grp_fu_330_p1;
wire  signed [15:0] grp_fu_332_p0;
wire  signed [11:0] grp_fu_332_p1;
wire  signed [15:0] trunc_ln42_38_fu_13527_p1;
wire  signed [15:0] tmp_8_fu_13537_p1;
wire   [22:0] tmp_8_fu_13537_p3;
wire  signed [24:0] sext_ln73_7_fu_13545_p1;
wire  signed [15:0] sext_ln70_19_fu_13555_p0;
wire  signed [15:0] sext_ln70_20_fu_13560_p0;
wire  signed [15:0] sext_ln70_21_fu_13565_p0;
wire  signed [15:0] tmp_14_fu_13575_p1;
wire   [20:0] tmp_14_fu_13575_p3;
wire  signed [22:0] sext_ln73_13_fu_13583_p1;
wire   [22:0] add_ln73_1_fu_13587_p2;
wire   [21:0] tmp_fu_13619_p3;
wire   [19:0] tmp_4_fu_13630_p3;
wire  signed [23:0] sext_ln73_2_fu_13626_p1;
wire  signed [23:0] sext_ln73_3_fu_13637_p1;
wire   [23:0] add_ln73_fu_13641_p2;
wire   [23:0] tmp_5_fu_13670_p3;
wire   [19:0] tmp_6_fu_13681_p3;
wire  signed [24:0] sext_ln73_4_fu_13677_p1;
wire  signed [24:0] sext_ln73_5_fu_13688_p1;
wire   [24:0] sub_ln73_fu_13692_p2;
wire   [19:0] tmp_9_fu_13756_p3;
wire  signed [24:0] sext_ln73_8_fu_13763_p1;
wire   [24:0] sub_ln73_3_fu_13767_p2;
wire   [23:0] tmp_10_fu_13794_p3;
wire   [18:0] tmp_11_fu_13805_p3;
wire  signed [24:0] sext_ln73_10_fu_13812_p1;
wire  signed [24:0] sext_ln73_9_fu_13801_p1;
wire   [24:0] sub_ln73_4_fu_13816_p2;
wire   [21:0] tmp_12_fu_13832_p3;
wire   [17:0] tmp_13_fu_13843_p3;
wire  signed [22:0] sext_ln73_12_fu_13850_p1;
wire  signed [22:0] sext_ln73_11_fu_13839_p1;
wire   [22:0] sub_ln73_5_fu_13854_p2;
wire   [22:0] grp_fu_290_p2;
wire   [25:0] grp_fu_270_p2;
wire   [25:0] grp_fu_332_p2;
wire   [25:0] grp_fu_321_p2;
wire   [25:0] grp_fu_280_p2;
wire   [22:0] grp_fu_276_p2;
wire   [25:0] grp_fu_306_p2;
wire   [25:0] grp_fu_271_p2;
wire  signed [11:0] sext_ln73_fu_13720_p1;
wire   [25:0] grp_fu_283_p2;
wire   [25:0] grp_fu_307_p2;
wire   [25:0] grp_fu_317_p2;
wire   [25:0] grp_fu_292_p2;
wire   [22:0] grp_fu_309_p2;
wire   [25:0] grp_fu_327_p2;
wire   [24:0] grp_fu_289_p2;
wire   [25:0] grp_fu_308_p2;
wire   [25:0] grp_fu_277_p2;
wire   [25:0] grp_fu_296_p2;
wire   [25:0] grp_fu_319_p2;
wire   [25:0] grp_fu_328_p2;
wire   [22:0] grp_fu_305_p2;
wire   [25:0] grp_fu_312_p2;
wire   [24:0] tmp_7_fu_14109_p3;
wire  signed [25:0] sext_ln73_6_fu_14116_p1;
wire   [25:0] sub_ln73_1_fu_14120_p2;
wire   [25:0] grp_fu_273_p2;
wire   [24:0] grp_fu_293_p2;
wire   [25:0] grp_fu_316_p2;
wire   [25:0] grp_fu_275_p2;
wire   [25:0] grp_fu_278_p2;
wire   [25:0] grp_fu_313_p2;
wire   [25:0] grp_fu_281_p2;
wire   [25:0] grp_fu_298_p2;
wire   [25:0] grp_fu_294_p2;
wire   [24:0] grp_fu_279_p2;
wire   [24:0] grp_fu_322_p2;
wire   [23:0] grp_fu_320_p2;
wire   [25:0] grp_fu_274_p2;
wire   [25:0] grp_fu_297_p2;
wire   [25:0] grp_fu_315_p2;
wire   [24:0] grp_fu_282_p2;
wire   [22:0] grp_fu_324_p2;
wire   [25:0] grp_fu_330_p2;
wire   [24:0] grp_fu_300_p2;
wire   [25:0] grp_fu_299_p2;
wire   [25:0] grp_fu_284_p2;
wire   [24:0] grp_fu_286_p2;
wire   [25:0] grp_fu_285_p2;
wire   [25:0] grp_fu_323_p2;
wire   [25:0] grp_fu_295_p2;
wire   [25:0] grp_fu_302_p2;
wire   [25:0] grp_fu_287_p2;
wire   [25:0] grp_fu_329_p2;
wire   [25:0] grp_fu_288_p2;
wire   [25:0] grp_fu_318_p2;
wire   [24:0] grp_fu_311_p2;
wire   [25:0] grp_fu_303_p2;
wire   [25:0] grp_fu_291_p2;
wire   [25:0] grp_fu_310_p2;
wire  signed [15:0] sext_ln42_25_fu_14356_p1;
wire  signed [15:0] sext_ln42_28_fu_14419_p1;
wire  signed [15:0] sext_ln58_fu_14496_p1;
wire  signed [13:0] sext_ln42_30_fu_14482_p1;
wire  signed [15:0] sext_ln42_24_fu_14569_p1;
wire  signed [15:0] sext_ln42_19_fu_14557_p1;
wire  signed [15:0] sext_ln42_11_fu_14539_p1;
wire  signed [15:0] sext_ln42_20_fu_14560_p1;
wire  signed [15:0] sext_ln42_14_fu_14545_p1;
wire  signed [15:0] sext_ln42_16_fu_14548_p1;
wire  signed [15:0] sext_ln42_26_fu_14572_p1;
wire  signed [15:0] sext_ln42_fu_14530_p1;
wire  signed [15:0] sext_ln42_17_fu_14551_p1;
wire  signed [15:0] sext_ln42_21_fu_14563_p1;
wire  signed [13:0] sext_ln73_14_fu_14578_p1;
wire   [13:0] add_ln58_59_fu_14663_p2;
wire  signed [15:0] sext_ln58_1_fu_14669_p1;
wire  signed [15:0] sext_ln42_29_fu_14575_p1;
wire  signed [15:0] sext_ln42_9_fu_14533_p1;
wire  signed [15:0] sext_ln42_18_fu_14554_p1;
wire  signed [15:0] sext_ln42_22_fu_14566_p1;
wire  signed [15:0] sext_ln58_2_fu_14694_p1;
wire  signed [15:0] sext_ln42_12_fu_14542_p1;
wire  signed [15:0] sext_ln42_10_fu_14536_p1;
wire   [15:0] add_ln58_30_fu_14796_p2;
wire   [15:0] add_ln58_38_fu_14800_p2;
wire   [15:0] add_ln58_46_fu_14804_p2;
wire   [15:0] add_ln58_54_fu_14808_p2;
wire   [15:0] add_ln58_62_fu_14812_p2;
wire   [15:0] add_ln58_70_fu_14816_p2;
wire   [15:0] add_ln58_78_fu_14820_p2;
wire   [15:0] add_ln58_86_fu_14824_p2;
reg    grp_fu_270_ce;
reg    grp_fu_271_ce;
reg    grp_fu_273_ce;
reg    grp_fu_274_ce;
reg    grp_fu_275_ce;
reg    grp_fu_276_ce;
reg    grp_fu_277_ce;
reg    grp_fu_278_ce;
reg    grp_fu_279_ce;
reg    grp_fu_280_ce;
reg    grp_fu_281_ce;
reg    grp_fu_282_ce;
reg    grp_fu_283_ce;
reg    grp_fu_284_ce;
reg    grp_fu_285_ce;
reg    grp_fu_286_ce;
reg    grp_fu_287_ce;
reg    grp_fu_288_ce;
reg    grp_fu_289_ce;
reg    grp_fu_290_ce;
reg    grp_fu_291_ce;
reg    grp_fu_292_ce;
reg    grp_fu_293_ce;
reg    grp_fu_294_ce;
reg    grp_fu_295_ce;
reg    grp_fu_296_ce;
reg    grp_fu_297_ce;
reg    grp_fu_298_ce;
reg    grp_fu_299_ce;
reg    grp_fu_300_ce;
reg    grp_fu_302_ce;
reg    grp_fu_303_ce;
reg    grp_fu_305_ce;
reg    grp_fu_306_ce;
reg    grp_fu_307_ce;
reg    grp_fu_308_ce;
reg    grp_fu_309_ce;
reg    grp_fu_310_ce;
reg    grp_fu_311_ce;
reg    grp_fu_312_ce;
reg    grp_fu_313_ce;
reg    grp_fu_315_ce;
reg    grp_fu_316_ce;
reg    grp_fu_317_ce;
reg    grp_fu_318_ce;
reg    grp_fu_319_ce;
reg    grp_fu_320_ce;
reg    grp_fu_321_ce;
reg    grp_fu_322_ce;
reg    grp_fu_323_ce;
reg    grp_fu_324_ce;
reg    grp_fu_327_ce;
reg    grp_fu_328_ce;
reg    grp_fu_329_ce;
reg    grp_fu_330_ce;
reg    grp_fu_332_ce;
reg    ap_ce_reg;
reg   [15:0] data_0_val_int_reg;
reg   [15:0] data_1_val_int_reg;
reg   [15:0] data_2_val_int_reg;
reg   [15:0] data_3_val_int_reg;
reg   [15:0] data_4_val_int_reg;
reg   [15:0] data_5_val_int_reg;
reg   [15:0] data_6_val_int_reg;
reg   [15:0] data_7_val_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_270_p0),
    .din1(grp_fu_270_p1),
    .ce(grp_fu_270_ce),
    .dout(grp_fu_270_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_271_p0),
    .din1(grp_fu_271_p1),
    .ce(grp_fu_271_ce),
    .dout(grp_fu_271_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_273_p0),
    .din1(grp_fu_273_p1),
    .ce(grp_fu_273_ce),
    .dout(grp_fu_273_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_274_p0),
    .din1(grp_fu_274_p1),
    .ce(grp_fu_274_ce),
    .dout(grp_fu_274_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_275_p0),
    .din1(grp_fu_275_p1),
    .ce(grp_fu_275_ce),
    .dout(grp_fu_275_p2)
);

myproject_mul_16s_7ns_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_2_0_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_276_p0),
    .din1(grp_fu_276_p1),
    .ce(grp_fu_276_ce),
    .dout(grp_fu_276_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_277_p0),
    .din1(grp_fu_277_p1),
    .ce(grp_fu_277_ce),
    .dout(grp_fu_277_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_278_p0),
    .din1(grp_fu_278_p1),
    .ce(grp_fu_278_ce),
    .dout(grp_fu_278_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_2_0_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_279_p0),
    .din1(grp_fu_279_p1),
    .ce(grp_fu_279_ce),
    .dout(grp_fu_279_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_280_p0),
    .din1(grp_fu_280_p1),
    .ce(grp_fu_280_ce),
    .dout(grp_fu_280_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_281_p0),
    .din1(grp_fu_281_p1),
    .ce(grp_fu_281_ce),
    .dout(grp_fu_281_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_2_0_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_282_p0),
    .din1(grp_fu_282_p1),
    .ce(grp_fu_282_ce),
    .dout(grp_fu_282_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_283_p0),
    .din1(grp_fu_283_p1),
    .ce(grp_fu_283_ce),
    .dout(grp_fu_283_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_284_p0),
    .din1(grp_fu_284_p1),
    .ce(grp_fu_284_ce),
    .dout(grp_fu_284_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_285_p0),
    .din1(grp_fu_285_p1),
    .ce(grp_fu_285_ce),
    .dout(grp_fu_285_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_5_val_read_reg_14882),
    .din1(grp_fu_286_p1),
    .ce(grp_fu_286_ce),
    .dout(grp_fu_286_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_287_p0),
    .din1(grp_fu_287_p1),
    .ce(grp_fu_287_ce),
    .dout(grp_fu_287_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_288_p0),
    .din1(grp_fu_288_p1),
    .ce(grp_fu_288_ce),
    .dout(grp_fu_288_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_0_val_read_reg_14922),
    .din1(grp_fu_289_p1),
    .ce(grp_fu_289_ce),
    .dout(grp_fu_289_p2)
);

myproject_mul_16s_7s_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_2_0_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln70_19_fu_13555_p0),
    .din1(grp_fu_290_p1),
    .ce(grp_fu_290_ce),
    .dout(grp_fu_290_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_291_p0),
    .din1(grp_fu_291_p1),
    .ce(grp_fu_291_ce),
    .dout(grp_fu_291_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_292_p0),
    .din1(grp_fu_292_p1),
    .ce(grp_fu_292_ce),
    .dout(grp_fu_292_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_2_val_read_reg_14907),
    .din1(grp_fu_293_p1),
    .ce(grp_fu_293_ce),
    .dout(grp_fu_293_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_294_p0),
    .din1(grp_fu_294_p1),
    .ce(grp_fu_294_ce),
    .dout(grp_fu_294_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_295_p0),
    .din1(grp_fu_295_p1),
    .ce(grp_fu_295_ce),
    .dout(grp_fu_295_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_296_p0),
    .din1(grp_fu_296_p1),
    .ce(grp_fu_296_ce),
    .dout(grp_fu_296_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_297_p0),
    .din1(grp_fu_297_p1),
    .ce(grp_fu_297_ce),
    .dout(grp_fu_297_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_298_p0),
    .din1(grp_fu_298_p1),
    .ce(grp_fu_298_ce),
    .dout(grp_fu_298_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U77(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_299_p0),
    .din1(grp_fu_299_p1),
    .ce(grp_fu_299_ce),
    .dout(grp_fu_299_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_300_p0),
    .din1(grp_fu_300_p1),
    .ce(grp_fu_300_ce),
    .dout(grp_fu_300_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_302_p0),
    .din1(grp_fu_302_p1),
    .ce(grp_fu_302_ce),
    .dout(grp_fu_302_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_303_p0),
    .din1(grp_fu_303_p1),
    .ce(grp_fu_303_ce),
    .dout(grp_fu_303_p2)
);

myproject_mul_16s_7s_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_2_0_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_1_val_read_reg_14914),
    .din1(grp_fu_305_p1),
    .ce(grp_fu_305_ce),
    .dout(grp_fu_305_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_306_p0),
    .din1(grp_fu_306_p1),
    .ce(grp_fu_306_ce),
    .dout(grp_fu_306_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U83(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_307_p0),
    .din1(grp_fu_307_p1),
    .ce(grp_fu_307_ce),
    .dout(grp_fu_307_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U84(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_308_p0),
    .din1(grp_fu_308_p1),
    .ce(grp_fu_308_ce),
    .dout(grp_fu_308_p2)
);

myproject_mul_16s_7ns_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_2_0_U85(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_0_val_read_reg_14922),
    .din1(grp_fu_309_p1),
    .ce(grp_fu_309_ce),
    .dout(grp_fu_309_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_310_p0),
    .din1(grp_fu_310_p1),
    .ce(grp_fu_310_ce),
    .dout(grp_fu_310_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_6_val_read_reg_14876),
    .din1(grp_fu_311_p1),
    .ce(grp_fu_311_ce),
    .dout(grp_fu_311_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_312_p0),
    .din1(grp_fu_312_p1),
    .ce(grp_fu_312_ce),
    .dout(grp_fu_312_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_313_p0),
    .din1(grp_fu_313_p1),
    .ce(grp_fu_313_ce),
    .dout(grp_fu_313_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_315_p0),
    .din1(grp_fu_315_p1),
    .ce(grp_fu_315_ce),
    .dout(grp_fu_315_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_316_p0),
    .din1(grp_fu_316_p1),
    .ce(grp_fu_316_ce),
    .dout(grp_fu_316_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_317_p0),
    .din1(grp_fu_317_p1),
    .ce(grp_fu_317_ce),
    .dout(grp_fu_317_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_318_p0),
    .din1(grp_fu_318_p1),
    .ce(grp_fu_318_ce),
    .dout(grp_fu_318_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_319_p0),
    .din1(grp_fu_319_p1),
    .ce(grp_fu_319_ce),
    .dout(grp_fu_319_p2)
);

myproject_mul_16s_8ns_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_0_U95(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_3_val_read_reg_14900),
    .din1(grp_fu_320_p1),
    .ce(grp_fu_320_ce),
    .dout(grp_fu_320_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_321_p0),
    .din1(grp_fu_321_p1),
    .ce(grp_fu_321_ce),
    .dout(grp_fu_321_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_322_p0),
    .din1(grp_fu_322_p1),
    .ce(grp_fu_322_ce),
    .dout(grp_fu_322_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_323_p0),
    .din1(grp_fu_323_p1),
    .ce(grp_fu_323_ce),
    .dout(grp_fu_323_p2)
);

myproject_mul_16s_7ns_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_2_0_U99(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_4_val_read_reg_14892),
    .din1(grp_fu_324_p1),
    .ce(grp_fu_324_ce),
    .dout(grp_fu_324_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_327_p0),
    .din1(grp_fu_327_p1),
    .ce(grp_fu_327_ce),
    .dout(grp_fu_327_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U101(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_328_p0),
    .din1(grp_fu_328_p1),
    .ce(grp_fu_328_ce),
    .dout(grp_fu_328_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U102(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_329_p0),
    .din1(grp_fu_329_p1),
    .ce(grp_fu_329_ce),
    .dout(grp_fu_329_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U103(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_330_p0),
    .din1(grp_fu_330_p1),
    .ce(grp_fu_330_ce),
    .dout(grp_fu_330_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U104(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_332_p0),
    .din1(grp_fu_332_p1),
    .ce(grp_fu_332_ce),
    .dout(grp_fu_332_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln58_24_reg_15442 <= add_ln58_24_fu_14585_p2;
        add_ln58_25_reg_15592 <= add_ln58_25_fu_14736_p2;
        add_ln58_26_reg_15447 <= add_ln58_26_fu_14589_p2;
        add_ln58_27_reg_15397 <= add_ln58_27_fu_14485_p2;
        add_ln58_28_reg_15452 <= add_ln58_28_fu_14594_p2;
        add_ln58_29_reg_15597 <= add_ln58_29_fu_14740_p2;
        add_ln58_31_reg_15457 <= add_ln58_31_fu_14598_p2;
        add_ln58_32_reg_15462 <= add_ln58_32_fu_14602_p2;
        add_ln58_33_reg_15602 <= add_ln58_33_fu_14744_p2;
        add_ln58_34_reg_15402 <= add_ln58_34_fu_14490_p2;
        add_ln58_35_reg_15147 <= add_ln58_35_fu_13963_p2;
        add_ln58_36_reg_15407 <= add_ln58_36_fu_14499_p2;
        add_ln58_37_reg_15467 <= add_ln58_37_fu_14607_p2;
        add_ln58_37_reg_15467_pp0_iter4_reg <= add_ln58_37_reg_15467;
        add_ln58_39_reg_15472 <= add_ln58_39_fu_14611_p2;
        add_ln58_40_reg_15477 <= add_ln58_40_fu_14616_p2;
        add_ln58_41_reg_15607 <= add_ln58_41_fu_14748_p2;
        add_ln58_42_reg_15482 <= add_ln58_42_fu_14620_p2;
        add_ln58_43_reg_15412 <= add_ln58_43_fu_14504_p2;
        add_ln58_44_reg_15487 <= add_ln58_44_fu_14625_p2;
        add_ln58_45_reg_15612 <= add_ln58_45_fu_14752_p2;
        add_ln58_47_reg_15492 <= add_ln58_47_fu_14629_p2;
        add_ln58_48_reg_15497 <= add_ln58_48_fu_14633_p2;
        add_ln58_49_reg_15617 <= add_ln58_49_fu_14756_p2;
        add_ln58_50_reg_15502 <= add_ln58_50_fu_14639_p2;
        add_ln58_51_reg_15417 <= add_ln58_51_fu_14509_p2;
        add_ln58_52_reg_15507 <= add_ln58_52_fu_14644_p2;
        add_ln58_53_reg_15622 <= add_ln58_53_fu_14760_p2;
        add_ln58_55_reg_15512 <= add_ln58_55_fu_14648_p2;
        add_ln58_56_reg_15517 <= add_ln58_56_fu_14653_p2;
        add_ln58_57_reg_15627 <= add_ln58_57_fu_14764_p2;
        add_ln58_58_reg_15522 <= add_ln58_58_fu_14658_p2;
        add_ln58_60_reg_15527 <= add_ln58_60_fu_14673_p2;
        add_ln58_61_reg_15632 <= add_ln58_61_fu_14768_p2;
        add_ln58_63_reg_15532 <= add_ln58_63_fu_14679_p2;
        add_ln58_64_reg_15537 <= add_ln58_64_fu_14684_p2;
        add_ln58_65_reg_15637 <= add_ln58_65_fu_14772_p2;
        add_ln58_66_reg_15542 <= add_ln58_66_fu_14689_p2;
        add_ln58_67_reg_15422 <= add_ln58_67_fu_14514_p2;
        add_ln58_68_reg_15547 <= add_ln58_68_fu_14697_p2;
        add_ln58_69_reg_15642 <= add_ln58_69_fu_14776_p2;
        add_ln58_71_reg_15552 <= add_ln58_71_fu_14702_p2;
        add_ln58_72_reg_15557 <= add_ln58_72_fu_14707_p2;
        add_ln58_73_reg_15647 <= add_ln58_73_fu_14780_p2;
        add_ln58_74_reg_15562 <= add_ln58_74_fu_14711_p2;
        add_ln58_75_reg_15427 <= add_ln58_75_fu_14520_p2;
        add_ln58_76_reg_15567 <= add_ln58_76_fu_14715_p2;
        add_ln58_77_reg_15652 <= add_ln58_77_fu_14784_p2;
        add_ln58_79_reg_15572 <= add_ln58_79_fu_14719_p2;
        add_ln58_80_reg_15577 <= add_ln58_80_fu_14724_p2;
        add_ln58_81_reg_15657 <= add_ln58_81_fu_14788_p2;
        add_ln58_82_reg_15582 <= add_ln58_82_fu_14728_p2;
        add_ln58_83_reg_15432 <= add_ln58_83_fu_14525_p2;
        add_ln58_84_reg_15587 <= add_ln58_84_fu_14732_p2;
        add_ln58_85_reg_15662 <= add_ln58_85_fu_14792_p2;
        add_ln58_reg_15437 <= add_ln58_fu_14581_p2;
        data_0_val_read_reg_14922 <= data_0_val_int_reg;
        data_1_val_read_reg_14914 <= data_1_val_int_reg;
        data_2_val_read_reg_14907 <= data_2_val_int_reg;
        data_2_val_read_reg_14907_pp0_iter1_reg <= data_2_val_read_reg_14907;
        data_3_val_read_reg_14900 <= data_3_val_int_reg;
        data_4_val_read_reg_14892 <= data_4_val_int_reg;
        data_5_val_read_reg_14882 <= data_5_val_int_reg;
        data_6_val_read_reg_14876 <= data_6_val_int_reg;
        sub_ln73_2_reg_14936[24 : 7] <= sub_ln73_2_fu_13549_p2[24 : 7];
        trunc_ln42_23_reg_15162 <= {{grp_fu_317_p2[25:10]}};
        trunc_ln42_24_reg_15167 <= {{grp_fu_292_p2[25:10]}};
        trunc_ln42_25_reg_14985 <= {{add_ln73_fu_13641_p2[23:10]}};
        trunc_ln42_25_reg_14985_pp0_iter2_reg <= trunc_ln42_25_reg_14985;
        trunc_ln42_26_reg_15172 <= {{grp_fu_309_p2[22:10]}};
        trunc_ln42_27_reg_15177 <= {{grp_fu_327_p2[25:10]}};
        trunc_ln42_28_reg_15182 <= {{grp_fu_289_p2[24:10]}};
        trunc_ln42_29_reg_15187 <= {{grp_fu_308_p2[25:10]}};
        trunc_ln42_30_reg_15192 <= {{grp_fu_277_p2[25:10]}};
        trunc_ln42_31_reg_15005 <= {{sub_ln73_fu_13692_p2[24:10]}};
        trunc_ln42_31_reg_15005_pp0_iter2_reg <= trunc_ln42_31_reg_15005;
        trunc_ln42_32_reg_15197 <= {{grp_fu_296_p2[25:10]}};
        trunc_ln42_33_reg_15202 <= {{grp_fu_319_p2[25:10]}};
        trunc_ln42_34_reg_15207 <= {{grp_fu_328_p2[25:10]}};
        trunc_ln42_35_reg_15212 <= {{grp_fu_305_p2[22:10]}};
        trunc_ln42_36_reg_15217 <= {{grp_fu_312_p2[25:10]}};
        trunc_ln42_37_reg_15222 <= {{sub_ln73_1_fu_14120_p2[25:10]}};
        trunc_ln42_38_reg_14931 <= {{trunc_ln42_38_fu_13527_p1[15:5]}};
        trunc_ln42_39_reg_15227 <= {{grp_fu_273_p2[25:10]}};
        trunc_ln42_40_reg_15232 <= {{grp_fu_293_p2[24:10]}};
        trunc_ln42_41_reg_15237 <= {{grp_fu_316_p2[25:10]}};
        trunc_ln42_42_reg_15242 <= {{grp_fu_275_p2[25:10]}};
        trunc_ln42_43_reg_15247 <= {{grp_fu_278_p2[25:10]}};
        trunc_ln42_44_reg_15252 <= {{grp_fu_313_p2[25:10]}};
        trunc_ln42_45_reg_15257 <= {{grp_fu_281_p2[25:10]}};
        trunc_ln42_46_reg_15262 <= {{grp_fu_298_p2[25:10]}};
        trunc_ln42_47_reg_15267 <= {{grp_fu_294_p2[25:10]}};
        trunc_ln42_48_reg_15272 <= {{grp_fu_279_p2[24:10]}};
        trunc_ln42_49_reg_15277 <= {{grp_fu_322_p2[24:10]}};
        trunc_ln42_50_reg_15282 <= {{grp_fu_320_p2[23:10]}};
        trunc_ln42_51_reg_15287 <= {{grp_fu_274_p2[25:10]}};
        trunc_ln42_52_reg_15292 <= {{grp_fu_297_p2[25:10]}};
        trunc_ln42_53_reg_15297 <= {{grp_fu_315_p2[25:10]}};
        trunc_ln42_54_reg_15302 <= {{grp_fu_282_p2[24:10]}};
        trunc_ln42_55_reg_15307 <= {{grp_fu_324_p2[22:10]}};
        trunc_ln42_56_reg_15312 <= {{grp_fu_330_p2[25:10]}};
        trunc_ln42_57_reg_15063 <= {{sub_ln73_3_fu_13767_p2[24:10]}};
        trunc_ln42_57_reg_15063_pp0_iter2_reg <= trunc_ln42_57_reg_15063;
        trunc_ln42_58_reg_15317 <= {{grp_fu_300_p2[24:10]}};
        trunc_ln42_59_reg_15322 <= {{grp_fu_299_p2[25:10]}};
        trunc_ln42_60_reg_15327 <= {{grp_fu_284_p2[25:10]}};
        trunc_ln42_61_reg_15332 <= {{grp_fu_286_p2[24:10]}};
        trunc_ln42_62_reg_15082 <= {{sub_ln73_4_fu_13816_p2[24:10]}};
        trunc_ln42_63_reg_15337 <= {{grp_fu_285_p2[25:10]}};
        trunc_ln42_64_reg_15087 <= {{sub_ln73_5_fu_13854_p2[22:10]}};
        trunc_ln42_64_reg_15087_pp0_iter2_reg <= trunc_ln42_64_reg_15087;
        trunc_ln42_65_reg_15342 <= {{grp_fu_323_p2[25:10]}};
        trunc_ln42_66_reg_15347 <= {{grp_fu_295_p2[25:10]}};
        trunc_ln42_67_reg_15352 <= {{grp_fu_302_p2[25:10]}};
        trunc_ln42_68_reg_15357 <= {{grp_fu_287_p2[25:10]}};
        trunc_ln42_69_reg_15362 <= {{grp_fu_329_p2[25:10]}};
        trunc_ln42_70_reg_15107 <= {{grp_fu_290_p2[22:10]}};
        trunc_ln42_71_reg_15367 <= {{grp_fu_288_p2[25:10]}};
        trunc_ln42_72_reg_15372 <= {{grp_fu_318_p2[25:10]}};
        trunc_ln42_73_reg_15377 <= {{grp_fu_311_p2[24:10]}};
        trunc_ln42_74_reg_15382 <= {{grp_fu_303_p2[25:10]}};
        trunc_ln42_75_reg_15387 <= {{grp_fu_291_p2[25:10]}};
        trunc_ln42_76_reg_15392 <= {{grp_fu_310_p2[25:10]}};
        trunc_ln42_77_reg_15112 <= {{grp_fu_270_p2[25:10]}};
        trunc_ln42_78_reg_15117 <= {{grp_fu_332_p2[25:10]}};
        trunc_ln42_79_reg_15122 <= {{grp_fu_321_p2[25:10]}};
        trunc_ln42_80_reg_15127 <= {{grp_fu_280_p2[25:10]}};
        trunc_ln42_81_reg_14961 <= {{add_ln73_1_fu_13587_p2[22:10]}};
        trunc_ln42_81_reg_14961_pp0_iter1_reg <= trunc_ln42_81_reg_14961;
        trunc_ln42_81_reg_14961_pp0_iter2_reg <= trunc_ln42_81_reg_14961_pp0_iter1_reg;
        trunc_ln42_82_reg_15132 <= {{grp_fu_276_p2[22:10]}};
        trunc_ln42_83_reg_15137 <= {{grp_fu_306_p2[25:10]}};
        trunc_ln42_84_reg_15142 <= {{grp_fu_271_p2[25:10]}};
        trunc_ln42_s_reg_15157 <= {{grp_fu_307_p2[25:10]}};
        trunc_ln_reg_15152 <= {{grp_fu_283_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln58_30_fu_14796_p2;
        ap_return_1_int_reg <= add_ln58_38_fu_14800_p2;
        ap_return_2_int_reg <= add_ln58_46_fu_14804_p2;
        ap_return_3_int_reg <= add_ln58_54_fu_14808_p2;
        ap_return_4_int_reg <= add_ln58_62_fu_14812_p2;
        ap_return_5_int_reg <= add_ln58_70_fu_14816_p2;
        ap_return_6_int_reg <= add_ln58_78_fu_14820_p2;
        ap_return_7_int_reg <= add_ln58_86_fu_14824_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_val_int_reg <= data_0_val;
        data_1_val_int_reg <= data_1_val;
        data_2_val_int_reg <= data_2_val;
        data_3_val_int_reg <= data_3_val;
        data_4_val_int_reg <= data_4_val;
        data_5_val_int_reg <= data_5_val;
        data_6_val_int_reg <= data_6_val;
        data_7_val_int_reg <= data_7_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln58_30_fu_14796_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln58_38_fu_14800_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln58_46_fu_14804_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln58_54_fu_14808_p2;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = add_ln58_62_fu_14812_p2;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = add_ln58_70_fu_14816_p2;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = add_ln58_78_fu_14820_p2;
    end else begin
        ap_return_6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = add_ln58_86_fu_14824_p2;
    end else begin
        ap_return_7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_270_ce = 1'b1;
    end else begin
        grp_fu_270_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_271_ce = 1'b1;
    end else begin
        grp_fu_271_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_273_ce = 1'b1;
    end else begin
        grp_fu_273_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_274_ce = 1'b1;
    end else begin
        grp_fu_274_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_275_ce = 1'b1;
    end else begin
        grp_fu_275_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_276_ce = 1'b1;
    end else begin
        grp_fu_276_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_277_ce = 1'b1;
    end else begin
        grp_fu_277_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_278_ce = 1'b1;
    end else begin
        grp_fu_278_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_279_ce = 1'b1;
    end else begin
        grp_fu_279_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_280_ce = 1'b1;
    end else begin
        grp_fu_280_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_281_ce = 1'b1;
    end else begin
        grp_fu_281_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_282_ce = 1'b1;
    end else begin
        grp_fu_282_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_283_ce = 1'b1;
    end else begin
        grp_fu_283_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_284_ce = 1'b1;
    end else begin
        grp_fu_284_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_285_ce = 1'b1;
    end else begin
        grp_fu_285_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_286_ce = 1'b1;
    end else begin
        grp_fu_286_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_287_ce = 1'b1;
    end else begin
        grp_fu_287_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_288_ce = 1'b1;
    end else begin
        grp_fu_288_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_289_ce = 1'b1;
    end else begin
        grp_fu_289_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_290_ce = 1'b1;
    end else begin
        grp_fu_290_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_291_ce = 1'b1;
    end else begin
        grp_fu_291_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_292_ce = 1'b1;
    end else begin
        grp_fu_292_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_293_ce = 1'b1;
    end else begin
        grp_fu_293_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_294_ce = 1'b1;
    end else begin
        grp_fu_294_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_295_ce = 1'b1;
    end else begin
        grp_fu_295_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_296_ce = 1'b1;
    end else begin
        grp_fu_296_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_297_ce = 1'b1;
    end else begin
        grp_fu_297_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_298_ce = 1'b1;
    end else begin
        grp_fu_298_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_299_ce = 1'b1;
    end else begin
        grp_fu_299_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_300_ce = 1'b1;
    end else begin
        grp_fu_300_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_302_ce = 1'b1;
    end else begin
        grp_fu_302_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_303_ce = 1'b1;
    end else begin
        grp_fu_303_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_305_ce = 1'b1;
    end else begin
        grp_fu_305_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_306_ce = 1'b1;
    end else begin
        grp_fu_306_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_307_ce = 1'b1;
    end else begin
        grp_fu_307_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_308_ce = 1'b1;
    end else begin
        grp_fu_308_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_309_ce = 1'b1;
    end else begin
        grp_fu_309_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_310_ce = 1'b1;
    end else begin
        grp_fu_310_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_311_ce = 1'b1;
    end else begin
        grp_fu_311_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_312_ce = 1'b1;
    end else begin
        grp_fu_312_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_313_ce = 1'b1;
    end else begin
        grp_fu_313_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_315_ce = 1'b1;
    end else begin
        grp_fu_315_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_316_ce = 1'b1;
    end else begin
        grp_fu_316_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_317_ce = 1'b1;
    end else begin
        grp_fu_317_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_318_ce = 1'b1;
    end else begin
        grp_fu_318_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_319_ce = 1'b1;
    end else begin
        grp_fu_319_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_320_ce = 1'b1;
    end else begin
        grp_fu_320_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_321_ce = 1'b1;
    end else begin
        grp_fu_321_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_322_ce = 1'b1;
    end else begin
        grp_fu_322_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_323_ce = 1'b1;
    end else begin
        grp_fu_323_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_324_ce = 1'b1;
    end else begin
        grp_fu_324_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_327_ce = 1'b1;
    end else begin
        grp_fu_327_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_328_ce = 1'b1;
    end else begin
        grp_fu_328_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_329_ce = 1'b1;
    end else begin
        grp_fu_329_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_330_ce = 1'b1;
    end else begin
        grp_fu_330_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_332_ce = 1'b1;
    end else begin
        grp_fu_332_ce = 1'b0;
    end
end

assign add_ln58_24_fu_14585_p2 = (trunc_ln42_37_reg_15222 + trunc_ln42_45_reg_15257);

assign add_ln58_25_fu_14736_p2 = (add_ln58_24_reg_15442 + add_ln58_reg_15437);

assign add_ln58_26_fu_14589_p2 = ($signed(trunc_ln42_53_reg_15297) + $signed(sext_ln42_24_fu_14569_p1));

assign add_ln58_27_fu_14485_p2 = ($signed(trunc_ln42_77_reg_15112) + $signed(16'd65330));

assign add_ln58_28_fu_14594_p2 = (add_ln58_27_reg_15397 + trunc_ln42_69_reg_15362);

assign add_ln58_29_fu_14740_p2 = (add_ln58_28_reg_15452 + add_ln58_26_reg_15447);

assign add_ln58_30_fu_14796_p2 = (add_ln58_29_reg_15597 + add_ln58_25_reg_15592);

assign add_ln58_31_fu_14598_p2 = (trunc_ln42_s_reg_15157 + trunc_ln42_30_reg_15192);

assign add_ln58_32_fu_14602_p2 = ($signed(trunc_ln42_46_reg_15262) + $signed(sext_ln42_19_fu_14557_p1));

assign add_ln58_33_fu_14744_p2 = (add_ln58_32_reg_15462 + add_ln58_31_reg_15457);

assign add_ln58_34_fu_14490_p2 = ($signed(sext_ln42_25_fu_14356_p1) + $signed(sext_ln42_28_fu_14419_p1));

assign add_ln58_35_fu_13963_p2 = ($signed(sext_ln73_fu_13720_p1) + $signed(12'd3854));

assign add_ln58_36_fu_14499_p2 = ($signed(sext_ln58_fu_14496_p1) + $signed(trunc_ln42_78_reg_15117));

assign add_ln58_37_fu_14607_p2 = (add_ln58_36_reg_15407 + add_ln58_34_reg_15402);

assign add_ln58_38_fu_14800_p2 = (add_ln58_37_reg_15467_pp0_iter4_reg + add_ln58_33_reg_15602);

assign add_ln58_39_fu_14611_p2 = ($signed(trunc_ln42_23_reg_15162) + $signed(sext_ln42_11_fu_14539_p1));

assign add_ln58_40_fu_14616_p2 = (trunc_ln42_39_reg_15227 + trunc_ln42_47_reg_15267);

assign add_ln58_41_fu_14748_p2 = (add_ln58_40_reg_15477 + add_ln58_39_reg_15472);

assign add_ln58_42_fu_14620_p2 = ($signed(sext_ln42_20_fu_14560_p1) + $signed(trunc_ln42_63_reg_15337));

assign add_ln58_43_fu_14504_p2 = ($signed(trunc_ln42_79_reg_15122) + $signed(16'd65414));

assign add_ln58_44_fu_14625_p2 = (add_ln58_43_reg_15412 + trunc_ln42_71_reg_15367);

assign add_ln58_45_fu_14752_p2 = (add_ln58_44_reg_15487 + add_ln58_42_reg_15482);

assign add_ln58_46_fu_14804_p2 = (add_ln58_45_reg_15612 + add_ln58_41_reg_15607);

assign add_ln58_47_fu_14629_p2 = (trunc_ln42_24_reg_15167 + trunc_ln42_32_reg_15197);

assign add_ln58_48_fu_14633_p2 = ($signed(sext_ln42_14_fu_14545_p1) + $signed(sext_ln42_16_fu_14548_p1));

assign add_ln58_49_fu_14756_p2 = (add_ln58_48_reg_15497 + add_ln58_47_reg_15492);

assign add_ln58_50_fu_14639_p2 = ($signed(trunc_ln42_56_reg_15312) + $signed(sext_ln42_26_fu_14572_p1));

assign add_ln58_51_fu_14509_p2 = (trunc_ln42_80_reg_15127 + 16'd144);

assign add_ln58_52_fu_14644_p2 = (add_ln58_51_reg_15417 + trunc_ln42_72_reg_15372);

assign add_ln58_53_fu_14760_p2 = (add_ln58_52_reg_15507 + add_ln58_50_reg_15502);

assign add_ln58_54_fu_14808_p2 = (add_ln58_53_reg_15622 + add_ln58_49_reg_15617);

assign add_ln58_55_fu_14648_p2 = ($signed(sext_ln42_fu_14530_p1) + $signed(trunc_ln42_33_reg_15202));

assign add_ln58_56_fu_14653_p2 = ($signed(trunc_ln42_41_reg_15237) + $signed(sext_ln42_17_fu_14551_p1));

assign add_ln58_57_fu_14764_p2 = (add_ln58_56_reg_15517 + add_ln58_55_reg_15512);

assign add_ln58_58_fu_14658_p2 = ($signed(sext_ln42_21_fu_14563_p1) + $signed(trunc_ln42_65_reg_15342));

assign add_ln58_59_fu_14663_p2 = ($signed(sext_ln73_14_fu_14578_p1) + $signed(14'd16322));

assign add_ln58_60_fu_14673_p2 = ($signed(sext_ln58_1_fu_14669_p1) + $signed(sext_ln42_29_fu_14575_p1));

assign add_ln58_61_fu_14768_p2 = (add_ln58_60_reg_15527 + add_ln58_58_reg_15522);

assign add_ln58_62_fu_14812_p2 = (add_ln58_61_reg_15632 + add_ln58_57_reg_15627);

assign add_ln58_63_fu_14679_p2 = ($signed(sext_ln42_9_fu_14533_p1) + $signed(trunc_ln42_34_reg_15207));

assign add_ln58_64_fu_14684_p2 = ($signed(trunc_ln42_42_reg_15242) + $signed(sext_ln42_18_fu_14554_p1));

assign add_ln58_65_fu_14772_p2 = (add_ln58_64_reg_15537 + add_ln58_63_reg_15532);

assign add_ln58_66_fu_14689_p2 = ($signed(sext_ln42_22_fu_14566_p1) + $signed(trunc_ln42_66_reg_15347));

assign add_ln58_67_fu_14514_p2 = ($signed(sext_ln42_30_fu_14482_p1) + $signed(14'd16240));

assign add_ln58_68_fu_14697_p2 = ($signed(sext_ln58_2_fu_14694_p1) + $signed(trunc_ln42_74_reg_15382));

assign add_ln58_69_fu_14776_p2 = (add_ln58_68_reg_15547 + add_ln58_66_reg_15542);

assign add_ln58_70_fu_14816_p2 = (add_ln58_69_reg_15642 + add_ln58_65_reg_15637);

assign add_ln58_71_fu_14702_p2 = ($signed(trunc_ln42_27_reg_15177) + $signed(sext_ln42_12_fu_14542_p1));

assign add_ln58_72_fu_14707_p2 = (trunc_ln42_43_reg_15247 + trunc_ln42_51_reg_15287);

assign add_ln58_73_fu_14780_p2 = (add_ln58_72_reg_15557 + add_ln58_71_reg_15552);

assign add_ln58_74_fu_14711_p2 = (trunc_ln42_59_reg_15322 + trunc_ln42_67_reg_15352);

assign add_ln58_75_fu_14520_p2 = ($signed(trunc_ln42_83_reg_15137) + $signed(16'd65434));

assign add_ln58_76_fu_14715_p2 = (add_ln58_75_reg_15427 + trunc_ln42_75_reg_15387);

assign add_ln58_77_fu_14784_p2 = (add_ln58_76_reg_15567 + add_ln58_74_reg_15562);

assign add_ln58_78_fu_14820_p2 = (add_ln58_77_reg_15652 + add_ln58_73_reg_15647);

assign add_ln58_79_fu_14719_p2 = ($signed(sext_ln42_10_fu_14536_p1) + $signed(trunc_ln42_36_reg_15217));

assign add_ln58_80_fu_14724_p2 = (trunc_ln42_44_reg_15252 + trunc_ln42_52_reg_15292);

assign add_ln58_81_fu_14788_p2 = (add_ln58_80_reg_15577 + add_ln58_79_reg_15572);

assign add_ln58_82_fu_14728_p2 = (trunc_ln42_60_reg_15327 + trunc_ln42_68_reg_15357);

assign add_ln58_83_fu_14525_p2 = (trunc_ln42_84_reg_15142 + 16'd990);

assign add_ln58_84_fu_14732_p2 = (add_ln58_83_reg_15432 + trunc_ln42_76_reg_15392);

assign add_ln58_85_fu_14792_p2 = (add_ln58_84_reg_15587 + add_ln58_82_reg_15582);

assign add_ln58_86_fu_14824_p2 = (add_ln58_85_reg_15662 + add_ln58_81_reg_15657);

assign add_ln58_fu_14581_p2 = (trunc_ln_reg_15152 + trunc_ln42_29_reg_15187);

assign add_ln73_1_fu_13587_p2 = ($signed(sext_ln73_13_fu_13583_p1) + $signed(sext_ln70_20_fu_13560_p1));

assign add_ln73_fu_13641_p2 = ($signed(sext_ln73_2_fu_13626_p1) + $signed(sext_ln73_3_fu_13637_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_270_p0 = sext_ln70_21_fu_13565_p1;

assign grp_fu_270_p1 = 26'd67108169;

assign grp_fu_271_p0 = sext_ln70_21_fu_13565_p1;

assign grp_fu_271_p1 = 26'd67108177;

assign grp_fu_273_p0 = sext_ln42_13_fu_13708_p1;

assign grp_fu_273_p1 = 26'd369;

assign grp_fu_274_p0 = sext_ln42_15_fu_13732_p1;

assign grp_fu_274_p1 = 26'd806;

assign grp_fu_275_p0 = sext_ln42_13_fu_13708_p1;

assign grp_fu_275_p1 = 26'd387;

assign grp_fu_276_p0 = sext_ln70_20_fu_13560_p1;

assign grp_fu_276_p1 = 23'd55;

assign grp_fu_277_p0 = sext_ln70_11_fu_13661_p1;

assign grp_fu_277_p1 = 26'd561;

assign grp_fu_278_p0 = sext_ln42_13_fu_13708_p1;

assign grp_fu_278_p1 = 26'd436;

assign grp_fu_279_p0 = sext_ln70_14_fu_13727_p1;

assign grp_fu_279_p1 = 25'd231;

assign grp_fu_280_p0 = sext_ln70_21_fu_13565_p1;

assign grp_fu_280_p1 = 26'd1468;

assign grp_fu_281_p0 = sext_ln42_15_fu_13732_p1;

assign grp_fu_281_p1 = 26'd428;

assign grp_fu_282_p0 = sext_ln70_16_fu_13744_p1;

assign grp_fu_282_p1 = 25'd201;

assign grp_fu_283_p0 = sext_ln70_9_fu_13611_p1;

assign grp_fu_283_p1 = 26'd905;

assign grp_fu_284_p0 = sext_ln73_1_fu_13749_p1;

assign grp_fu_284_p1 = 26'd1604;

assign grp_fu_285_p0 = sext_ln42_23_fu_13782_p1;

assign grp_fu_285_p1 = 26'd67107830;

assign grp_fu_286_p1 = 25'd33554292;

assign grp_fu_287_p0 = sext_ln42_23_fu_13782_p1;

assign grp_fu_287_p1 = 26'd1211;

assign grp_fu_288_p0 = sext_ln42_27_fu_13874_p1;

assign grp_fu_288_p1 = 26'd67108417;

assign grp_fu_289_p1 = 25'd33554211;

assign grp_fu_290_p1 = 23'd8388555;

assign grp_fu_291_p0 = sext_ln42_27_fu_13874_p1;

assign grp_fu_291_p1 = 26'd67108390;

assign grp_fu_292_p0 = sext_ln70_9_fu_13611_p1;

assign grp_fu_292_p1 = 26'd67108134;

assign grp_fu_293_p1 = 25'd33554266;

assign grp_fu_294_p0 = sext_ln42_15_fu_13732_p1;

assign grp_fu_294_p1 = 26'd67108537;

assign grp_fu_295_p0 = sext_ln42_23_fu_13782_p1;

assign grp_fu_295_p1 = 26'd67108180;

assign grp_fu_296_p0 = sext_ln70_11_fu_13661_p1;

assign grp_fu_296_p1 = 26'd67107809;

assign grp_fu_297_p0 = sext_ln42_15_fu_13732_p1;

assign grp_fu_297_p1 = 26'd524;

assign grp_fu_298_p0 = sext_ln42_15_fu_13732_p1;

assign grp_fu_298_p1 = 26'd1278;

assign grp_fu_299_p0 = sext_ln73_1_fu_13749_p1;

assign grp_fu_299_p1 = 26'd673;

assign grp_fu_300_p0 = sext_ln70_16_fu_13744_p1;

assign grp_fu_300_p1 = 25'd33554223;

assign grp_fu_302_p0 = sext_ln42_23_fu_13782_p1;

assign grp_fu_302_p1 = 26'd67108540;

assign grp_fu_303_p0 = sext_ln42_27_fu_13874_p1;

assign grp_fu_303_p1 = 26'd67108542;

assign grp_fu_305_p1 = 23'd8388561;

assign grp_fu_306_p0 = sext_ln70_21_fu_13565_p1;

assign grp_fu_306_p1 = 26'd67108158;

assign grp_fu_307_p0 = sext_ln70_9_fu_13611_p1;

assign grp_fu_307_p1 = 26'd1001;

assign grp_fu_308_p0 = sext_ln70_11_fu_13661_p1;

assign grp_fu_308_p1 = 26'd666;

assign grp_fu_309_p1 = 23'd49;

assign grp_fu_310_p0 = sext_ln42_27_fu_13874_p1;

assign grp_fu_310_p1 = 26'd319;

assign grp_fu_311_p1 = 25'd33554245;

assign grp_fu_312_p0 = sext_ln70_11_fu_13661_p1;

assign grp_fu_312_p1 = 26'd1577;

assign grp_fu_313_p0 = sext_ln42_13_fu_13708_p1;

assign grp_fu_313_p1 = 26'd67107994;

assign grp_fu_315_p0 = sext_ln73_1_fu_13749_p1;

assign grp_fu_315_p1 = 26'd846;

assign grp_fu_316_p0 = sext_ln42_13_fu_13708_p1;

assign grp_fu_316_p1 = 26'd67108446;

assign grp_fu_317_p0 = sext_ln70_9_fu_13611_p1;

assign grp_fu_317_p1 = 26'd304;

assign grp_fu_318_p0 = sext_ln42_27_fu_13874_p1;

assign grp_fu_318_p1 = 26'd555;

assign grp_fu_319_p0 = sext_ln70_11_fu_13661_p1;

assign grp_fu_319_p1 = 26'd277;

assign grp_fu_320_p1 = 24'd83;

assign grp_fu_321_p0 = sext_ln70_21_fu_13565_p1;

assign grp_fu_321_p1 = 26'd67108431;

assign grp_fu_322_p0 = sext_ln70_14_fu_13727_p1;

assign grp_fu_322_p1 = 25'd33554189;

assign grp_fu_323_p0 = sext_ln42_23_fu_13782_p1;

assign grp_fu_323_p1 = 26'd67108428;

assign grp_fu_324_p1 = 23'd54;

assign grp_fu_327_p0 = sext_ln70_9_fu_13611_p1;

assign grp_fu_327_p1 = 26'd784;

assign grp_fu_328_p0 = sext_ln70_11_fu_13661_p1;

assign grp_fu_328_p1 = 26'd67108326;

assign grp_fu_329_p0 = sext_ln42_27_fu_13874_p1;

assign grp_fu_329_p1 = 26'd67108435;

assign grp_fu_330_p0 = sext_ln73_1_fu_13749_p1;

assign grp_fu_330_p1 = 26'd67107069;

assign grp_fu_332_p0 = sext_ln70_21_fu_13565_p1;

assign grp_fu_332_p1 = 26'd67107614;

assign sext_ln42_10_fu_14536_p1 = $signed(trunc_ln42_28_reg_15182);

assign sext_ln42_11_fu_14539_p1 = $signed(trunc_ln42_31_reg_15005_pp0_iter2_reg);

assign sext_ln42_12_fu_14542_p1 = $signed(trunc_ln42_35_reg_15212);

assign sext_ln42_13_fu_13708_p1 = data_2_val_read_reg_14907;

assign sext_ln42_14_fu_14545_p1 = $signed(trunc_ln42_40_reg_15232);

assign sext_ln42_15_fu_13732_p1 = data_3_val_read_reg_14900;

assign sext_ln42_16_fu_14548_p1 = $signed(trunc_ln42_48_reg_15272);

assign sext_ln42_17_fu_14551_p1 = $signed(trunc_ln42_49_reg_15277);

assign sext_ln42_18_fu_14554_p1 = $signed(trunc_ln42_50_reg_15282);

assign sext_ln42_19_fu_14557_p1 = $signed(trunc_ln42_54_reg_15302);

assign sext_ln42_20_fu_14560_p1 = $signed(trunc_ln42_55_reg_15307);

assign sext_ln42_21_fu_14563_p1 = $signed(trunc_ln42_57_reg_15063_pp0_iter2_reg);

assign sext_ln42_22_fu_14566_p1 = $signed(trunc_ln42_58_reg_15317);

assign sext_ln42_23_fu_13782_p1 = data_5_val_read_reg_14882;

assign sext_ln42_24_fu_14569_p1 = $signed(trunc_ln42_61_reg_15332);

assign sext_ln42_25_fu_14356_p1 = $signed(trunc_ln42_62_reg_15082);

assign sext_ln42_26_fu_14572_p1 = $signed(trunc_ln42_64_reg_15087_pp0_iter2_reg);

assign sext_ln42_27_fu_13874_p1 = data_6_val_read_reg_14876;

assign sext_ln42_28_fu_14419_p1 = $signed(trunc_ln42_70_reg_15107);

assign sext_ln42_29_fu_14575_p1 = $signed(trunc_ln42_73_reg_15377);

assign sext_ln42_30_fu_14482_p1 = $signed(trunc_ln42_82_reg_15132);

assign sext_ln42_9_fu_14533_p1 = $signed(trunc_ln42_26_reg_15172);

assign sext_ln42_fu_14530_p1 = $signed(trunc_ln42_25_reg_14985_pp0_iter2_reg);

assign sext_ln58_1_fu_14669_p1 = $signed(add_ln58_59_fu_14663_p2);

assign sext_ln58_2_fu_14694_p1 = $signed(add_ln58_67_reg_15422);

assign sext_ln58_fu_14496_p1 = $signed(add_ln58_35_reg_15147);

assign sext_ln70_11_fu_13661_p1 = data_1_val_read_reg_14914;

assign sext_ln70_14_fu_13727_p1 = data_3_val_read_reg_14900;

assign sext_ln70_16_fu_13744_p1 = data_4_val_read_reg_14892;

assign sext_ln70_19_fu_13555_p0 = data_6_val_int_reg;

assign sext_ln70_20_fu_13560_p0 = data_7_val_int_reg;

assign sext_ln70_20_fu_13560_p1 = sext_ln70_20_fu_13560_p0;

assign sext_ln70_21_fu_13565_p0 = data_7_val_int_reg;

assign sext_ln70_21_fu_13565_p1 = sext_ln70_21_fu_13565_p0;

assign sext_ln70_9_fu_13611_p1 = data_0_val_read_reg_14922;

assign sext_ln73_10_fu_13812_p1 = $signed(tmp_11_fu_13805_p3);

assign sext_ln73_11_fu_13839_p1 = $signed(tmp_12_fu_13832_p3);

assign sext_ln73_12_fu_13850_p1 = $signed(tmp_13_fu_13843_p3);

assign sext_ln73_13_fu_13583_p1 = $signed(tmp_14_fu_13575_p3);

assign sext_ln73_14_fu_14578_p1 = $signed(trunc_ln42_81_reg_14961_pp0_iter2_reg);

assign sext_ln73_1_fu_13749_p1 = data_4_val_read_reg_14892;

assign sext_ln73_2_fu_13626_p1 = $signed(tmp_fu_13619_p3);

assign sext_ln73_3_fu_13637_p1 = $signed(tmp_4_fu_13630_p3);

assign sext_ln73_4_fu_13677_p1 = $signed(tmp_5_fu_13670_p3);

assign sext_ln73_5_fu_13688_p1 = $signed(tmp_6_fu_13681_p3);

assign sext_ln73_6_fu_14116_p1 = $signed(tmp_7_fu_14109_p3);

assign sext_ln73_7_fu_13545_p1 = $signed(tmp_8_fu_13537_p3);

assign sext_ln73_8_fu_13763_p1 = $signed(tmp_9_fu_13756_p3);

assign sext_ln73_9_fu_13801_p1 = $signed(tmp_10_fu_13794_p3);

assign sext_ln73_fu_13720_p1 = $signed(trunc_ln42_38_reg_14931);

assign sub_ln73_1_fu_14120_p2 = ($signed(26'd0) - $signed(sext_ln73_6_fu_14116_p1));

assign sub_ln73_2_fu_13549_p2 = ($signed(25'd0) - $signed(sext_ln73_7_fu_13545_p1));

assign sub_ln73_3_fu_13767_p2 = ($signed(sub_ln73_2_reg_14936) - $signed(sext_ln73_8_fu_13763_p1));

assign sub_ln73_4_fu_13816_p2 = ($signed(sext_ln73_10_fu_13812_p1) - $signed(sext_ln73_9_fu_13801_p1));

assign sub_ln73_5_fu_13854_p2 = ($signed(sext_ln73_12_fu_13850_p1) - $signed(sext_ln73_11_fu_13839_p1));

assign sub_ln73_fu_13692_p2 = ($signed(sext_ln73_4_fu_13677_p1) - $signed(sext_ln73_5_fu_13688_p1));

assign tmp_10_fu_13794_p3 = {{data_5_val_read_reg_14882}, {8'd0}};

assign tmp_11_fu_13805_p3 = {{data_5_val_read_reg_14882}, {3'd0}};

assign tmp_12_fu_13832_p3 = {{data_5_val_read_reg_14882}, {6'd0}};

assign tmp_13_fu_13843_p3 = {{data_5_val_read_reg_14882}, {2'd0}};

assign tmp_14_fu_13575_p1 = data_7_val_int_reg;

assign tmp_14_fu_13575_p3 = {{tmp_14_fu_13575_p1}, {5'd0}};

assign tmp_4_fu_13630_p3 = {{data_0_val_read_reg_14922}, {4'd0}};

assign tmp_5_fu_13670_p3 = {{data_1_val_read_reg_14914}, {8'd0}};

assign tmp_6_fu_13681_p3 = {{data_1_val_read_reg_14914}, {4'd0}};

assign tmp_7_fu_14109_p3 = {{data_2_val_read_reg_14907_pp0_iter1_reg}, {9'd0}};

assign tmp_8_fu_13537_p1 = data_4_val_int_reg;

assign tmp_8_fu_13537_p3 = {{tmp_8_fu_13537_p1}, {7'd0}};

assign tmp_9_fu_13756_p3 = {{data_4_val_read_reg_14892}, {4'd0}};

assign tmp_fu_13619_p3 = {{data_0_val_read_reg_14922}, {6'd0}};

assign trunc_ln42_38_fu_13527_p1 = data_2_val_int_reg;

always @ (posedge ap_clk) begin
    sub_ln73_2_reg_14936[6:0] <= 7'b0000000;
end

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s
