// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;

reg   [15:0] data_6_val_read_reg_2430;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_5_val_read_reg_2435;
reg   [15:0] data_4_val_read_reg_2441;
reg  signed [15:0] data_2_val_read_reg_2446;
reg  signed [15:0] data_1_val_read_reg_2453;
wire  signed [25:0] sext_ln70_fu_1914_p1;
wire   [25:0] sub_ln42_1_fu_1943_p2;
reg   [25:0] sub_ln42_1_reg_2476;
wire  signed [25:0] sext_ln42_3_fu_1949_p1;
wire  signed [25:0] sext_ln42_7_fu_1960_p1;
reg   [15:0] trunc_ln_reg_2503;
reg   [15:0] trunc_ln42_1_reg_2508;
reg   [15:0] trunc_ln42_2_reg_2513;
reg   [14:0] trunc_ln42_3_reg_2518;
reg   [15:0] trunc_ln42_4_reg_2523;
reg   [15:0] trunc_ln42_5_reg_2528;
wire  signed [25:0] sext_ln70_2_fu_2055_p1;
reg   [15:0] trunc_ln42_6_reg_2538;
reg   [13:0] trunc_ln42_7_reg_2543;
reg   [15:0] trunc_ln42_9_reg_2548;
reg   [14:0] trunc_ln42_s_reg_2553;
reg   [15:0] trunc_ln42_10_reg_2558;
reg   [15:0] trunc_ln42_10_reg_2558_pp0_iter2_reg;
wire  signed [25:0] sext_ln42_5_fu_2142_p1;
wire  signed [25:0] sext_ln70_5_fu_2152_p1;
wire  signed [25:0] sext_ln70_6_fu_2157_p1;
reg   [14:0] trunc_ln42_20_reg_2588;
reg   [15:0] trunc_ln42_21_reg_2593;
reg   [15:0] trunc_ln42_22_reg_2598;
reg   [15:0] trunc_ln42_8_reg_2603;
reg   [15:0] trunc_ln42_11_reg_2608;
reg   [15:0] trunc_ln42_12_reg_2613;
reg   [15:0] trunc_ln42_13_reg_2618;
reg   [15:0] trunc_ln42_14_reg_2623;
reg   [15:0] trunc_ln42_15_reg_2628;
reg   [13:0] trunc_ln42_16_reg_2633;
reg   [15:0] trunc_ln42_17_reg_2638;
reg   [15:0] trunc_ln42_18_reg_2643;
reg   [15:0] trunc_ln42_19_reg_2648;
wire   [15:0] add_ln58_fu_2305_p2;
reg   [15:0] add_ln58_reg_2653;
wire   [15:0] add_ln58_1_fu_2310_p2;
reg   [15:0] add_ln58_1_reg_2658;
wire   [15:0] add_ln58_4_fu_2314_p2;
reg   [15:0] add_ln58_4_reg_2663;
wire   [15:0] add_ln58_8_fu_2320_p2;
reg   [15:0] add_ln58_8_reg_2668;
wire   [15:0] add_ln58_9_fu_2324_p2;
reg   [15:0] add_ln58_9_reg_2673;
wire   [15:0] add_ln58_12_fu_2330_p2;
reg   [15:0] add_ln58_12_reg_2678;
wire   [15:0] add_ln58_16_fu_2335_p2;
reg   [15:0] add_ln58_16_reg_2683;
reg   [15:0] add_ln58_16_reg_2683_pp0_iter3_reg;
wire   [15:0] add_ln58_20_fu_2339_p2;
reg   [15:0] add_ln58_20_reg_2688;
wire   [15:0] add_ln58_2_fu_2347_p2;
reg   [15:0] add_ln58_2_reg_2693;
reg   [15:0] add_ln58_2_reg_2693_pp0_iter4_reg;
wire   [15:0] add_ln58_3_fu_2351_p2;
reg   [15:0] add_ln58_3_reg_2698;
wire   [15:0] add_ln58_5_fu_2355_p2;
reg   [15:0] add_ln58_5_reg_2703;
wire   [15:0] add_ln58_10_fu_2359_p2;
reg   [15:0] add_ln58_10_reg_2708;
reg   [15:0] add_ln58_10_reg_2708_pp0_iter4_reg;
wire   [15:0] add_ln58_11_fu_2363_p2;
reg   [15:0] add_ln58_11_reg_2713;
wire   [15:0] add_ln58_13_fu_2367_p2;
reg   [15:0] add_ln58_13_reg_2718;
wire   [15:0] add_ln58_17_fu_2371_p2;
reg   [15:0] add_ln58_17_reg_2723;
wire   [15:0] add_ln58_19_fu_2375_p2;
reg   [15:0] add_ln58_19_reg_2728;
wire   [15:0] add_ln58_21_fu_2380_p2;
reg   [15:0] add_ln58_21_reg_2733;
wire   [15:0] add_ln58_6_fu_2384_p2;
reg   [15:0] add_ln58_6_reg_2738;
wire   [15:0] add_ln58_14_fu_2388_p2;
reg   [15:0] add_ln58_14_reg_2743;
wire   [15:0] add_ln58_18_fu_2392_p2;
reg   [15:0] add_ln58_18_reg_2748;
wire   [15:0] add_ln58_22_fu_2396_p2;
reg   [15:0] add_ln58_22_reg_2753;
wire  signed [11:0] grp_fu_166_p1;
wire    ap_block_pp0_stage0;
wire  signed [8:0] grp_fu_167_p1;
wire  signed [15:0] grp_fu_168_p0;
wire  signed [11:0] grp_fu_168_p1;
wire  signed [15:0] grp_fu_169_p0;
wire  signed [9:0] grp_fu_169_p1;
wire  signed [15:0] grp_fu_170_p0;
wire  signed [9:0] grp_fu_170_p1;
wire  signed [15:0] grp_fu_171_p0;
wire  signed [11:0] grp_fu_171_p1;
wire  signed [8:0] grp_fu_172_p1;
wire  signed [15:0] grp_fu_174_p0;
wire  signed [10:0] grp_fu_174_p1;
wire  signed [8:0] grp_fu_176_p1;
wire  signed [15:0] grp_fu_177_p0;
wire   [10:0] grp_fu_177_p1;
wire  signed [7:0] grp_fu_178_p1;
wire  signed [15:0] grp_fu_179_p0;
wire  signed [9:0] grp_fu_179_p1;
wire  signed [15:0] grp_fu_181_p0;
wire   [11:0] grp_fu_181_p1;
wire  signed [15:0] grp_fu_182_p0;
wire   [11:0] grp_fu_182_p1;
wire  signed [15:0] grp_fu_183_p0;
wire   [9:0] grp_fu_183_p1;
wire  signed [15:0] grp_fu_184_p0;
wire   [10:0] grp_fu_184_p1;
wire  signed [15:0] grp_fu_185_p0;
wire  signed [9:0] grp_fu_185_p1;
wire  signed [15:0] grp_fu_186_p0;
wire  signed [9:0] grp_fu_186_p1;
wire  signed [15:0] grp_fu_187_p0;
wire   [11:0] grp_fu_187_p1;
wire  signed [15:0] grp_fu_188_p0;
wire  signed [9:0] grp_fu_188_p1;
wire  signed [15:0] grp_fu_189_p0;
wire  signed [10:0] grp_fu_189_p1;
wire  signed [15:0] sext_ln42_fu_1921_p0;
wire  signed [15:0] sext_ln70_1_fu_1926_p0;
wire  signed [15:0] tmp_1_fu_1931_p1;
wire   [24:0] tmp_1_fu_1931_p3;
wire  signed [25:0] sext_ln42_10_fu_1939_p1;
wire  signed [15:0] sext_ln42_3_fu_1949_p0;
wire  signed [15:0] sext_ln70_3_fu_1955_p0;
wire  signed [15:0] sext_ln42_7_fu_1960_p0;
wire  signed [15:0] sext_ln70_7_fu_1966_p0;
wire   [25:0] grp_fu_187_p2;
wire   [25:0] grp_fu_168_p2;
wire   [25:0] grp_fu_185_p2;
wire   [24:0] grp_fu_172_p2;
wire   [25:0] grp_fu_166_p2;
wire   [18:0] tmp_fu_2028_p3;
wire  signed [25:0] sext_ln42_9_fu_2035_p1;
wire   [25:0] p_shl1_fu_2021_p3;
wire   [25:0] sub_ln42_fu_2039_p2;
wire   [25:0] sub_ln42_2_fu_2059_p2;
wire   [22:0] tmp_2_fu_2074_p3;
wire   [16:0] tmp_3_fu_2085_p3;
wire  signed [23:0] sext_ln73_1_fu_2092_p1;
wire  signed [23:0] sext_ln73_fu_2081_p1;
wire   [23:0] sub_ln73_fu_2096_p2;
wire   [25:0] grp_fu_189_p2;
wire   [24:0] grp_fu_167_p2;
wire   [25:0] grp_fu_181_p2;
wire   [24:0] grp_fu_176_p2;
wire   [25:0] grp_fu_182_p2;
wire   [25:0] grp_fu_174_p2;
wire   [25:0] grp_fu_188_p2;
wire   [25:0] grp_fu_186_p2;
wire   [25:0] grp_fu_184_p2;
wire   [25:0] grp_fu_170_p2;
wire   [25:0] grp_fu_169_p2;
wire   [25:0] grp_fu_183_p2;
wire   [23:0] grp_fu_178_p2;
wire   [25:0] grp_fu_177_p2;
wire   [25:0] grp_fu_171_p2;
wire   [25:0] grp_fu_179_p2;
wire  signed [15:0] sext_ln42_1_fu_2193_p1;
wire  signed [15:0] sext_ln42_8_fu_2302_p1;
wire  signed [15:0] sext_ln42_2_fu_2196_p1;
wire  signed [15:0] sext_ln42_4_fu_2209_p1;
wire  signed [15:0] sext_ln42_6_fu_2344_p1;
wire   [15:0] add_ln58_7_fu_2400_p2;
wire   [15:0] add_ln58_15_fu_2404_p2;
wire   [15:0] add_ln58_23_fu_2408_p2;
reg    grp_fu_166_ce;
reg    grp_fu_167_ce;
reg    grp_fu_168_ce;
reg    grp_fu_169_ce;
reg    grp_fu_170_ce;
reg    grp_fu_171_ce;
reg    grp_fu_172_ce;
reg    grp_fu_174_ce;
reg    grp_fu_176_ce;
reg    grp_fu_177_ce;
reg    grp_fu_178_ce;
reg    grp_fu_179_ce;
reg    grp_fu_181_ce;
reg    grp_fu_182_ce;
reg    grp_fu_183_ce;
reg    grp_fu_184_ce;
reg    grp_fu_185_ce;
reg    grp_fu_186_ce;
reg    grp_fu_187_ce;
reg    grp_fu_188_ce;
reg    grp_fu_189_ce;
reg    ap_ce_reg;
reg   [15:0] data_0_val_int_reg;
reg   [15:0] data_1_val_int_reg;
reg   [15:0] data_2_val_int_reg;
reg   [15:0] data_3_val_int_reg;
reg   [15:0] data_4_val_int_reg;
reg   [15:0] data_5_val_int_reg;
reg   [15:0] data_6_val_int_reg;
reg   [15:0] data_7_val_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U123(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln42_fu_1921_p0),
    .din1(grp_fu_166_p1),
    .ce(grp_fu_166_ce),
    .dout(grp_fu_166_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U124(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln70_3_fu_1955_p0),
    .din1(grp_fu_167_p1),
    .ce(grp_fu_167_ce),
    .dout(grp_fu_167_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U125(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_168_p0),
    .din1(grp_fu_168_p1),
    .ce(grp_fu_168_ce),
    .dout(grp_fu_168_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_169_p0),
    .din1(grp_fu_169_p1),
    .ce(grp_fu_169_ce),
    .dout(grp_fu_169_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_170_p0),
    .din1(grp_fu_170_p1),
    .ce(grp_fu_170_ce),
    .dout(grp_fu_170_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_171_p0),
    .din1(grp_fu_171_p1),
    .ce(grp_fu_171_ce),
    .dout(grp_fu_171_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U129(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln70_1_fu_1926_p0),
    .din1(grp_fu_172_p1),
    .ce(grp_fu_172_ce),
    .dout(grp_fu_172_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U130(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_174_p0),
    .din1(grp_fu_174_p1),
    .ce(grp_fu_174_ce),
    .dout(grp_fu_174_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U131(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln70_7_fu_1966_p0),
    .din1(grp_fu_176_p1),
    .ce(grp_fu_176_ce),
    .dout(grp_fu_176_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U132(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_177_p0),
    .din1(grp_fu_177_p1),
    .ce(grp_fu_177_ce),
    .dout(grp_fu_177_p2)
);

myproject_mul_16s_8s_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_2_0_U133(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_5_val_read_reg_2435),
    .din1(grp_fu_178_p1),
    .ce(grp_fu_178_ce),
    .dout(grp_fu_178_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U134(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_179_p0),
    .din1(grp_fu_179_p1),
    .ce(grp_fu_179_ce),
    .dout(grp_fu_179_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U135(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_181_p0),
    .din1(grp_fu_181_p1),
    .ce(grp_fu_181_ce),
    .dout(grp_fu_181_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U136(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_182_p0),
    .din1(grp_fu_182_p1),
    .ce(grp_fu_182_ce),
    .dout(grp_fu_182_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U137(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .din1(grp_fu_183_p1),
    .ce(grp_fu_183_ce),
    .dout(grp_fu_183_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U138(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_184_p0),
    .din1(grp_fu_184_p1),
    .ce(grp_fu_184_ce),
    .dout(grp_fu_184_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_185_p0),
    .din1(grp_fu_185_p1),
    .ce(grp_fu_185_ce),
    .dout(grp_fu_185_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_186_p0),
    .din1(grp_fu_186_p1),
    .ce(grp_fu_186_ce),
    .dout(grp_fu_186_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_187_p0),
    .din1(grp_fu_187_p1),
    .ce(grp_fu_187_ce),
    .dout(grp_fu_187_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_188_p0),
    .din1(grp_fu_188_p1),
    .ce(grp_fu_188_ce),
    .dout(grp_fu_188_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_189_p0),
    .din1(grp_fu_189_p1),
    .ce(grp_fu_189_ce),
    .dout(grp_fu_189_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln58_10_reg_2708 <= add_ln58_10_fu_2359_p2;
        add_ln58_10_reg_2708_pp0_iter4_reg <= add_ln58_10_reg_2708;
        add_ln58_11_reg_2713 <= add_ln58_11_fu_2363_p2;
        add_ln58_12_reg_2678 <= add_ln58_12_fu_2330_p2;
        add_ln58_13_reg_2718 <= add_ln58_13_fu_2367_p2;
        add_ln58_14_reg_2743 <= add_ln58_14_fu_2388_p2;
        add_ln58_16_reg_2683 <= add_ln58_16_fu_2335_p2;
        add_ln58_16_reg_2683_pp0_iter3_reg <= add_ln58_16_reg_2683;
        add_ln58_17_reg_2723 <= add_ln58_17_fu_2371_p2;
        add_ln58_18_reg_2748 <= add_ln58_18_fu_2392_p2;
        add_ln58_19_reg_2728 <= add_ln58_19_fu_2375_p2;
        add_ln58_1_reg_2658 <= add_ln58_1_fu_2310_p2;
        add_ln58_20_reg_2688 <= add_ln58_20_fu_2339_p2;
        add_ln58_21_reg_2733 <= add_ln58_21_fu_2380_p2;
        add_ln58_22_reg_2753 <= add_ln58_22_fu_2396_p2;
        add_ln58_2_reg_2693 <= add_ln58_2_fu_2347_p2;
        add_ln58_2_reg_2693_pp0_iter4_reg <= add_ln58_2_reg_2693;
        add_ln58_3_reg_2698 <= add_ln58_3_fu_2351_p2;
        add_ln58_4_reg_2663 <= add_ln58_4_fu_2314_p2;
        add_ln58_5_reg_2703 <= add_ln58_5_fu_2355_p2;
        add_ln58_6_reg_2738 <= add_ln58_6_fu_2384_p2;
        add_ln58_8_reg_2668 <= add_ln58_8_fu_2320_p2;
        add_ln58_9_reg_2673 <= add_ln58_9_fu_2324_p2;
        add_ln58_reg_2653 <= add_ln58_fu_2305_p2;
        data_1_val_read_reg_2453 <= data_1_val_int_reg;
        data_2_val_read_reg_2446 <= data_2_val_int_reg;
        data_4_val_read_reg_2441 <= data_4_val_int_reg;
        data_5_val_read_reg_2435 <= data_5_val_int_reg;
        data_6_val_read_reg_2430 <= data_6_val_int_reg;
        sub_ln42_1_reg_2476[25 : 9] <= sub_ln42_1_fu_1943_p2[25 : 9];
        trunc_ln42_10_reg_2558 <= {{grp_fu_181_p2[25:10]}};
        trunc_ln42_10_reg_2558_pp0_iter2_reg <= trunc_ln42_10_reg_2558;
        trunc_ln42_11_reg_2608 <= {{grp_fu_186_p2[25:10]}};
        trunc_ln42_12_reg_2613 <= {{grp_fu_184_p2[25:10]}};
        trunc_ln42_13_reg_2618 <= {{grp_fu_170_p2[25:10]}};
        trunc_ln42_14_reg_2623 <= {{grp_fu_169_p2[25:10]}};
        trunc_ln42_15_reg_2628 <= {{grp_fu_183_p2[25:10]}};
        trunc_ln42_16_reg_2633 <= {{grp_fu_178_p2[23:10]}};
        trunc_ln42_17_reg_2638 <= {{grp_fu_177_p2[25:10]}};
        trunc_ln42_18_reg_2643 <= {{grp_fu_171_p2[25:10]}};
        trunc_ln42_19_reg_2648 <= {{grp_fu_179_p2[25:10]}};
        trunc_ln42_1_reg_2508 <= {{grp_fu_168_p2[25:10]}};
        trunc_ln42_20_reg_2588 <= {{grp_fu_176_p2[24:10]}};
        trunc_ln42_21_reg_2593 <= {{grp_fu_182_p2[25:10]}};
        trunc_ln42_22_reg_2598 <= {{grp_fu_174_p2[25:10]}};
        trunc_ln42_2_reg_2513 <= {{grp_fu_185_p2[25:10]}};
        trunc_ln42_3_reg_2518 <= {{grp_fu_172_p2[24:10]}};
        trunc_ln42_4_reg_2523 <= {{grp_fu_166_p2[25:10]}};
        trunc_ln42_5_reg_2528 <= {{sub_ln42_fu_2039_p2[25:10]}};
        trunc_ln42_6_reg_2538 <= {{sub_ln42_2_fu_2059_p2[25:10]}};
        trunc_ln42_7_reg_2543 <= {{sub_ln73_fu_2096_p2[23:10]}};
        trunc_ln42_8_reg_2603 <= {{grp_fu_188_p2[25:10]}};
        trunc_ln42_9_reg_2548 <= {{grp_fu_189_p2[25:10]}};
        trunc_ln42_s_reg_2553 <= {{grp_fu_167_p2[24:10]}};
        trunc_ln_reg_2503 <= {{grp_fu_187_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln58_7_fu_2400_p2;
        ap_return_1_int_reg <= add_ln58_15_fu_2404_p2;
        ap_return_2_int_reg <= add_ln58_23_fu_2408_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_val_int_reg <= data_0_val;
        data_1_val_int_reg <= data_1_val;
        data_2_val_int_reg <= data_2_val;
        data_3_val_int_reg <= data_3_val;
        data_4_val_int_reg <= data_4_val;
        data_5_val_int_reg <= data_5_val;
        data_6_val_int_reg <= data_6_val;
        data_7_val_int_reg <= data_7_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln58_7_fu_2400_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln58_15_fu_2404_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln58_23_fu_2408_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_166_ce = 1'b1;
    end else begin
        grp_fu_166_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_167_ce = 1'b1;
    end else begin
        grp_fu_167_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_168_ce = 1'b1;
    end else begin
        grp_fu_168_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_169_ce = 1'b1;
    end else begin
        grp_fu_169_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_170_ce = 1'b1;
    end else begin
        grp_fu_170_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_171_ce = 1'b1;
    end else begin
        grp_fu_171_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_172_ce = 1'b1;
    end else begin
        grp_fu_172_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_174_ce = 1'b1;
    end else begin
        grp_fu_174_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_176_ce = 1'b1;
    end else begin
        grp_fu_176_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_177_ce = 1'b1;
    end else begin
        grp_fu_177_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_178_ce = 1'b1;
    end else begin
        grp_fu_178_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_179_ce = 1'b1;
    end else begin
        grp_fu_179_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_181_ce = 1'b1;
    end else begin
        grp_fu_181_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_182_ce = 1'b1;
    end else begin
        grp_fu_182_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_183_ce = 1'b1;
    end else begin
        grp_fu_183_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_184_ce = 1'b1;
    end else begin
        grp_fu_184_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_185_ce = 1'b1;
    end else begin
        grp_fu_185_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_186_ce = 1'b1;
    end else begin
        grp_fu_186_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_187_ce = 1'b1;
    end else begin
        grp_fu_187_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_188_ce = 1'b1;
    end else begin
        grp_fu_188_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_189_ce = 1'b1;
    end else begin
        grp_fu_189_ce = 1'b0;
    end
end

assign add_ln58_10_fu_2359_p2 = (add_ln58_9_reg_2673 + add_ln58_8_reg_2668);

assign add_ln58_11_fu_2363_p2 = (trunc_ln42_12_reg_2613 + trunc_ln42_15_reg_2628);

assign add_ln58_12_fu_2330_p2 = (trunc_ln42_21_reg_2593 + 16'd436);

assign add_ln58_13_fu_2367_p2 = (add_ln58_12_reg_2678 + trunc_ln42_18_reg_2643);

assign add_ln58_14_fu_2388_p2 = (add_ln58_13_reg_2718 + add_ln58_11_reg_2713);

assign add_ln58_15_fu_2404_p2 = (add_ln58_14_reg_2743 + add_ln58_10_reg_2708_pp0_iter4_reg);

assign add_ln58_16_fu_2335_p2 = (trunc_ln42_2_reg_2513 + trunc_ln42_5_reg_2528);

assign add_ln58_17_fu_2371_p2 = (trunc_ln42_8_reg_2603 + trunc_ln42_10_reg_2558_pp0_iter2_reg);

assign add_ln58_18_fu_2392_p2 = (add_ln58_17_reg_2723 + add_ln58_16_reg_2683_pp0_iter3_reg);

assign add_ln58_19_fu_2375_p2 = ($signed(trunc_ln42_13_reg_2618) + $signed(sext_ln42_6_fu_2344_p1));

assign add_ln58_1_fu_2310_p2 = (trunc_ln42_6_reg_2538 + trunc_ln42_9_reg_2548);

assign add_ln58_20_fu_2339_p2 = (trunc_ln42_22_reg_2598 + 16'd163);

assign add_ln58_21_fu_2380_p2 = (add_ln58_20_reg_2688 + trunc_ln42_19_reg_2648);

assign add_ln58_22_fu_2396_p2 = (add_ln58_21_reg_2733 + add_ln58_19_reg_2728);

assign add_ln58_23_fu_2408_p2 = (add_ln58_22_reg_2753 + add_ln58_18_reg_2748);

assign add_ln58_2_fu_2347_p2 = (add_ln58_1_reg_2658 + add_ln58_reg_2653);

assign add_ln58_3_fu_2351_p2 = (trunc_ln42_11_reg_2608 + trunc_ln42_14_reg_2623);

assign add_ln58_4_fu_2314_p2 = ($signed(sext_ln42_8_fu_2302_p1) + $signed(16'd64933));

assign add_ln58_5_fu_2355_p2 = (add_ln58_4_reg_2663 + trunc_ln42_17_reg_2638);

assign add_ln58_6_fu_2384_p2 = (add_ln58_5_reg_2703 + add_ln58_3_reg_2698);

assign add_ln58_7_fu_2400_p2 = (add_ln58_6_reg_2738 + add_ln58_2_reg_2693_pp0_iter4_reg);

assign add_ln58_8_fu_2320_p2 = (trunc_ln42_1_reg_2508 + trunc_ln42_4_reg_2523);

assign add_ln58_9_fu_2324_p2 = ($signed(sext_ln42_2_fu_2196_p1) + $signed(sext_ln42_4_fu_2209_p1));

assign add_ln58_fu_2305_p2 = ($signed(trunc_ln_reg_2503) + $signed(sext_ln42_1_fu_2193_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_166_p1 = 26'd67107636;

assign grp_fu_167_p1 = 25'd33554282;

assign grp_fu_168_p0 = sext_ln70_fu_1914_p1;

assign grp_fu_168_p1 = 26'd67107714;

assign grp_fu_169_p0 = sext_ln70_5_fu_2152_p1;

assign grp_fu_169_p1 = 26'd67108370;

assign grp_fu_170_p0 = sext_ln42_5_fu_2142_p1;

assign grp_fu_170_p1 = 26'd67108531;

assign grp_fu_171_p0 = sext_ln70_6_fu_2157_p1;

assign grp_fu_171_p1 = 26'd67107773;

assign grp_fu_172_p1 = 25'd33554294;

assign grp_fu_174_p0 = sext_ln42_7_fu_1960_p1;

assign grp_fu_174_p1 = 26'd67108163;

assign grp_fu_176_p1 = 25'd33554276;

assign grp_fu_177_p0 = sext_ln70_6_fu_2157_p1;

assign grp_fu_177_p1 = 26'd1014;

assign grp_fu_178_p1 = 24'd16777121;

assign grp_fu_179_p0 = sext_ln70_6_fu_2157_p1;

assign grp_fu_179_p1 = 26'd67108489;

assign grp_fu_181_p0 = sext_ln42_3_fu_1949_p1;

assign grp_fu_181_p1 = 26'd1342;

assign grp_fu_182_p0 = sext_ln42_7_fu_1960_p1;

assign grp_fu_182_p1 = 26'd1648;

assign grp_fu_183_p0 = sext_ln70_5_fu_2152_p1;

assign grp_fu_183_p1 = 26'd437;

assign grp_fu_184_p0 = sext_ln42_5_fu_2142_p1;

assign grp_fu_184_p1 = 26'd577;

assign grp_fu_185_p0 = sext_ln70_fu_1914_p1;

assign grp_fu_185_p1 = 26'd67108359;

assign grp_fu_186_p0 = sext_ln42_5_fu_2142_p1;

assign grp_fu_186_p1 = 26'd67108477;

assign grp_fu_187_p0 = sext_ln70_fu_1914_p1;

assign grp_fu_187_p1 = 26'd1144;

assign grp_fu_188_p0 = sext_ln70_2_fu_2055_p1;

assign grp_fu_188_p1 = 26'd67108406;

assign grp_fu_189_p0 = sext_ln42_3_fu_1949_p1;

assign grp_fu_189_p1 = 26'd67107922;

assign p_shl1_fu_2021_p3 = {{data_1_val_read_reg_2453}, {10'd0}};

assign sext_ln42_10_fu_1939_p1 = $signed(tmp_1_fu_1931_p3);

assign sext_ln42_1_fu_2193_p1 = $signed(trunc_ln42_3_reg_2518);

assign sext_ln42_2_fu_2196_p1 = $signed(trunc_ln42_7_reg_2543);

assign sext_ln42_3_fu_1949_p0 = data_3_val_int_reg;

assign sext_ln42_3_fu_1949_p1 = sext_ln42_3_fu_1949_p0;

assign sext_ln42_4_fu_2209_p1 = $signed(trunc_ln42_s_reg_2553);

assign sext_ln42_5_fu_2142_p1 = $signed(data_4_val_read_reg_2441);

assign sext_ln42_6_fu_2344_p1 = $signed(trunc_ln42_16_reg_2633);

assign sext_ln42_7_fu_1960_p0 = data_7_val_int_reg;

assign sext_ln42_7_fu_1960_p1 = sext_ln42_7_fu_1960_p0;

assign sext_ln42_8_fu_2302_p1 = $signed(trunc_ln42_20_reg_2588);

assign sext_ln42_9_fu_2035_p1 = $signed(tmp_fu_2028_p3);

assign sext_ln42_fu_1921_p0 = data_1_val_int_reg;

assign sext_ln70_1_fu_1926_p0 = data_1_val_int_reg;

assign sext_ln70_2_fu_2055_p1 = data_2_val_read_reg_2446;

assign sext_ln70_3_fu_1955_p0 = data_3_val_int_reg;

assign sext_ln70_5_fu_2152_p1 = data_5_val_read_reg_2435;

assign sext_ln70_6_fu_2157_p1 = $signed(data_6_val_read_reg_2430);

assign sext_ln70_7_fu_1966_p0 = data_7_val_int_reg;

assign sext_ln70_fu_1914_p1 = $signed(data_0_val_int_reg);

assign sext_ln73_1_fu_2092_p1 = $signed(tmp_3_fu_2085_p3);

assign sext_ln73_fu_2081_p1 = $signed(tmp_2_fu_2074_p3);

assign sub_ln42_1_fu_1943_p2 = ($signed(26'd0) - $signed(sext_ln42_10_fu_1939_p1));

assign sub_ln42_2_fu_2059_p2 = ($signed(sub_ln42_1_reg_2476) - $signed(sext_ln70_2_fu_2055_p1));

assign sub_ln42_fu_2039_p2 = ($signed(sext_ln42_9_fu_2035_p1) - $signed(p_shl1_fu_2021_p3));

assign sub_ln73_fu_2096_p2 = ($signed(sext_ln73_1_fu_2092_p1) - $signed(sext_ln73_fu_2081_p1));

assign tmp_1_fu_1931_p1 = data_2_val_int_reg;

assign tmp_1_fu_1931_p3 = {{tmp_1_fu_1931_p1}, {9'd0}};

assign tmp_2_fu_2074_p3 = {{data_2_val_read_reg_2446}, {7'd0}};

assign tmp_3_fu_2085_p3 = {{data_2_val_read_reg_2446}, {1'd0}};

assign tmp_fu_2028_p3 = {{data_1_val_read_reg_2453}, {3'd0}};

always @ (posedge ap_clk) begin
    sub_ln42_1_reg_2476[8:0] <= 9'b000000000;
end

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
