// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        data_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [63:0] data_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;

wire  signed [15:0] a_fu_3525_p1;
reg  signed [15:0] a_reg_4206;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] a_reg_4206_pp0_iter1_reg;
reg  signed [15:0] a_2_reg_4214;
reg   [13:0] trunc_ln42_94_reg_4220;
reg   [13:0] trunc_ln42_94_reg_4220_pp0_iter1_reg;
reg   [13:0] trunc_ln42_94_reg_4220_pp0_iter2_reg;
reg  signed [15:0] a_3_reg_4225;
wire  signed [25:0] sext_ln42_34_fu_3608_p1;
wire  signed [25:0] sext_ln70_22_fu_3623_p1;
wire   [25:0] sub_ln73_fu_3643_p2;
reg   [25:0] sub_ln73_reg_4262;
wire  signed [25:0] sext_ln70_24_fu_3653_p1;
wire  signed [25:0] sext_ln70_25_fu_3662_p1;
reg   [15:0] trunc_ln42_107_reg_4298;
reg   [15:0] trunc_ln42_108_reg_4303;
reg   [15:0] trunc_ln42_109_reg_4308;
reg   [15:0] trunc_ln42_110_reg_4313;
reg   [15:0] trunc_ln42_111_reg_4318;
reg   [15:0] trunc_ln42_112_reg_4323;
reg   [14:0] trunc_ln42_113_reg_4328;
reg   [15:0] trunc_ln42_114_reg_4333;
reg   [15:0] trunc_ln_reg_4338;
reg   [15:0] trunc_ln42_s_reg_4343;
reg   [15:0] trunc_ln42_85_reg_4348;
reg   [15:0] trunc_ln42_86_reg_4353;
reg   [13:0] trunc_ln42_87_reg_4358;
reg   [15:0] trunc_ln42_88_reg_4363;
reg   [15:0] trunc_ln42_89_reg_4368;
reg   [15:0] trunc_ln42_90_reg_4373;
reg   [15:0] trunc_ln42_91_reg_4378;
reg   [15:0] trunc_ln42_92_reg_4383;
reg   [15:0] trunc_ln42_93_reg_4388;
reg   [15:0] trunc_ln42_95_reg_4393;
reg   [15:0] trunc_ln42_96_reg_4398;
reg   [14:0] trunc_ln42_97_reg_4403;
reg   [15:0] trunc_ln42_98_reg_4408;
reg   [15:0] trunc_ln42_99_reg_4413;
reg   [15:0] trunc_ln42_100_reg_4418;
reg   [14:0] trunc_ln42_101_reg_4423;
reg   [15:0] trunc_ln42_102_reg_4428;
reg   [15:0] trunc_ln42_103_reg_4433;
reg   [15:0] trunc_ln42_104_reg_4438;
reg   [15:0] trunc_ln42_105_reg_4443;
reg   [15:0] trunc_ln42_106_reg_4448;
wire   [15:0] add_ln58_87_fu_4005_p2;
reg   [15:0] add_ln58_87_reg_4453;
wire   [15:0] add_ln58_91_fu_4010_p2;
reg   [15:0] add_ln58_91_reg_4458;
wire   [15:0] add_ln58_95_fu_4015_p2;
reg   [15:0] add_ln58_95_reg_4463;
wire   [15:0] add_ln58_99_fu_4020_p2;
reg   [15:0] add_ln58_99_reg_4468;
wire   [15:0] add_ln58_103_fu_4025_p2;
reg   [15:0] add_ln58_103_reg_4473;
wire   [15:0] add_ln58_107_fu_4030_p2;
reg   [15:0] add_ln58_107_reg_4478;
wire   [15:0] add_ln58_111_fu_4035_p2;
reg   [15:0] add_ln58_111_reg_4483;
wire   [15:0] add_ln58_115_fu_4041_p2;
reg   [15:0] add_ln58_115_reg_4488;
wire   [15:0] add_ln58_fu_4058_p2;
reg   [15:0] add_ln58_reg_4493;
wire   [15:0] add_ln58_88_fu_4062_p2;
reg   [15:0] add_ln58_88_reg_4498;
wire   [15:0] add_ln58_90_fu_4066_p2;
reg   [15:0] add_ln58_90_reg_4503;
wire   [15:0] add_ln58_92_fu_4070_p2;
reg   [15:0] add_ln58_92_reg_4508;
wire   [15:0] add_ln58_94_fu_4074_p2;
reg   [15:0] add_ln58_94_reg_4513;
wire   [15:0] add_ln58_96_fu_4078_p2;
reg   [15:0] add_ln58_96_reg_4518;
wire   [15:0] add_ln58_98_fu_4083_p2;
reg   [15:0] add_ln58_98_reg_4523;
wire   [15:0] add_ln58_100_fu_4088_p2;
reg   [15:0] add_ln58_100_reg_4528;
wire   [15:0] add_ln58_102_fu_4092_p2;
reg   [15:0] add_ln58_102_reg_4533;
wire   [15:0] add_ln58_104_fu_4097_p2;
reg   [15:0] add_ln58_104_reg_4538;
wire   [15:0] add_ln58_106_fu_4101_p2;
reg   [15:0] add_ln58_106_reg_4543;
wire   [15:0] add_ln58_108_fu_4105_p2;
reg   [15:0] add_ln58_108_reg_4548;
wire   [15:0] add_ln58_110_fu_4109_p2;
reg   [15:0] add_ln58_110_reg_4553;
wire   [15:0] add_ln58_112_fu_4114_p2;
reg   [15:0] add_ln58_112_reg_4558;
wire   [15:0] add_ln58_114_fu_4118_p2;
reg   [15:0] add_ln58_114_reg_4563;
wire   [15:0] add_ln58_116_fu_4122_p2;
reg   [15:0] add_ln58_116_reg_4568;
wire  signed [15:0] grp_fu_146_p0;
wire  signed [11:0] grp_fu_146_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] grp_fu_147_p0;
wire   [11:0] grp_fu_147_p1;
wire  signed [15:0] grp_fu_148_p0;
wire   [10:0] grp_fu_148_p1;
wire  signed [15:0] grp_fu_149_p0;
wire   [9:0] grp_fu_149_p1;
wire  signed [15:0] grp_fu_150_p0;
wire   [9:0] grp_fu_150_p1;
wire  signed [15:0] grp_fu_151_p0;
wire  signed [9:0] grp_fu_151_p1;
wire  signed [15:0] grp_fu_152_p0;
wire  signed [10:0] grp_fu_152_p1;
wire  signed [15:0] grp_fu_153_p0;
wire   [10:0] grp_fu_153_p1;
wire  signed [15:0] grp_fu_154_p0;
wire   [9:0] grp_fu_154_p1;
wire  signed [15:0] grp_fu_155_p0;
wire  signed [9:0] grp_fu_155_p1;
wire   [8:0] grp_fu_156_p1;
wire  signed [15:0] grp_fu_157_p0;
wire   [9:0] grp_fu_157_p1;
wire  signed [15:0] grp_fu_159_p0;
wire   [10:0] grp_fu_159_p1;
wire  signed [15:0] grp_fu_160_p0;
wire  signed [10:0] grp_fu_160_p1;
wire  signed [15:0] grp_fu_161_p0;
wire  signed [9:0] grp_fu_161_p1;
wire  signed [15:0] grp_fu_162_p0;
wire  signed [11:0] grp_fu_162_p1;
wire  signed [8:0] grp_fu_163_p1;
wire  signed [15:0] grp_fu_164_p0;
wire   [10:0] grp_fu_164_p1;
wire  signed [15:0] grp_fu_165_p0;
wire  signed [9:0] grp_fu_165_p1;
wire  signed [15:0] grp_fu_166_p0;
wire  signed [10:0] grp_fu_166_p1;
wire  signed [15:0] grp_fu_167_p0;
wire   [9:0] grp_fu_167_p1;
wire  signed [15:0] grp_fu_168_p0;
wire  signed [10:0] grp_fu_168_p1;
wire   [8:0] grp_fu_169_p1;
wire  signed [15:0] grp_fu_170_p0;
wire   [10:0] grp_fu_170_p1;
wire  signed [15:0] grp_fu_171_p0;
wire  signed [9:0] grp_fu_171_p1;
wire  signed [15:0] grp_fu_172_p0;
wire  signed [10:0] grp_fu_172_p1;
wire  signed [15:0] grp_fu_173_p0;
wire  signed [10:0] grp_fu_173_p1;
wire  signed [15:0] grp_fu_174_p0;
wire  signed [10:0] grp_fu_174_p1;
wire   [7:0] grp_fu_176_p1;
wire  signed [15:0] grp_fu_177_p0;
wire   [10:0] grp_fu_177_p1;
wire   [15:0] tmp_16_fu_3537_p4;
wire   [22:0] tmp_17_fu_3547_p3;
wire   [18:0] tmp_18_fu_3559_p3;
wire  signed [23:0] sext_ln73_17_fu_3567_p1;
wire  signed [23:0] sext_ln73_16_fu_3555_p1;
wire   [23:0] sub_ln73_7_fu_3571_p2;
wire  signed [15:0] a_4_fu_3595_p3;
wire   [23:0] tmp_fu_3632_p3;
wire  signed [25:0] sext_ln73_fu_3639_p1;
wire   [25:0] grp_fu_151_p2;
wire   [25:0] grp_fu_154_p2;
wire   [25:0] grp_fu_167_p2;
wire   [25:0] grp_fu_162_p2;
wire   [25:0] grp_fu_173_p2;
wire   [25:0] grp_fu_146_p2;
wire   [24:0] grp_fu_156_p2;
wire   [25:0] grp_fu_147_p2;
wire   [17:0] tmp_15_fu_3756_p3;
wire  signed [25:0] sext_ln73_15_fu_3763_p1;
wire   [25:0] sub_ln73_6_fu_3767_p2;
wire   [25:0] grp_fu_166_p2;
wire   [25:0] grp_fu_165_p2;
wire   [25:0] grp_fu_152_p2;
wire   [23:0] grp_fu_176_p2;
wire   [25:0] grp_fu_170_p2;
wire   [25:0] grp_fu_148_p2;
wire   [25:0] grp_fu_164_p2;
wire   [25:0] grp_fu_177_p2;
wire   [25:0] grp_fu_159_p2;
wire   [25:0] grp_fu_157_p2;
wire   [25:0] grp_fu_150_p2;
wire   [25:0] grp_fu_160_p2;
wire   [24:0] grp_fu_169_p2;
wire   [25:0] grp_fu_171_p2;
wire   [25:0] grp_fu_172_p2;
wire   [25:0] grp_fu_168_p2;
wire   [24:0] grp_fu_163_p2;
wire   [25:0] grp_fu_174_p2;
wire   [25:0] grp_fu_161_p2;
wire   [25:0] grp_fu_155_p2;
wire   [25:0] grp_fu_149_p2;
wire   [25:0] grp_fu_153_p2;
wire  signed [15:0] sext_ln42_35_fu_4002_p1;
wire  signed [15:0] sext_ln42_33_fu_4055_p1;
wire  signed [15:0] sext_ln42_31_fu_4049_p1;
wire  signed [15:0] sext_ln42_fu_4046_p1;
wire  signed [15:0] sext_ln42_32_fu_4052_p1;
wire   [15:0] add_ln58_89_fu_4126_p2;
wire   [15:0] add_ln58_93_fu_4130_p2;
wire   [15:0] add_ln58_97_fu_4134_p2;
wire   [15:0] add_ln58_101_fu_4138_p2;
wire   [15:0] add_ln58_105_fu_4142_p2;
wire   [15:0] add_ln58_109_fu_4146_p2;
wire   [15:0] add_ln58_113_fu_4150_p2;
wire   [15:0] add_ln58_117_fu_4154_p2;
reg    grp_fu_146_ce;
reg    grp_fu_147_ce;
reg    grp_fu_148_ce;
reg    grp_fu_149_ce;
reg    grp_fu_150_ce;
reg    grp_fu_151_ce;
reg    grp_fu_152_ce;
reg    grp_fu_153_ce;
reg    grp_fu_154_ce;
reg    grp_fu_155_ce;
reg    grp_fu_156_ce;
reg    grp_fu_157_ce;
reg    grp_fu_159_ce;
reg    grp_fu_160_ce;
reg    grp_fu_161_ce;
reg    grp_fu_162_ce;
reg    grp_fu_163_ce;
reg    grp_fu_164_ce;
reg    grp_fu_165_ce;
reg    grp_fu_166_ce;
reg    grp_fu_167_ce;
reg    grp_fu_168_ce;
reg    grp_fu_169_ce;
reg    grp_fu_170_ce;
reg    grp_fu_171_ce;
reg    grp_fu_172_ce;
reg    grp_fu_173_ce;
reg    grp_fu_174_ce;
reg    grp_fu_176_ce;
reg    grp_fu_177_ce;
reg    ap_ce_reg;
reg   [63:0] data_val_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_146_p0),
    .din1(grp_fu_146_p1),
    .ce(grp_fu_146_ce),
    .dout(grp_fu_146_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_147_p0),
    .din1(grp_fu_147_p1),
    .ce(grp_fu_147_ce),
    .dout(grp_fu_147_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_148_p0),
    .din1(grp_fu_148_p1),
    .ce(grp_fu_148_ce),
    .dout(grp_fu_148_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_149_p0),
    .din1(grp_fu_149_p1),
    .ce(grp_fu_149_ce),
    .dout(grp_fu_149_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_150_p0),
    .din1(grp_fu_150_p1),
    .ce(grp_fu_150_ce),
    .dout(grp_fu_150_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_151_p0),
    .din1(grp_fu_151_p1),
    .ce(grp_fu_151_ce),
    .dout(grp_fu_151_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_152_p0),
    .din1(grp_fu_152_p1),
    .ce(grp_fu_152_ce),
    .dout(grp_fu_152_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_153_p0),
    .din1(grp_fu_153_p1),
    .ce(grp_fu_153_ce),
    .dout(grp_fu_153_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_154_p0),
    .din1(grp_fu_154_p1),
    .ce(grp_fu_154_ce),
    .dout(grp_fu_154_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_155_p0),
    .din1(grp_fu_155_p1),
    .ce(grp_fu_155_ce),
    .dout(grp_fu_155_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_2_0_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_4_fu_3595_p3),
    .din1(grp_fu_156_p1),
    .ce(grp_fu_156_ce),
    .dout(grp_fu_156_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_157_p0),
    .din1(grp_fu_157_p1),
    .ce(grp_fu_157_ce),
    .dout(grp_fu_157_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_159_p0),
    .din1(grp_fu_159_p1),
    .ce(grp_fu_159_ce),
    .dout(grp_fu_159_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_160_p0),
    .din1(grp_fu_160_p1),
    .ce(grp_fu_160_ce),
    .dout(grp_fu_160_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_161_p0),
    .din1(grp_fu_161_p1),
    .ce(grp_fu_161_ce),
    .dout(grp_fu_161_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_162_p0),
    .din1(grp_fu_162_p1),
    .ce(grp_fu_162_ce),
    .dout(grp_fu_162_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_3_reg_4225),
    .din1(grp_fu_163_p1),
    .ce(grp_fu_163_ce),
    .dout(grp_fu_163_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_164_p0),
    .din1(grp_fu_164_p1),
    .ce(grp_fu_164_ce),
    .dout(grp_fu_164_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_165_p0),
    .din1(grp_fu_165_p1),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_166_p0),
    .din1(grp_fu_166_p1),
    .ce(grp_fu_166_ce),
    .dout(grp_fu_166_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_0_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_167_p0),
    .din1(grp_fu_167_p1),
    .ce(grp_fu_167_ce),
    .dout(grp_fu_167_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_168_p0),
    .din1(grp_fu_168_p1),
    .ce(grp_fu_168_ce),
    .dout(grp_fu_168_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_2_0_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_2_reg_4214),
    .din1(grp_fu_169_p1),
    .ce(grp_fu_169_ce),
    .dout(grp_fu_169_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_170_p0),
    .din1(grp_fu_170_p1),
    .ce(grp_fu_170_ce),
    .dout(grp_fu_170_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_171_p0),
    .din1(grp_fu_171_p1),
    .ce(grp_fu_171_ce),
    .dout(grp_fu_171_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_172_p0),
    .din1(grp_fu_172_p1),
    .ce(grp_fu_172_ce),
    .dout(grp_fu_172_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_173_p0),
    .din1(grp_fu_173_p1),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_174_p0),
    .din1(grp_fu_174_p1),
    .ce(grp_fu_174_ce),
    .dout(grp_fu_174_p2)
);

myproject_mul_16s_8ns_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_0_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_reg_4206),
    .din1(grp_fu_176_p1),
    .ce(grp_fu_176_ce),
    .dout(grp_fu_176_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_177_p0),
    .din1(grp_fu_177_p1),
    .ce(grp_fu_177_ce),
    .dout(grp_fu_177_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        a_2_reg_4214 <= {{data_val_int_reg[31:16]}};
        a_3_reg_4225 <= {{data_val_int_reg[47:32]}};
        a_reg_4206 <= a_fu_3525_p1;
        a_reg_4206_pp0_iter1_reg <= a_reg_4206;
        add_ln58_100_reg_4528 <= add_ln58_100_fu_4088_p2;
        add_ln58_102_reg_4533 <= add_ln58_102_fu_4092_p2;
        add_ln58_103_reg_4473 <= add_ln58_103_fu_4025_p2;
        add_ln58_104_reg_4538 <= add_ln58_104_fu_4097_p2;
        add_ln58_106_reg_4543 <= add_ln58_106_fu_4101_p2;
        add_ln58_107_reg_4478 <= add_ln58_107_fu_4030_p2;
        add_ln58_108_reg_4548 <= add_ln58_108_fu_4105_p2;
        add_ln58_110_reg_4553 <= add_ln58_110_fu_4109_p2;
        add_ln58_111_reg_4483 <= add_ln58_111_fu_4035_p2;
        add_ln58_112_reg_4558 <= add_ln58_112_fu_4114_p2;
        add_ln58_114_reg_4563 <= add_ln58_114_fu_4118_p2;
        add_ln58_115_reg_4488 <= add_ln58_115_fu_4041_p2;
        add_ln58_116_reg_4568 <= add_ln58_116_fu_4122_p2;
        add_ln58_87_reg_4453 <= add_ln58_87_fu_4005_p2;
        add_ln58_88_reg_4498 <= add_ln58_88_fu_4062_p2;
        add_ln58_90_reg_4503 <= add_ln58_90_fu_4066_p2;
        add_ln58_91_reg_4458 <= add_ln58_91_fu_4010_p2;
        add_ln58_92_reg_4508 <= add_ln58_92_fu_4070_p2;
        add_ln58_94_reg_4513 <= add_ln58_94_fu_4074_p2;
        add_ln58_95_reg_4463 <= add_ln58_95_fu_4015_p2;
        add_ln58_96_reg_4518 <= add_ln58_96_fu_4078_p2;
        add_ln58_98_reg_4523 <= add_ln58_98_fu_4083_p2;
        add_ln58_99_reg_4468 <= add_ln58_99_fu_4020_p2;
        add_ln58_reg_4493 <= add_ln58_fu_4058_p2;
        sub_ln73_reg_4262[25 : 8] <= sub_ln73_fu_3643_p2[25 : 8];
        trunc_ln42_100_reg_4418 <= {{grp_fu_168_p2[25:10]}};
        trunc_ln42_101_reg_4423 <= {{grp_fu_163_p2[24:10]}};
        trunc_ln42_102_reg_4428 <= {{grp_fu_174_p2[25:10]}};
        trunc_ln42_103_reg_4433 <= {{grp_fu_161_p2[25:10]}};
        trunc_ln42_104_reg_4438 <= {{grp_fu_155_p2[25:10]}};
        trunc_ln42_105_reg_4443 <= {{grp_fu_149_p2[25:10]}};
        trunc_ln42_106_reg_4448 <= {{grp_fu_153_p2[25:10]}};
        trunc_ln42_107_reg_4298 <= {{grp_fu_151_p2[25:10]}};
        trunc_ln42_108_reg_4303 <= {{grp_fu_154_p2[25:10]}};
        trunc_ln42_109_reg_4308 <= {{grp_fu_167_p2[25:10]}};
        trunc_ln42_110_reg_4313 <= {{grp_fu_162_p2[25:10]}};
        trunc_ln42_111_reg_4318 <= {{grp_fu_173_p2[25:10]}};
        trunc_ln42_112_reg_4323 <= {{grp_fu_146_p2[25:10]}};
        trunc_ln42_113_reg_4328 <= {{grp_fu_156_p2[24:10]}};
        trunc_ln42_114_reg_4333 <= {{grp_fu_147_p2[25:10]}};
        trunc_ln42_85_reg_4348 <= {{grp_fu_165_p2[25:10]}};
        trunc_ln42_86_reg_4353 <= {{grp_fu_152_p2[25:10]}};
        trunc_ln42_87_reg_4358 <= {{grp_fu_176_p2[23:10]}};
        trunc_ln42_88_reg_4363 <= {{grp_fu_170_p2[25:10]}};
        trunc_ln42_89_reg_4368 <= {{grp_fu_148_p2[25:10]}};
        trunc_ln42_90_reg_4373 <= {{grp_fu_164_p2[25:10]}};
        trunc_ln42_91_reg_4378 <= {{grp_fu_177_p2[25:10]}};
        trunc_ln42_92_reg_4383 <= {{grp_fu_159_p2[25:10]}};
        trunc_ln42_93_reg_4388 <= {{grp_fu_157_p2[25:10]}};
        trunc_ln42_94_reg_4220 <= {{sub_ln73_7_fu_3571_p2[23:10]}};
        trunc_ln42_94_reg_4220_pp0_iter1_reg <= trunc_ln42_94_reg_4220;
        trunc_ln42_94_reg_4220_pp0_iter2_reg <= trunc_ln42_94_reg_4220_pp0_iter1_reg;
        trunc_ln42_95_reg_4393 <= {{grp_fu_150_p2[25:10]}};
        trunc_ln42_96_reg_4398 <= {{grp_fu_160_p2[25:10]}};
        trunc_ln42_97_reg_4403 <= {{grp_fu_169_p2[24:10]}};
        trunc_ln42_98_reg_4408 <= {{grp_fu_171_p2[25:10]}};
        trunc_ln42_99_reg_4413 <= {{grp_fu_172_p2[25:10]}};
        trunc_ln42_s_reg_4343 <= {{grp_fu_166_p2[25:10]}};
        trunc_ln_reg_4338 <= {{sub_ln73_6_fu_3767_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln58_89_fu_4126_p2;
        ap_return_1_int_reg <= add_ln58_93_fu_4130_p2;
        ap_return_2_int_reg <= add_ln58_97_fu_4134_p2;
        ap_return_3_int_reg <= add_ln58_101_fu_4138_p2;
        ap_return_4_int_reg <= add_ln58_105_fu_4142_p2;
        ap_return_5_int_reg <= add_ln58_109_fu_4146_p2;
        ap_return_6_int_reg <= add_ln58_113_fu_4150_p2;
        ap_return_7_int_reg <= add_ln58_117_fu_4154_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_val_int_reg <= data_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln58_89_fu_4126_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln58_93_fu_4130_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln58_97_fu_4134_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln58_101_fu_4138_p2;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = add_ln58_105_fu_4142_p2;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = add_ln58_109_fu_4146_p2;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = add_ln58_113_fu_4150_p2;
    end else begin
        ap_return_6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = add_ln58_117_fu_4154_p2;
    end else begin
        ap_return_7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_146_ce = 1'b1;
    end else begin
        grp_fu_146_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_147_ce = 1'b1;
    end else begin
        grp_fu_147_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_148_ce = 1'b1;
    end else begin
        grp_fu_148_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_149_ce = 1'b1;
    end else begin
        grp_fu_149_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_150_ce = 1'b1;
    end else begin
        grp_fu_150_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_151_ce = 1'b1;
    end else begin
        grp_fu_151_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_152_ce = 1'b1;
    end else begin
        grp_fu_152_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_153_ce = 1'b1;
    end else begin
        grp_fu_153_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_154_ce = 1'b1;
    end else begin
        grp_fu_154_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_155_ce = 1'b1;
    end else begin
        grp_fu_155_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_156_ce = 1'b1;
    end else begin
        grp_fu_156_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_157_ce = 1'b1;
    end else begin
        grp_fu_157_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_159_ce = 1'b1;
    end else begin
        grp_fu_159_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_160_ce = 1'b1;
    end else begin
        grp_fu_160_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_161_ce = 1'b1;
    end else begin
        grp_fu_161_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_162_ce = 1'b1;
    end else begin
        grp_fu_162_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_163_ce = 1'b1;
    end else begin
        grp_fu_163_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_164_ce = 1'b1;
    end else begin
        grp_fu_164_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_165_ce = 1'b1;
    end else begin
        grp_fu_165_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_166_ce = 1'b1;
    end else begin
        grp_fu_166_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_167_ce = 1'b1;
    end else begin
        grp_fu_167_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_168_ce = 1'b1;
    end else begin
        grp_fu_168_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_169_ce = 1'b1;
    end else begin
        grp_fu_169_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_170_ce = 1'b1;
    end else begin
        grp_fu_170_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_171_ce = 1'b1;
    end else begin
        grp_fu_171_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_172_ce = 1'b1;
    end else begin
        grp_fu_172_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_173_ce = 1'b1;
    end else begin
        grp_fu_173_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_174_ce = 1'b1;
    end else begin
        grp_fu_174_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_176_ce = 1'b1;
    end else begin
        grp_fu_176_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_177_ce = 1'b1;
    end else begin
        grp_fu_177_ce = 1'b0;
    end
end

assign a_4_fu_3595_p3 = {{data_val_int_reg[63:48]}};

assign a_fu_3525_p1 = data_val_int_reg[15:0];

assign add_ln58_100_fu_4088_p2 = (add_ln58_99_reg_4468 + trunc_ln42_102_reg_4428);

assign add_ln58_101_fu_4138_p2 = (add_ln58_100_reg_4528 + add_ln58_98_reg_4523);

assign add_ln58_102_fu_4092_p2 = ($signed(sext_ln42_fu_4046_p1) + $signed(trunc_ln42_95_reg_4393));

assign add_ln58_103_fu_4025_p2 = (trunc_ln42_111_reg_4318 + 16'd988);

assign add_ln58_104_fu_4097_p2 = (add_ln58_103_reg_4473 + trunc_ln42_103_reg_4433);

assign add_ln58_105_fu_4142_p2 = (add_ln58_104_reg_4538 + add_ln58_102_reg_4533);

assign add_ln58_106_fu_4101_p2 = (trunc_ln42_88_reg_4363 + trunc_ln42_96_reg_4398);

assign add_ln58_107_fu_4030_p2 = (trunc_ln42_112_reg_4323 + 16'd927);

assign add_ln58_108_fu_4105_p2 = (add_ln58_107_reg_4478 + trunc_ln42_104_reg_4438);

assign add_ln58_109_fu_4146_p2 = (add_ln58_108_reg_4548 + add_ln58_106_reg_4543);

assign add_ln58_110_fu_4109_p2 = ($signed(trunc_ln42_89_reg_4368) + $signed(sext_ln42_32_fu_4052_p1));

assign add_ln58_111_fu_4035_p2 = ($signed(sext_ln42_35_fu_4002_p1) + $signed(16'd763));

assign add_ln58_112_fu_4114_p2 = (add_ln58_111_reg_4483 + trunc_ln42_105_reg_4443);

assign add_ln58_113_fu_4150_p2 = (add_ln58_112_reg_4558 + add_ln58_110_reg_4553);

assign add_ln58_114_fu_4118_p2 = (trunc_ln42_90_reg_4373 + trunc_ln42_98_reg_4408);

assign add_ln58_115_fu_4041_p2 = (trunc_ln42_114_reg_4333 + 16'd176);

assign add_ln58_116_fu_4122_p2 = (add_ln58_115_reg_4488 + trunc_ln42_106_reg_4448);

assign add_ln58_117_fu_4154_p2 = (add_ln58_116_reg_4568 + add_ln58_114_reg_4563);

assign add_ln58_87_fu_4005_p2 = (trunc_ln42_107_reg_4298 + 16'd160);

assign add_ln58_88_fu_4062_p2 = (add_ln58_87_reg_4453 + trunc_ln42_99_reg_4413);

assign add_ln58_89_fu_4126_p2 = (add_ln58_88_reg_4498 + add_ln58_reg_4493);

assign add_ln58_90_fu_4066_p2 = (trunc_ln42_s_reg_4343 + trunc_ln42_92_reg_4383);

assign add_ln58_91_fu_4010_p2 = (trunc_ln42_108_reg_4303 + 16'd530);

assign add_ln58_92_fu_4070_p2 = (add_ln58_91_reg_4458 + trunc_ln42_100_reg_4418);

assign add_ln58_93_fu_4130_p2 = (add_ln58_92_reg_4508 + add_ln58_90_reg_4503);

assign add_ln58_94_fu_4074_p2 = (trunc_ln42_85_reg_4348 + trunc_ln42_93_reg_4388);

assign add_ln58_95_fu_4015_p2 = ($signed(trunc_ln42_109_reg_4308) + $signed(16'd65214));

assign add_ln58_96_fu_4078_p2 = ($signed(add_ln58_95_reg_4463) + $signed(sext_ln42_33_fu_4055_p1));

assign add_ln58_97_fu_4134_p2 = (add_ln58_96_reg_4518 + add_ln58_94_reg_4513);

assign add_ln58_98_fu_4083_p2 = ($signed(trunc_ln42_86_reg_4353) + $signed(sext_ln42_31_fu_4049_p1));

assign add_ln58_99_fu_4020_p2 = (trunc_ln42_110_reg_4313 + 16'd218);

assign add_ln58_fu_4058_p2 = (trunc_ln_reg_4338 + trunc_ln42_91_reg_4378);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_146_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_146_p1 = 26'd67107748;

assign grp_fu_147_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_147_p1 = 26'd1519;

assign grp_fu_148_p0 = sext_ln70_22_fu_3623_p1;

assign grp_fu_148_p1 = 26'd937;

assign grp_fu_149_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_149_p1 = 26'd478;

assign grp_fu_150_p0 = sext_ln70_24_fu_3653_p1;

assign grp_fu_150_p1 = 26'd266;

assign grp_fu_151_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_151_p1 = 26'd67108587;

assign grp_fu_152_p0 = sext_ln70_22_fu_3623_p1;

assign grp_fu_152_p1 = 26'd67108254;

assign grp_fu_153_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_153_p1 = 26'd748;

assign grp_fu_154_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_154_p1 = 26'd292;

assign grp_fu_155_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_155_p1 = 26'd67108504;

assign grp_fu_156_p1 = 25'd246;

assign grp_fu_157_p0 = sext_ln70_24_fu_3653_p1;

assign grp_fu_157_p1 = 26'd453;

assign grp_fu_159_p0 = sext_ln70_24_fu_3653_p1;

assign grp_fu_159_p1 = 26'd993;

assign grp_fu_160_p0 = sext_ln70_24_fu_3653_p1;

assign grp_fu_160_p1 = 26'd67108087;

assign grp_fu_161_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_161_p1 = 26'd67108584;

assign grp_fu_162_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_162_p1 = 26'd67107649;

assign grp_fu_163_p1 = 25'd33554181;

assign grp_fu_164_p0 = sext_ln70_22_fu_3623_p1;

assign grp_fu_164_p1 = 26'd534;

assign grp_fu_165_p0 = sext_ln70_22_fu_3623_p1;

assign grp_fu_165_p1 = 26'd67108533;

assign grp_fu_166_p0 = sext_ln70_22_fu_3623_p1;

assign grp_fu_166_p1 = 26'd67108215;

assign grp_fu_167_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_167_p1 = 26'd415;

assign grp_fu_168_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_168_p1 = 26'd67108283;

assign grp_fu_169_p1 = 25'd139;

assign grp_fu_170_p0 = sext_ln70_22_fu_3623_p1;

assign grp_fu_170_p1 = 26'd643;

assign grp_fu_171_p0 = sext_ln70_24_fu_3653_p1;

assign grp_fu_171_p1 = 26'd67108408;

assign grp_fu_172_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_172_p1 = 26'd67108094;

assign grp_fu_173_p0 = sext_ln42_34_fu_3608_p1;

assign grp_fu_173_p1 = 26'd67108187;

assign grp_fu_174_p0 = sext_ln70_25_fu_3662_p1;

assign grp_fu_174_p1 = 26'd67107900;

assign grp_fu_176_p1 = 24'd75;

assign grp_fu_177_p0 = sext_ln70_24_fu_3653_p1;

assign grp_fu_177_p1 = 26'd572;

assign sext_ln42_31_fu_4049_p1 = $signed(trunc_ln42_94_reg_4220_pp0_iter2_reg);

assign sext_ln42_32_fu_4052_p1 = $signed(trunc_ln42_97_reg_4403);

assign sext_ln42_33_fu_4055_p1 = $signed(trunc_ln42_101_reg_4423);

assign sext_ln42_34_fu_3608_p1 = a_4_fu_3595_p3;

assign sext_ln42_35_fu_4002_p1 = $signed(trunc_ln42_113_reg_4328);

assign sext_ln42_fu_4046_p1 = $signed(trunc_ln42_87_reg_4358);

assign sext_ln70_22_fu_3623_p1 = a_reg_4206;

assign sext_ln70_24_fu_3653_p1 = a_2_reg_4214;

assign sext_ln70_25_fu_3662_p1 = a_3_reg_4225;

assign sext_ln73_15_fu_3763_p1 = $signed(tmp_15_fu_3756_p3);

assign sext_ln73_16_fu_3555_p1 = $signed(tmp_17_fu_3547_p3);

assign sext_ln73_17_fu_3567_p1 = $signed(tmp_18_fu_3559_p3);

assign sext_ln73_fu_3639_p1 = $signed(tmp_fu_3632_p3);

assign sub_ln73_6_fu_3767_p2 = ($signed(sub_ln73_reg_4262) - $signed(sext_ln73_15_fu_3763_p1));

assign sub_ln73_7_fu_3571_p2 = ($signed(sext_ln73_17_fu_3567_p1) - $signed(sext_ln73_16_fu_3555_p1));

assign sub_ln73_fu_3643_p2 = ($signed(26'd0) - $signed(sext_ln73_fu_3639_p1));

assign tmp_15_fu_3756_p3 = {{a_reg_4206_pp0_iter1_reg}, {2'd0}};

assign tmp_16_fu_3537_p4 = {{data_val_int_reg[31:16]}};

assign tmp_17_fu_3547_p3 = {{tmp_16_fu_3537_p4}, {7'd0}};

assign tmp_18_fu_3559_p3 = {{tmp_16_fu_3537_p4}, {3'd0}};

assign tmp_fu_3632_p3 = {{a_reg_4206}, {8'd0}};

always @ (posedge ap_clk) begin
    sub_ln73_reg_4262[7:0] <= 8'b00000000;
end

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s
