-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_val : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_3FFFBA4 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101110100100";
    constant ap_const_lv26_5EF : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010111101111";
    constant ap_const_lv26_3A9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001110101001";
    constant ap_const_lv26_1DE : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111011110";
    constant ap_const_lv26_10A : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100001010";
    constant ap_const_lv26_3FFFEEB : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011101011";
    constant ap_const_lv26_3FFFD9E : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110011110";
    constant ap_const_lv26_2EC : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001011101100";
    constant ap_const_lv26_124 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100100100";
    constant ap_const_lv26_3FFFE98 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111010011000";
    constant ap_const_lv25_F6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000011110110";
    constant ap_const_lv26_1C5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111000101";
    constant ap_const_lv26_3E1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001111100001";
    constant ap_const_lv26_3FFFCF7 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110011110111";
    constant ap_const_lv26_3FFFEE8 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011101000";
    constant ap_const_lv26_3FFFB41 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101101000001";
    constant ap_const_lv25_1FFFF05 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111100000101";
    constant ap_const_lv26_216 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000010110";
    constant ap_const_lv26_3FFFEB5 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111010110101";
    constant ap_const_lv26_3FFFD77 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110101110111";
    constant ap_const_lv26_19F : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110011111";
    constant ap_const_lv26_3FFFDBB : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110111011";
    constant ap_const_lv25_8B : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010001011";
    constant ap_const_lv26_283 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010000011";
    constant ap_const_lv26_3FFFE38 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000111000";
    constant ap_const_lv26_3FFFCFE : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110011111110";
    constant ap_const_lv26_3FFFD5B : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110101011011";
    constant ap_const_lv26_3FFFC3C : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110000111100";
    constant ap_const_lv24_4B : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001001011";
    constant ap_const_lv26_23C : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000111100";
    constant ap_const_lv64_10 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv64_20 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000100000";
    constant ap_const_lv64_30 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000110000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_A0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010100000";
    constant ap_const_lv16_212 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000010010";
    constant ap_const_lv16_FEBE : STD_LOGIC_VECTOR (15 downto 0) := "1111111010111110";
    constant ap_const_lv16_DA : STD_LOGIC_VECTOR (15 downto 0) := "0000000011011010";
    constant ap_const_lv16_3DC : STD_LOGIC_VECTOR (15 downto 0) := "0000001111011100";
    constant ap_const_lv16_39F : STD_LOGIC_VECTOR (15 downto 0) := "0000001110011111";
    constant ap_const_lv16_2FB : STD_LOGIC_VECTOR (15 downto 0) := "0000001011111011";
    constant ap_const_lv16_B0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010110000";

attribute shreg_extract : string;
    signal a_fu_3525_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_reg_4206 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal a_reg_4206_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a_2_reg_4214 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_94_reg_4220 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln42_94_reg_4220_pp0_iter1_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln42_94_reg_4220_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal a_3_reg_4225 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_34_fu_3608_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_22_fu_3623_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln73_fu_3643_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln73_reg_4262 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_24_fu_3653_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_25_fu_3662_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_107_reg_4298 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_108_reg_4303 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_109_reg_4308 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_110_reg_4313 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_111_reg_4318 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_112_reg_4323 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_113_reg_4328 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_114_reg_4333 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_4338 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_reg_4343 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_85_reg_4348 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_86_reg_4353 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_87_reg_4358 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln42_88_reg_4363 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_89_reg_4368 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_90_reg_4373 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_91_reg_4378 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_92_reg_4383 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_93_reg_4388 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_95_reg_4393 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_96_reg_4398 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_97_reg_4403 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_98_reg_4408 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_99_reg_4413 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_100_reg_4418 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_101_reg_4423 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_102_reg_4428 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_103_reg_4433 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_104_reg_4438 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_105_reg_4443 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_106_reg_4448 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_87_fu_4005_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_87_reg_4453 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_91_fu_4010_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_91_reg_4458 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_95_fu_4015_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_95_reg_4463 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_99_fu_4020_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_99_reg_4468 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_103_fu_4025_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_103_reg_4473 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_107_fu_4030_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_107_reg_4478 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_111_fu_4035_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_111_reg_4483 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_115_fu_4041_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_115_reg_4488 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_4058_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_reg_4493 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_88_fu_4062_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_88_reg_4498 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_90_fu_4066_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_90_reg_4503 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_92_fu_4070_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_92_reg_4508 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_94_fu_4074_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_94_reg_4513 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_96_fu_4078_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_96_reg_4518 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_98_fu_4083_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_98_reg_4523 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_100_fu_4088_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_100_reg_4528 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_102_fu_4092_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_102_reg_4533 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_104_fu_4097_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_104_reg_4538 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_106_fu_4101_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_106_reg_4543 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_108_fu_4105_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_108_reg_4548 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_110_fu_4109_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_110_reg_4553 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_112_fu_4114_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_112_reg_4558 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_114_fu_4118_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_114_reg_4563 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_116_fu_4122_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_116_reg_4568 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_146_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_146_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_147_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_147_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_148_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_148_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_149_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_149_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_150_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_150_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_151_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_151_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_152_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_152_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_153_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_153_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_154_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_154_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_155_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_155_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_156_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_157_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_157_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_159_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_159_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_160_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_160_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_161_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_161_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_162_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_162_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_163_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_164_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_164_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_165_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_165_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_166_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_166_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_167_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_167_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_168_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_168_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_169_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_170_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_170_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_171_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_171_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_172_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_172_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_173_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_173_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_174_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_174_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_176_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_177_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_177_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_16_fu_3537_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_fu_3547_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_18_fu_3559_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln73_17_fu_3567_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln73_16_fu_3555_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sub_ln73_7_fu_3571_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_4_fu_3595_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_3632_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln73_fu_3639_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_151_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_154_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_167_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_162_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_173_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_146_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_156_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_147_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_15_fu_3756_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln73_15_fu_3763_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln73_6_fu_3767_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_166_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_165_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_152_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_176_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_170_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_148_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_164_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_177_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_159_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_157_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_150_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_160_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_169_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_171_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_172_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_168_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_163_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_174_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_161_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_155_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_149_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_153_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_35_fu_4002_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_33_fu_4055_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_31_fu_4049_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_4046_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_32_fu_4052_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_89_fu_4126_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_93_fu_4130_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_97_fu_4134_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_101_fu_4138_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_105_fu_4142_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_109_fu_4146_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_113_fu_4150_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_117_fu_4154_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_146_ce : STD_LOGIC;
    signal grp_fu_147_ce : STD_LOGIC;
    signal grp_fu_148_ce : STD_LOGIC;
    signal grp_fu_149_ce : STD_LOGIC;
    signal grp_fu_150_ce : STD_LOGIC;
    signal grp_fu_151_ce : STD_LOGIC;
    signal grp_fu_152_ce : STD_LOGIC;
    signal grp_fu_153_ce : STD_LOGIC;
    signal grp_fu_154_ce : STD_LOGIC;
    signal grp_fu_155_ce : STD_LOGIC;
    signal grp_fu_156_ce : STD_LOGIC;
    signal grp_fu_157_ce : STD_LOGIC;
    signal grp_fu_159_ce : STD_LOGIC;
    signal grp_fu_160_ce : STD_LOGIC;
    signal grp_fu_161_ce : STD_LOGIC;
    signal grp_fu_162_ce : STD_LOGIC;
    signal grp_fu_163_ce : STD_LOGIC;
    signal grp_fu_164_ce : STD_LOGIC;
    signal grp_fu_165_ce : STD_LOGIC;
    signal grp_fu_166_ce : STD_LOGIC;
    signal grp_fu_167_ce : STD_LOGIC;
    signal grp_fu_168_ce : STD_LOGIC;
    signal grp_fu_169_ce : STD_LOGIC;
    signal grp_fu_170_ce : STD_LOGIC;
    signal grp_fu_171_ce : STD_LOGIC;
    signal grp_fu_172_ce : STD_LOGIC;
    signal grp_fu_173_ce : STD_LOGIC;
    signal grp_fu_174_ce : STD_LOGIC;
    signal grp_fu_176_ce : STD_LOGIC;
    signal grp_fu_177_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal data_val_int_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_5_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_6_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_7_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component myproject_mul_16s_12s_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_12ns_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11ns_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10ns_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10s_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11s_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_9ns_25_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component myproject_mul_16s_9s_25_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component myproject_mul_16s_8ns_24_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    mul_16s_12s_26_2_0_U1 : component myproject_mul_16s_12s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_146_p0,
        din1 => grp_fu_146_p1,
        ce => grp_fu_146_ce,
        dout => grp_fu_146_p2);

    mul_16s_12ns_26_2_0_U2 : component myproject_mul_16s_12ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_147_p0,
        din1 => grp_fu_147_p1,
        ce => grp_fu_147_ce,
        dout => grp_fu_147_p2);

    mul_16s_11ns_26_2_0_U3 : component myproject_mul_16s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_148_p0,
        din1 => grp_fu_148_p1,
        ce => grp_fu_148_ce,
        dout => grp_fu_148_p2);

    mul_16s_10ns_26_2_0_U4 : component myproject_mul_16s_10ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_149_p0,
        din1 => grp_fu_149_p1,
        ce => grp_fu_149_ce,
        dout => grp_fu_149_p2);

    mul_16s_10ns_26_2_0_U5 : component myproject_mul_16s_10ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_150_p0,
        din1 => grp_fu_150_p1,
        ce => grp_fu_150_ce,
        dout => grp_fu_150_p2);

    mul_16s_10s_26_2_0_U6 : component myproject_mul_16s_10s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_151_p0,
        din1 => grp_fu_151_p1,
        ce => grp_fu_151_ce,
        dout => grp_fu_151_p2);

    mul_16s_11s_26_2_0_U7 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_152_p0,
        din1 => grp_fu_152_p1,
        ce => grp_fu_152_ce,
        dout => grp_fu_152_p2);

    mul_16s_11ns_26_2_0_U8 : component myproject_mul_16s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_153_p0,
        din1 => grp_fu_153_p1,
        ce => grp_fu_153_ce,
        dout => grp_fu_153_p2);

    mul_16s_10ns_26_2_0_U9 : component myproject_mul_16s_10ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_154_p0,
        din1 => grp_fu_154_p1,
        ce => grp_fu_154_ce,
        dout => grp_fu_154_p2);

    mul_16s_10s_26_2_0_U10 : component myproject_mul_16s_10s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_155_p0,
        din1 => grp_fu_155_p1,
        ce => grp_fu_155_ce,
        dout => grp_fu_155_p2);

    mul_16s_9ns_25_2_0_U11 : component myproject_mul_16s_9ns_25_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_4_fu_3595_p3,
        din1 => grp_fu_156_p1,
        ce => grp_fu_156_ce,
        dout => grp_fu_156_p2);

    mul_16s_10ns_26_2_0_U12 : component myproject_mul_16s_10ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_157_p0,
        din1 => grp_fu_157_p1,
        ce => grp_fu_157_ce,
        dout => grp_fu_157_p2);

    mul_16s_11ns_26_2_0_U13 : component myproject_mul_16s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_159_p0,
        din1 => grp_fu_159_p1,
        ce => grp_fu_159_ce,
        dout => grp_fu_159_p2);

    mul_16s_11s_26_2_0_U14 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_160_p0,
        din1 => grp_fu_160_p1,
        ce => grp_fu_160_ce,
        dout => grp_fu_160_p2);

    mul_16s_10s_26_2_0_U15 : component myproject_mul_16s_10s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_161_p0,
        din1 => grp_fu_161_p1,
        ce => grp_fu_161_ce,
        dout => grp_fu_161_p2);

    mul_16s_12s_26_2_0_U16 : component myproject_mul_16s_12s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_162_p0,
        din1 => grp_fu_162_p1,
        ce => grp_fu_162_ce,
        dout => grp_fu_162_p2);

    mul_16s_9s_25_2_0_U17 : component myproject_mul_16s_9s_25_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_3_reg_4225,
        din1 => grp_fu_163_p1,
        ce => grp_fu_163_ce,
        dout => grp_fu_163_p2);

    mul_16s_11ns_26_2_0_U18 : component myproject_mul_16s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_164_p0,
        din1 => grp_fu_164_p1,
        ce => grp_fu_164_ce,
        dout => grp_fu_164_p2);

    mul_16s_10s_26_2_0_U19 : component myproject_mul_16s_10s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_165_p0,
        din1 => grp_fu_165_p1,
        ce => grp_fu_165_ce,
        dout => grp_fu_165_p2);

    mul_16s_11s_26_2_0_U20 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_166_p0,
        din1 => grp_fu_166_p1,
        ce => grp_fu_166_ce,
        dout => grp_fu_166_p2);

    mul_16s_10ns_26_2_0_U21 : component myproject_mul_16s_10ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_167_p0,
        din1 => grp_fu_167_p1,
        ce => grp_fu_167_ce,
        dout => grp_fu_167_p2);

    mul_16s_11s_26_2_0_U22 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_168_p0,
        din1 => grp_fu_168_p1,
        ce => grp_fu_168_ce,
        dout => grp_fu_168_p2);

    mul_16s_9ns_25_2_0_U23 : component myproject_mul_16s_9ns_25_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_2_reg_4214,
        din1 => grp_fu_169_p1,
        ce => grp_fu_169_ce,
        dout => grp_fu_169_p2);

    mul_16s_11ns_26_2_0_U24 : component myproject_mul_16s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_170_p0,
        din1 => grp_fu_170_p1,
        ce => grp_fu_170_ce,
        dout => grp_fu_170_p2);

    mul_16s_10s_26_2_0_U25 : component myproject_mul_16s_10s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_171_p0,
        din1 => grp_fu_171_p1,
        ce => grp_fu_171_ce,
        dout => grp_fu_171_p2);

    mul_16s_11s_26_2_0_U26 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_172_p0,
        din1 => grp_fu_172_p1,
        ce => grp_fu_172_ce,
        dout => grp_fu_172_p2);

    mul_16s_11s_26_2_0_U27 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_173_p0,
        din1 => grp_fu_173_p1,
        ce => grp_fu_173_ce,
        dout => grp_fu_173_p2);

    mul_16s_11s_26_2_0_U28 : component myproject_mul_16s_11s_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_174_p0,
        din1 => grp_fu_174_p1,
        ce => grp_fu_174_ce,
        dout => grp_fu_174_p2);

    mul_16s_8ns_24_2_0_U29 : component myproject_mul_16s_8ns_24_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_reg_4206,
        din1 => grp_fu_176_p1,
        ce => grp_fu_176_ce,
        dout => grp_fu_176_p2);

    mul_16s_11ns_26_2_0_U30 : component myproject_mul_16s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_177_p0,
        din1 => grp_fu_177_p1,
        ce => grp_fu_177_ce,
        dout => grp_fu_177_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                a_2_reg_4214 <= data_val_int_reg(31 downto 16);
                a_3_reg_4225 <= data_val_int_reg(47 downto 32);
                a_reg_4206 <= a_fu_3525_p1;
                a_reg_4206_pp0_iter1_reg <= a_reg_4206;
                add_ln58_100_reg_4528 <= add_ln58_100_fu_4088_p2;
                add_ln58_102_reg_4533 <= add_ln58_102_fu_4092_p2;
                add_ln58_103_reg_4473 <= add_ln58_103_fu_4025_p2;
                add_ln58_104_reg_4538 <= add_ln58_104_fu_4097_p2;
                add_ln58_106_reg_4543 <= add_ln58_106_fu_4101_p2;
                add_ln58_107_reg_4478 <= add_ln58_107_fu_4030_p2;
                add_ln58_108_reg_4548 <= add_ln58_108_fu_4105_p2;
                add_ln58_110_reg_4553 <= add_ln58_110_fu_4109_p2;
                add_ln58_111_reg_4483 <= add_ln58_111_fu_4035_p2;
                add_ln58_112_reg_4558 <= add_ln58_112_fu_4114_p2;
                add_ln58_114_reg_4563 <= add_ln58_114_fu_4118_p2;
                add_ln58_115_reg_4488 <= add_ln58_115_fu_4041_p2;
                add_ln58_116_reg_4568 <= add_ln58_116_fu_4122_p2;
                add_ln58_87_reg_4453 <= add_ln58_87_fu_4005_p2;
                add_ln58_88_reg_4498 <= add_ln58_88_fu_4062_p2;
                add_ln58_90_reg_4503 <= add_ln58_90_fu_4066_p2;
                add_ln58_91_reg_4458 <= add_ln58_91_fu_4010_p2;
                add_ln58_92_reg_4508 <= add_ln58_92_fu_4070_p2;
                add_ln58_94_reg_4513 <= add_ln58_94_fu_4074_p2;
                add_ln58_95_reg_4463 <= add_ln58_95_fu_4015_p2;
                add_ln58_96_reg_4518 <= add_ln58_96_fu_4078_p2;
                add_ln58_98_reg_4523 <= add_ln58_98_fu_4083_p2;
                add_ln58_99_reg_4468 <= add_ln58_99_fu_4020_p2;
                add_ln58_reg_4493 <= add_ln58_fu_4058_p2;
                    sub_ln73_reg_4262(25 downto 8) <= sub_ln73_fu_3643_p2(25 downto 8);
                trunc_ln42_100_reg_4418 <= grp_fu_168_p2(25 downto 10);
                trunc_ln42_101_reg_4423 <= grp_fu_163_p2(24 downto 10);
                trunc_ln42_102_reg_4428 <= grp_fu_174_p2(25 downto 10);
                trunc_ln42_103_reg_4433 <= grp_fu_161_p2(25 downto 10);
                trunc_ln42_104_reg_4438 <= grp_fu_155_p2(25 downto 10);
                trunc_ln42_105_reg_4443 <= grp_fu_149_p2(25 downto 10);
                trunc_ln42_106_reg_4448 <= grp_fu_153_p2(25 downto 10);
                trunc_ln42_107_reg_4298 <= grp_fu_151_p2(25 downto 10);
                trunc_ln42_108_reg_4303 <= grp_fu_154_p2(25 downto 10);
                trunc_ln42_109_reg_4308 <= grp_fu_167_p2(25 downto 10);
                trunc_ln42_110_reg_4313 <= grp_fu_162_p2(25 downto 10);
                trunc_ln42_111_reg_4318 <= grp_fu_173_p2(25 downto 10);
                trunc_ln42_112_reg_4323 <= grp_fu_146_p2(25 downto 10);
                trunc_ln42_113_reg_4328 <= grp_fu_156_p2(24 downto 10);
                trunc_ln42_114_reg_4333 <= grp_fu_147_p2(25 downto 10);
                trunc_ln42_85_reg_4348 <= grp_fu_165_p2(25 downto 10);
                trunc_ln42_86_reg_4353 <= grp_fu_152_p2(25 downto 10);
                trunc_ln42_87_reg_4358 <= grp_fu_176_p2(23 downto 10);
                trunc_ln42_88_reg_4363 <= grp_fu_170_p2(25 downto 10);
                trunc_ln42_89_reg_4368 <= grp_fu_148_p2(25 downto 10);
                trunc_ln42_90_reg_4373 <= grp_fu_164_p2(25 downto 10);
                trunc_ln42_91_reg_4378 <= grp_fu_177_p2(25 downto 10);
                trunc_ln42_92_reg_4383 <= grp_fu_159_p2(25 downto 10);
                trunc_ln42_93_reg_4388 <= grp_fu_157_p2(25 downto 10);
                trunc_ln42_94_reg_4220 <= sub_ln73_7_fu_3571_p2(23 downto 10);
                trunc_ln42_94_reg_4220_pp0_iter1_reg <= trunc_ln42_94_reg_4220;
                trunc_ln42_94_reg_4220_pp0_iter2_reg <= trunc_ln42_94_reg_4220_pp0_iter1_reg;
                trunc_ln42_95_reg_4393 <= grp_fu_150_p2(25 downto 10);
                trunc_ln42_96_reg_4398 <= grp_fu_160_p2(25 downto 10);
                trunc_ln42_97_reg_4403 <= grp_fu_169_p2(24 downto 10);
                trunc_ln42_98_reg_4408 <= grp_fu_171_p2(25 downto 10);
                trunc_ln42_99_reg_4413 <= grp_fu_172_p2(25 downto 10);
                trunc_ln42_s_reg_4343 <= grp_fu_166_p2(25 downto 10);
                trunc_ln_reg_4338 <= sub_ln73_6_fu_3767_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln58_89_fu_4126_p2;
                ap_return_1_int_reg <= add_ln58_93_fu_4130_p2;
                ap_return_2_int_reg <= add_ln58_97_fu_4134_p2;
                ap_return_3_int_reg <= add_ln58_101_fu_4138_p2;
                ap_return_4_int_reg <= add_ln58_105_fu_4142_p2;
                ap_return_5_int_reg <= add_ln58_109_fu_4146_p2;
                ap_return_6_int_reg <= add_ln58_113_fu_4150_p2;
                ap_return_7_int_reg <= add_ln58_117_fu_4154_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                data_val_int_reg <= data_val;
            end if;
        end if;
    end process;
    sub_ln73_reg_4262(7 downto 0) <= "00000000";
    a_4_fu_3595_p3 <= data_val_int_reg(63 downto 48);
    a_fu_3525_p1 <= data_val_int_reg(16 - 1 downto 0);
    add_ln58_100_fu_4088_p2 <= std_logic_vector(unsigned(add_ln58_99_reg_4468) + unsigned(trunc_ln42_102_reg_4428));
    add_ln58_101_fu_4138_p2 <= std_logic_vector(unsigned(add_ln58_100_reg_4528) + unsigned(add_ln58_98_reg_4523));
    add_ln58_102_fu_4092_p2 <= std_logic_vector(signed(sext_ln42_fu_4046_p1) + signed(trunc_ln42_95_reg_4393));
    add_ln58_103_fu_4025_p2 <= std_logic_vector(unsigned(trunc_ln42_111_reg_4318) + unsigned(ap_const_lv16_3DC));
    add_ln58_104_fu_4097_p2 <= std_logic_vector(unsigned(add_ln58_103_reg_4473) + unsigned(trunc_ln42_103_reg_4433));
    add_ln58_105_fu_4142_p2 <= std_logic_vector(unsigned(add_ln58_104_reg_4538) + unsigned(add_ln58_102_reg_4533));
    add_ln58_106_fu_4101_p2 <= std_logic_vector(unsigned(trunc_ln42_88_reg_4363) + unsigned(trunc_ln42_96_reg_4398));
    add_ln58_107_fu_4030_p2 <= std_logic_vector(unsigned(trunc_ln42_112_reg_4323) + unsigned(ap_const_lv16_39F));
    add_ln58_108_fu_4105_p2 <= std_logic_vector(unsigned(add_ln58_107_reg_4478) + unsigned(trunc_ln42_104_reg_4438));
    add_ln58_109_fu_4146_p2 <= std_logic_vector(unsigned(add_ln58_108_reg_4548) + unsigned(add_ln58_106_reg_4543));
    add_ln58_110_fu_4109_p2 <= std_logic_vector(unsigned(trunc_ln42_89_reg_4368) + unsigned(sext_ln42_32_fu_4052_p1));
    add_ln58_111_fu_4035_p2 <= std_logic_vector(signed(sext_ln42_35_fu_4002_p1) + signed(ap_const_lv16_2FB));
    add_ln58_112_fu_4114_p2 <= std_logic_vector(unsigned(add_ln58_111_reg_4483) + unsigned(trunc_ln42_105_reg_4443));
    add_ln58_113_fu_4150_p2 <= std_logic_vector(unsigned(add_ln58_112_reg_4558) + unsigned(add_ln58_110_reg_4553));
    add_ln58_114_fu_4118_p2 <= std_logic_vector(unsigned(trunc_ln42_90_reg_4373) + unsigned(trunc_ln42_98_reg_4408));
    add_ln58_115_fu_4041_p2 <= std_logic_vector(unsigned(trunc_ln42_114_reg_4333) + unsigned(ap_const_lv16_B0));
    add_ln58_116_fu_4122_p2 <= std_logic_vector(unsigned(add_ln58_115_reg_4488) + unsigned(trunc_ln42_106_reg_4448));
    add_ln58_117_fu_4154_p2 <= std_logic_vector(unsigned(add_ln58_116_reg_4568) + unsigned(add_ln58_114_reg_4563));
    add_ln58_87_fu_4005_p2 <= std_logic_vector(unsigned(trunc_ln42_107_reg_4298) + unsigned(ap_const_lv16_A0));
    add_ln58_88_fu_4062_p2 <= std_logic_vector(unsigned(add_ln58_87_reg_4453) + unsigned(trunc_ln42_99_reg_4413));
    add_ln58_89_fu_4126_p2 <= std_logic_vector(unsigned(add_ln58_88_reg_4498) + unsigned(add_ln58_reg_4493));
    add_ln58_90_fu_4066_p2 <= std_logic_vector(unsigned(trunc_ln42_s_reg_4343) + unsigned(trunc_ln42_92_reg_4383));
    add_ln58_91_fu_4010_p2 <= std_logic_vector(unsigned(trunc_ln42_108_reg_4303) + unsigned(ap_const_lv16_212));
    add_ln58_92_fu_4070_p2 <= std_logic_vector(unsigned(add_ln58_91_reg_4458) + unsigned(trunc_ln42_100_reg_4418));
    add_ln58_93_fu_4130_p2 <= std_logic_vector(unsigned(add_ln58_92_reg_4508) + unsigned(add_ln58_90_reg_4503));
    add_ln58_94_fu_4074_p2 <= std_logic_vector(unsigned(trunc_ln42_85_reg_4348) + unsigned(trunc_ln42_93_reg_4388));
    add_ln58_95_fu_4015_p2 <= std_logic_vector(unsigned(trunc_ln42_109_reg_4308) + unsigned(ap_const_lv16_FEBE));
    add_ln58_96_fu_4078_p2 <= std_logic_vector(unsigned(add_ln58_95_reg_4463) + unsigned(sext_ln42_33_fu_4055_p1));
    add_ln58_97_fu_4134_p2 <= std_logic_vector(unsigned(add_ln58_96_reg_4518) + unsigned(add_ln58_94_reg_4513));
    add_ln58_98_fu_4083_p2 <= std_logic_vector(unsigned(trunc_ln42_86_reg_4353) + unsigned(sext_ln42_31_fu_4049_p1));
    add_ln58_99_fu_4020_p2 <= std_logic_vector(unsigned(trunc_ln42_110_reg_4313) + unsigned(ap_const_lv16_DA));
    add_ln58_fu_4058_p2 <= std_logic_vector(unsigned(trunc_ln_reg_4338) + unsigned(trunc_ln42_91_reg_4378));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln58_89_fu_4126_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln58_89_fu_4126_p2;
        else 
            ap_return_0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln58_93_fu_4130_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln58_93_fu_4130_p2;
        else 
            ap_return_1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(add_ln58_97_fu_4134_p2, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= add_ln58_97_fu_4134_p2;
        else 
            ap_return_2 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_3_assign_proc : process(add_ln58_101_fu_4138_p2, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= add_ln58_101_fu_4138_p2;
        else 
            ap_return_3 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_4_assign_proc : process(add_ln58_105_fu_4142_p2, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= add_ln58_105_fu_4142_p2;
        else 
            ap_return_4 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_5_assign_proc : process(add_ln58_109_fu_4146_p2, ap_ce_reg, ap_return_5_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_5 <= ap_return_5_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_5 <= add_ln58_109_fu_4146_p2;
        else 
            ap_return_5 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_6_assign_proc : process(add_ln58_113_fu_4150_p2, ap_ce_reg, ap_return_6_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_6 <= ap_return_6_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_6 <= add_ln58_113_fu_4150_p2;
        else 
            ap_return_6 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_7_assign_proc : process(add_ln58_117_fu_4154_p2, ap_ce_reg, ap_return_7_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_7 <= ap_return_7_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_7 <= add_ln58_117_fu_4154_p2;
        else 
            ap_return_7 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_146_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_146_ce <= ap_const_logic_1;
        else 
            grp_fu_146_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_146_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_146_p1 <= ap_const_lv26_3FFFBA4(12 - 1 downto 0);

    grp_fu_147_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_147_ce <= ap_const_logic_1;
        else 
            grp_fu_147_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_147_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_147_p1 <= ap_const_lv26_5EF(12 - 1 downto 0);

    grp_fu_148_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_148_ce <= ap_const_logic_1;
        else 
            grp_fu_148_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_148_p0 <= sext_ln70_22_fu_3623_p1(16 - 1 downto 0);
    grp_fu_148_p1 <= ap_const_lv26_3A9(11 - 1 downto 0);

    grp_fu_149_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_149_ce <= ap_const_logic_1;
        else 
            grp_fu_149_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_149_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_149_p1 <= ap_const_lv26_1DE(10 - 1 downto 0);

    grp_fu_150_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_150_ce <= ap_const_logic_1;
        else 
            grp_fu_150_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_150_p0 <= sext_ln70_24_fu_3653_p1(16 - 1 downto 0);
    grp_fu_150_p1 <= ap_const_lv26_10A(10 - 1 downto 0);

    grp_fu_151_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_151_ce <= ap_const_logic_1;
        else 
            grp_fu_151_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_151_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_151_p1 <= ap_const_lv26_3FFFEEB(10 - 1 downto 0);

    grp_fu_152_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_152_ce <= ap_const_logic_1;
        else 
            grp_fu_152_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_152_p0 <= sext_ln70_22_fu_3623_p1(16 - 1 downto 0);
    grp_fu_152_p1 <= ap_const_lv26_3FFFD9E(11 - 1 downto 0);

    grp_fu_153_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_153_ce <= ap_const_logic_1;
        else 
            grp_fu_153_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_153_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_153_p1 <= ap_const_lv26_2EC(11 - 1 downto 0);

    grp_fu_154_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_154_ce <= ap_const_logic_1;
        else 
            grp_fu_154_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_154_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_154_p1 <= ap_const_lv26_124(10 - 1 downto 0);

    grp_fu_155_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_155_ce <= ap_const_logic_1;
        else 
            grp_fu_155_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_155_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_155_p1 <= ap_const_lv26_3FFFE98(10 - 1 downto 0);

    grp_fu_156_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_156_ce <= ap_const_logic_1;
        else 
            grp_fu_156_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_156_p1 <= ap_const_lv25_F6(9 - 1 downto 0);

    grp_fu_157_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_157_ce <= ap_const_logic_1;
        else 
            grp_fu_157_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_157_p0 <= sext_ln70_24_fu_3653_p1(16 - 1 downto 0);
    grp_fu_157_p1 <= ap_const_lv26_1C5(10 - 1 downto 0);

    grp_fu_159_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_159_ce <= ap_const_logic_1;
        else 
            grp_fu_159_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_159_p0 <= sext_ln70_24_fu_3653_p1(16 - 1 downto 0);
    grp_fu_159_p1 <= ap_const_lv26_3E1(11 - 1 downto 0);

    grp_fu_160_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_160_ce <= ap_const_logic_1;
        else 
            grp_fu_160_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_160_p0 <= sext_ln70_24_fu_3653_p1(16 - 1 downto 0);
    grp_fu_160_p1 <= ap_const_lv26_3FFFCF7(11 - 1 downto 0);

    grp_fu_161_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_161_ce <= ap_const_logic_1;
        else 
            grp_fu_161_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_161_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_161_p1 <= ap_const_lv26_3FFFEE8(10 - 1 downto 0);

    grp_fu_162_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_162_ce <= ap_const_logic_1;
        else 
            grp_fu_162_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_162_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_162_p1 <= ap_const_lv26_3FFFB41(12 - 1 downto 0);

    grp_fu_163_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_163_ce <= ap_const_logic_1;
        else 
            grp_fu_163_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_163_p1 <= ap_const_lv25_1FFFF05(9 - 1 downto 0);

    grp_fu_164_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_164_ce <= ap_const_logic_1;
        else 
            grp_fu_164_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_164_p0 <= sext_ln70_22_fu_3623_p1(16 - 1 downto 0);
    grp_fu_164_p1 <= ap_const_lv26_216(11 - 1 downto 0);

    grp_fu_165_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_165_ce <= ap_const_logic_1;
        else 
            grp_fu_165_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_165_p0 <= sext_ln70_22_fu_3623_p1(16 - 1 downto 0);
    grp_fu_165_p1 <= ap_const_lv26_3FFFEB5(10 - 1 downto 0);

    grp_fu_166_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_166_ce <= ap_const_logic_1;
        else 
            grp_fu_166_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_166_p0 <= sext_ln70_22_fu_3623_p1(16 - 1 downto 0);
    grp_fu_166_p1 <= ap_const_lv26_3FFFD77(11 - 1 downto 0);

    grp_fu_167_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_167_ce <= ap_const_logic_1;
        else 
            grp_fu_167_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_167_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_167_p1 <= ap_const_lv26_19F(10 - 1 downto 0);

    grp_fu_168_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_168_ce <= ap_const_logic_1;
        else 
            grp_fu_168_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_168_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_168_p1 <= ap_const_lv26_3FFFDBB(11 - 1 downto 0);

    grp_fu_169_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_169_ce <= ap_const_logic_1;
        else 
            grp_fu_169_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_169_p1 <= ap_const_lv25_8B(9 - 1 downto 0);

    grp_fu_170_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_170_ce <= ap_const_logic_1;
        else 
            grp_fu_170_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_170_p0 <= sext_ln70_22_fu_3623_p1(16 - 1 downto 0);
    grp_fu_170_p1 <= ap_const_lv26_283(11 - 1 downto 0);

    grp_fu_171_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_171_ce <= ap_const_logic_1;
        else 
            grp_fu_171_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_171_p0 <= sext_ln70_24_fu_3653_p1(16 - 1 downto 0);
    grp_fu_171_p1 <= ap_const_lv26_3FFFE38(10 - 1 downto 0);

    grp_fu_172_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_172_ce <= ap_const_logic_1;
        else 
            grp_fu_172_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_172_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_172_p1 <= ap_const_lv26_3FFFCFE(11 - 1 downto 0);

    grp_fu_173_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_173_ce <= ap_const_logic_1;
        else 
            grp_fu_173_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_173_p0 <= sext_ln42_34_fu_3608_p1(16 - 1 downto 0);
    grp_fu_173_p1 <= ap_const_lv26_3FFFD5B(11 - 1 downto 0);

    grp_fu_174_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_174_ce <= ap_const_logic_1;
        else 
            grp_fu_174_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_174_p0 <= sext_ln70_25_fu_3662_p1(16 - 1 downto 0);
    grp_fu_174_p1 <= ap_const_lv26_3FFFC3C(11 - 1 downto 0);

    grp_fu_176_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_176_ce <= ap_const_logic_1;
        else 
            grp_fu_176_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_176_p1 <= ap_const_lv24_4B(8 - 1 downto 0);

    grp_fu_177_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_177_ce <= ap_const_logic_1;
        else 
            grp_fu_177_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_177_p0 <= sext_ln70_24_fu_3653_p1(16 - 1 downto 0);
    grp_fu_177_p1 <= ap_const_lv26_23C(11 - 1 downto 0);
        sext_ln42_31_fu_4049_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_94_reg_4220_pp0_iter2_reg),16));

        sext_ln42_32_fu_4052_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_97_reg_4403),16));

        sext_ln42_33_fu_4055_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_101_reg_4423),16));

        sext_ln42_34_fu_3608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_4_fu_3595_p3),26));

        sext_ln42_35_fu_4002_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_113_reg_4328),16));

        sext_ln42_fu_4046_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_87_reg_4358),16));

        sext_ln70_22_fu_3623_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_reg_4206),26));

        sext_ln70_24_fu_3653_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_2_reg_4214),26));

        sext_ln70_25_fu_3662_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_3_reg_4225),26));

        sext_ln73_15_fu_3763_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_3756_p3),26));

        sext_ln73_16_fu_3555_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_3547_p3),24));

        sext_ln73_17_fu_3567_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_3559_p3),24));

        sext_ln73_fu_3639_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_3632_p3),26));

    sub_ln73_6_fu_3767_p2 <= std_logic_vector(unsigned(sub_ln73_reg_4262) - unsigned(sext_ln73_15_fu_3763_p1));
    sub_ln73_7_fu_3571_p2 <= std_logic_vector(signed(sext_ln73_17_fu_3567_p1) - signed(sext_ln73_16_fu_3555_p1));
    sub_ln73_fu_3643_p2 <= std_logic_vector(unsigned(ap_const_lv26_0) - unsigned(sext_ln73_fu_3639_p1));
    tmp_15_fu_3756_p3 <= (a_reg_4206_pp0_iter1_reg & ap_const_lv2_0);
    tmp_16_fu_3537_p4 <= data_val_int_reg(31 downto 16);
    tmp_17_fu_3547_p3 <= (tmp_16_fu_3537_p4 & ap_const_lv7_0);
    tmp_18_fu_3559_p3 <= (tmp_16_fu_3537_p4 & ap_const_lv3_0);
    tmp_fu_3632_p3 <= (a_reg_4206 & ap_const_lv8_0);
end behav;
