-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_2_val_read_reg_331 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal a_fu_124_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_reg_336 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln66_1_fu_132_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln66_1_reg_342 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln66_1_reg_342_pp0_iter1_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_fu_136_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_reg_348 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_reg_348_pp0_iter1_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_1_fu_140_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_1_reg_353 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_1_reg_353_pp0_iter1_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_fu_157_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_reg_358 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_reg_365 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_reg_370 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_reg_375 : STD_LOGIC_VECTOR (9 downto 0);
    signal a_1_reg_395 : STD_LOGIC_VECTOR (10 downto 0);
    signal a_1_reg_395_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal a_1_reg_395_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal a_1_reg_395_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal b_reg_401 : STD_LOGIC_VECTOR (10 downto 0);
    signal b_reg_401_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal b_reg_401_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal b_reg_401_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal b_1_reg_407 : STD_LOGIC_VECTOR (10 downto 0);
    signal b_1_reg_407_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal b_1_reg_407_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal b_1_reg_407_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_reg_413 : STD_LOGIC_VECTOR (3 downto 0);
    signal inv_exp_sum_reg_423 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln270_fu_253_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln258_fu_206_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln258_1_fu_210_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_2_fu_214_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln267_fu_249_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exp_table_ce2_local : STD_LOGIC;
    signal exp_table_ce1_local : STD_LOGIC;
    signal exp_table_ce0_local : STD_LOGIC;
    signal invert_table_ce0_local : STD_LOGIC;
    signal icmp_ln66_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_154_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_fu_164_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_1_fu_168_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_2_fu_172_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln141_fu_218_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_fu_224_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_1_fu_227_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln141_1_fu_221_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_fu_233_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_259_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_259_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_268_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_268_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_277_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_277_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_259_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_268_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_259_ce : STD_LOGIC;
    signal grp_fu_268_ce : STD_LOGIC;
    signal grp_fu_277_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal data_0_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_1_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_2_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_259_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_268_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_277_p10 : STD_LOGIC_VECTOR (25 downto 0);

    component myproject_mul_18s_11ns_26_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0_local,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1_local,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2_local,
        q2 => exp_table_q2);

    invert_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0_local,
        q0 => invert_table_q0);

    mul_18s_11ns_26_2_0_U153 : component myproject_mul_18s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_259_p0,
        din1 => grp_fu_259_p1,
        ce => grp_fu_259_ce,
        dout => grp_fu_259_p2);

    mul_18s_11ns_26_2_0_U154 : component myproject_mul_18s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_268_p0,
        din1 => grp_fu_268_p1,
        ce => grp_fu_268_ce,
        dout => grp_fu_268_p2);

    mul_18s_11ns_26_2_0_U155 : component myproject_mul_18s_11ns_26_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_277_p0,
        din1 => grp_fu_277_p1,
        ce => grp_fu_277_ce,
        dout => grp_fu_277_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                a_1_reg_395 <= exp_table_q2;
                a_1_reg_395_pp0_iter5_reg <= a_1_reg_395;
                a_1_reg_395_pp0_iter6_reg <= a_1_reg_395_pp0_iter5_reg;
                a_1_reg_395_pp0_iter7_reg <= a_1_reg_395_pp0_iter6_reg;
                a_reg_336 <= a_fu_124_p3;
                b_1_reg_407 <= exp_table_q0;
                b_1_reg_407_pp0_iter5_reg <= b_1_reg_407;
                b_1_reg_407_pp0_iter6_reg <= b_1_reg_407_pp0_iter5_reg;
                b_1_reg_407_pp0_iter7_reg <= b_1_reg_407_pp0_iter6_reg;
                b_reg_401 <= exp_table_q1;
                b_reg_401_pp0_iter5_reg <= b_reg_401;
                b_reg_401_pp0_iter6_reg <= b_reg_401_pp0_iter5_reg;
                b_reg_401_pp0_iter7_reg <= b_reg_401_pp0_iter6_reg;
                data_2_val_read_reg_331 <= data_2_val_int_reg;
                inv_exp_sum_reg_423 <= invert_table_q0;
                select_ln66_reg_358 <= select_ln66_fu_157_p3;
                tmp_1_reg_413 <= add_ln51_fu_233_p2(11 downto 8);
                tmp_2_reg_370 <= x_1_fu_168_p2(14 downto 5);
                tmp_4_reg_375 <= x_2_fu_172_p2(14 downto 5);
                tmp_reg_365 <= x_fu_164_p2(14 downto 5);
                trunc_ln248_1_reg_353 <= trunc_ln248_1_fu_140_p1;
                trunc_ln248_1_reg_353_pp0_iter1_reg <= trunc_ln248_1_reg_353;
                trunc_ln248_reg_348 <= trunc_ln248_fu_136_p1;
                trunc_ln248_reg_348_pp0_iter1_reg <= trunc_ln248_reg_348;
                trunc_ln66_1_reg_342 <= trunc_ln66_1_fu_132_p1;
                trunc_ln66_1_reg_342_pp0_iter1_reg <= trunc_ln66_1_reg_342;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= grp_fu_259_p2(25 downto 10);
                ap_return_1_int_reg <= grp_fu_268_p2(25 downto 10);
                ap_return_2_int_reg <= grp_fu_277_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                data_0_val_int_reg <= data_0_val;
                data_1_val_int_reg <= data_1_val;
                data_2_val_int_reg <= data_2_val;
            end if;
        end if;
    end process;
    a_fu_124_p3 <= 
        data_0_val_int_reg when (xor_ln66_fu_118_p2(0) = '1') else 
        data_1_val_int_reg;
    add_ln51_1_fu_227_p2 <= std_logic_vector(unsigned(zext_ln141_fu_218_p1) + unsigned(zext_ln51_fu_224_p1));
    add_ln51_fu_233_p2 <= std_logic_vector(unsigned(add_ln51_1_fu_227_p2) + unsigned(zext_ln141_1_fu_221_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(grp_fu_259_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= grp_fu_259_p2(25 downto 10);
        else 
            ap_return_0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(grp_fu_268_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= grp_fu_268_p2(25 downto 10);
        else 
            ap_return_1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(grp_fu_277_p2, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= grp_fu_277_p2(25 downto 10);
        else 
            ap_return_2 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    exp_table_address0 <= zext_ln258_2_fu_214_p1(10 - 1 downto 0);
    exp_table_address1 <= zext_ln258_1_fu_210_p1(10 - 1 downto 0);
    exp_table_address2 <= zext_ln258_fu_206_p1(10 - 1 downto 0);

    exp_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_table_ce0_local <= ap_const_logic_1;
        else 
            exp_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_table_ce1_local <= ap_const_logic_1;
        else 
            exp_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_table_ce2_local <= ap_const_logic_1;
        else 
            exp_table_ce2_local <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_259_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_259_ce <= ap_const_logic_1;
        else 
            grp_fu_259_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_259_p0 <= sext_ln270_fu_253_p1(18 - 1 downto 0);
    grp_fu_259_p1 <= grp_fu_259_p10(11 - 1 downto 0);
    grp_fu_259_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_1_reg_395_pp0_iter7_reg),26));

    grp_fu_268_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_268_ce <= ap_const_logic_1;
        else 
            grp_fu_268_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_268_p0 <= sext_ln270_fu_253_p1(18 - 1 downto 0);
    grp_fu_268_p1 <= grp_fu_268_p10(11 - 1 downto 0);
    grp_fu_268_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_reg_401_pp0_iter7_reg),26));

    grp_fu_277_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_277_ce <= ap_const_logic_1;
        else 
            grp_fu_277_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_277_p0 <= sext_ln270_fu_253_p1(18 - 1 downto 0);
    grp_fu_277_p1 <= grp_fu_277_p10(11 - 1 downto 0);
    grp_fu_277_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_1_reg_407_pp0_iter7_reg),26));
    icmp_ln66_1_fu_144_p2 <= "1" when (signed(a_reg_336) < signed(data_2_val_read_reg_331)) else "0";
    icmp_ln66_fu_112_p2 <= "1" when (signed(data_0_val_int_reg) < signed(data_1_val_int_reg)) else "0";
    invert_table_address0 <= zext_ln267_fu_249_p1(10 - 1 downto 0);

    invert_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            invert_table_ce0_local <= ap_const_logic_1;
        else 
            invert_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln66_fu_157_p3 <= 
        trunc_ln66_fu_154_p1 when (xor_ln66_1_fu_148_p2(0) = '1') else 
        trunc_ln66_1_reg_342;
        sext_ln270_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_reg_423),26));

    trunc_ln248_1_fu_140_p1 <= data_1_val_int_reg(15 - 1 downto 0);
    trunc_ln248_fu_136_p1 <= data_0_val_int_reg(15 - 1 downto 0);
    trunc_ln66_1_fu_132_p1 <= data_2_val_int_reg(15 - 1 downto 0);
    trunc_ln66_fu_154_p1 <= a_reg_336(15 - 1 downto 0);
    x_1_fu_168_p2 <= std_logic_vector(unsigned(select_ln66_reg_358) - unsigned(trunc_ln248_1_reg_353_pp0_iter1_reg));
    x_2_fu_172_p2 <= std_logic_vector(unsigned(select_ln66_reg_358) - unsigned(trunc_ln66_1_reg_342_pp0_iter1_reg));
    x_fu_164_p2 <= std_logic_vector(unsigned(select_ln66_reg_358) - unsigned(trunc_ln248_reg_348_pp0_iter1_reg));
    xor_ln66_1_fu_148_p2 <= (icmp_ln66_1_fu_144_p2 xor ap_const_lv1_1);
    xor_ln66_fu_118_p2 <= (icmp_ln66_fu_112_p2 xor ap_const_lv1_1);
    zext_ln141_1_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_reg_401),12));
    zext_ln141_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_1_reg_395),12));
    zext_ln258_1_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_370),64));
    zext_ln258_2_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_375),64));
    zext_ln258_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_365),64));
    zext_ln267_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_413),64));
    zext_ln51_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_1_reg_407),12));
end behav;
